NVIDIA/NVFlare

nvflare/widgets/widget.py
Unit tests are failing due to "New enum creations must be created as ..". This fixes that.
=> Fix enum error

nvflare/app_common/abstract/learner_service_provider_spec.py
3rd party train framework will need to implement / inherits this LearnerServiceProviderSpec to provide functionality of 
"train", "validate", "abort", "initialize", and "finalize".
This is an abstract interface that NVFlare will use.
- Add LearnerServiceProviderSpec
=> Add LearnerServiceProviderSpec

nvflare/apis/analytix.py, nvflare/apis/fl_component.py, nvflare/apis/fl_constant.py, nvflare/app_common/pt/tb_receiver.py, nvflare/app_common/widgets/streaming.py, nvflare/widgets/info_collector.py, test/app_testing/test_apps/tb_streaming/config/config_fed_client.json, test/app_testing/test_apps/tb_streaming/config/config_fed_server.json
- Rename DataType, Data to AnalyticsDataType and AnalyticsData in nvflare/apis/analytix.py
- Add AnalyticsSender which implements the following functions:
- info, debug, error, exception, warning, critical following the method signature of Python logger
- add_scalar, add_scalars, add_text, add_image following the method signature of PyTorch SummaryWriter
- Add a lock for save action in AnalyticsReceiver to ensure thread safety
- Update docstrings
=> Add AnalyticsSender and enhance streaming widgets

nvflare/private/fed/client/communicator.py
When running the NVflare client inside a `runc` container the client IP cannot be resolved because `socket.gethostbyname(socket.gethostname())` raises with `socket.gaierror: [Errno -3] Temporary failure in name resolution`. 
As explained in this [SO](https://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib/28950776#28950776), the method proposed here is more robust and solved the issue.
Thanks @ehlertjd
=> get client IP more robustly

build_doc.sh, docs/faq.rst, docs/user_guide/provisioning_tool.rst
Update documentation to add information about enable_byoc and allow_byoc and what they do in the provisioning process, and have the apidocs pages display better with module-first.
=> Add information about enable_byoc and allow_byoc

docs/quickstart.rst, examples/hello-monai/README.md, examples/hello-numpy-cross-val/README.md, examples/hello-pt/README.md, examples/hello-tf2/README.md
This PR fixes the commands in some README pages of examples where deploy_app is missing the target. Also, this slightly refines the page in the docs introducing the examples and provides a link.
This will close #110.
=> Fix deploy commands missing target in README of examples

nvflare/lighter/poc.py
An unzip executable is not always available, and calling it introduces an unnecessary implicit dependency.
This PR uses `shutil.unpack_archive()` instead.
=> avoid running unzip subprocess in poc.py

.github/workflows/build_docs.yml
Add workflow to build documentation and check it into the docs branch for automatic deployment on the pages site.
This will close #119.
=> Add workflow to build docs automatically

nvflare/apis/event_type.py, nvflare/private/fed/client/client_aux_runner.py, nvflare/private/fed/client/client_runner.py, nvflare/private/fed/client/fed_client_base.py, nvflare/private/fed/server/server_runner.py, nvflare/widgets/fed_event.py
Add ABOUT_TO_END_RUN to flush queue
Allow thread to exit only when queue is empty during END_RUN
Signed-off-by: Isaac Yang <isaacy@nvidia.com>
=> Increase fed event firing frequency

nvflare/apis/dxo.py, nvflare/app_common/aggregators/dxo_aggregator.py, nvflare/app_common/aggregators/intime_accumulate_model_aggregator.py, nvflare/app_common/aggregators/weighted_aggregation_helper.py, test/test_intime_aggregator.py
- Add "aggregation helper" and `DXOAggregator` class to be used in `InTimeAccumulateWeightedAggregator`.
- Introduce new DXO DataKind "COLLECTION". Allows a shareable to contain a DXO with a dict of DXOs that contain different weights. Useful for SCAFFOLD, for example.
- Add new test cases for intime aggregation.
=> add aggregation helper class

nvflare/fuel/hci/client/cli.py
- CredentialType class needs to inherit from str, so that string comparison ``"password" == CredentialType.PASSWORD`` will return True
=> Fix CredentialType

nvflare/apis/app_validation.py, nvflare/apis/workspace.py, nvflare/private/fed/app/default_app_validator.py, nvflare/private/fed/app/fl_app_validator.py, nvflare/private/fed/app/fl_conf.py
Add a default FL AppValidator to ensure the application's structure is valid.
- DefaultAppValidator: Validates an application has config folder and config_fed_server.json and config_fed_client.json inside it.
- FLAppValidator: The built-in FL app validator, by default it contains the DefaultAppValidator
=> Add default FL app validator

nvflare/private/fed/server/server_runner.py
If there are multiple workflows, we need to persist the `wf_index` so that we can resume from there.
=> Persist wf_index in server_runner

docs/user_guide/application.rst
In configurations for components, mention how name and path are used in the documentation.
Fixes #282
=> Documentation: Add information about the usage of name vs path

nvflare/fuel/hci/server/hci.py
Lowered admin connections to 16 so max memory usage is limited to 8GB.
=> Fixes #301 by lowering max admin connections to 16.

examples/cifar10/workspaces/secure_project.yml
Closes https://github.com/NVIDIA/NVFlare/issues/321
Decided to disable byoc by default as CIFAR10 example uses PYTHONPATH rather than custom code inside the app folders. Added comment showing how to enable it.
=> disable byoc in provisioning

nvflare/private/fed/server/job_runner.py
log was missing a white space after Application
2022-04-28 12:39:50,087 - JobRunner - INFO - [run=?]: Applicationcifar10_scaffold deployed to the server for run:2812e375-6054-497c-ae45-b924cafc99ee
2022-04-28 12:39:50,588 - JobRunner - INFO - [run=?]: Applicationcifar10_scaffold deployed to the clients: site-1,site-2,site-3,site-4,site-5,site-6,site-7,site-8 for run:2812e375-6054-497c-ae45-b924cafc99ee
=> Add a white space to log info when deploying an application

nvflare/fuel/hci/client/fl_admin_api_runner.py
admin API commands would cause an error because the API hasn't logged in yet.
This PR adds a check until successful login.
=> Wait for admin login

nvflare/apis/impl/job_def_manager.py
- Use `makedirs` so if intermediate folder is missed, it will also make those folders.
=> use makedirs to auto make intermediate folders if needed

.github/workflows/premerge.yml
Currently we are setting up blossom self-hosted runner. 
If no specific label, the CI may randomly pick unexpected runner to run CI.
This PR is trying to modify `runs-on` for existing workflow first.
=> Modify existing premerge CI to runs-on temp-ci label

nvflare/app_common/workflows/scatter_and_gather.py, nvflare/app_common/workflows/scatter_and_gather_scaffold.py
- Change the default value of `ignore_result_error` from `True` to `False`
=> Change the default value of ignore_result_error in SAG workflows

requirements-dev.txt, runtest.sh, tests/unit_test/app_common/storages/storage_test.py, tests/unit_test/lighter/project_test.py, tests/unit_test/private/fed/server/fed_server_test.py, tests/unit_test/private/fed/server/job_validator_test.py
- Remove minio server setup/teardown in runtest.sh
- Remove S3Storage unit tests
- Change "mock" to use default python system package "unittest.mock"
- Fix format issues
=> Remove minio server in test scripts and fix format issues

examples/cifar10/submit_job.py, examples/prostate/prostate_2D/submit_job.py, examples/prostate/prostate_3D/submit_job.py
following best practices, it is better to explicitly log out of the admin client after submitting a job.
=> logout from admin api after submitting job

requirements-dev.txt, runtest.sh, tests/integration_test/oa_laucher.py
1) refactoring runtests.sh to stream line different functions
check license
check imports, style, format, etc.
fix import format, style
run unit tests with option to turn on coverage test and unit test reports
2) give option to only run sub directories of styles, unit tests.
This make it possible to combine all tests (unit tests and integration tests) under the same command, We might re-name the command from runtests to something more general.
Our code base did not pass pylint and pytype checks, I have to disable both of them for now.
pylint usage may need legal approval due to GPL v2 license. I commented out the dependency and related codes.
=> runtests scripts refactoring

nvflare/apis/fl_context.py, nvflare/private/fed/app/client/worker_process.py, nvflare/private/fed/client/client_executor.py, nvflare/private/fed/client/client_runner.py, nvflare/private/fed/server/job_runner.py, nvflare/private/fed/server/server_engine.py
Fix handling of the following exception scenario:
- server has started the app, but the app code requires library that server did not install so execution exception happens
=> set job run status to `FINISHED: EXECUTION_EXCEPTION`
- client has started the app, but the app code requires library that client did not install so execution exception happens
=> job would stay RUNNING status since server side success
since client side has started but execution exception happens, so the resource is freed.
=> Fix handling of config exception during job running

nvflare/private/fed/server/info_coll_cmd.py
When the user reversed the job_id and the target for the show_stats command, the error would say that the App is not running. Instead, this says what it received as the job_id and specifies which position in the args it is expected to be.
=> revise wording of validation for show_stats

nvflare/fuel/hci/client/fl_admin_api.py, tests/integration_test/admin_controller.py, tests/integration_test/data/fladminapi/execute_fladminapi_commands.yml, tests/integration_test/data/single_app_as_job/test_fladminapi.yml, tests/integration_test/test_cases.yml, tests/integration_test/test_fladminapi.py
Adds a test to execute a chain of FLAdminAPI commands. This adds 30s to the tests and covers most of the FLAdminAPI commands.
Fixes some issues with commands in FLAdminAPI.
Testing clone_job is a bit tricky because the cloned job will be picked up to run and the abort right now does not stop it properly if it is in the SUBMITTED state even with some modifications to job_cmds.py (simply setting the status to FINISHED:ABORTED does not work because it still gets picked up and then the status becomes RUNNING again, but this is another issue from these tests).
=> add tests for running through FLAdminAPI commands

nvflare/app_common/resource_consumers/gpu_resource_consumer.py
- Use PCI_BUS_ID as CUDA_DEVICE_ORDER in GPUResourceConsumer
=> Use PCI_BUS_ID as CUDA_DEVICE_ORDER in GPUResourceConsumer

nvflare/private/fed/app/client/sub_worker_process.py, nvflare/private/fed/app/client/worker_process.py
1. Cherry-pick the monitor parent process exit, then terminate the child process into dev-2.1 branch.
2. Fixed a run_number issue for multi-gpu training.
=> cherrypick the monitor parent process exit to dev-2.1.

docs/faq.rst, docs/programming_guide/system_architecture.rst, docs/quickstart.rst, docs/user_guide/job.rst, docs/user_guide/operation.rst, docs/user_guide/overview.rst
- Fix links after some renaming in docs restructure
- add information on new changes to the deploy_map
- add to FAQ item from QA about aborting server after corrupted snapshot
- add information about permissions for super user for Overseer commands
=> fix links, add information to docs raised from QA

nvflare/ha/ha_admin_cmds.py
api here is not FLAdminAPI but AdminAPI so check_status is not available and do_command needs to be used instead.
Fixes this, and improves exception message to be more clear of what the error is for.
=> fix shutdown_system command

nvflare/private/defs.py, nvflare/private/fed/client/client_engine.py, nvflare/private/fed/client/client_engine_internal_spec.py, nvflare/private/fed/client/scheduler_cmds.py, nvflare/private/fed/server/fed_server.py, nvflare/private/fed/server/job_runner.py, nvflare/private/fed/server/server_engine.py, nvflare/private/fed/utils/fed_utils.py
- Fix event firing
- Fix a situation where `task_id` might be referenced before assignment in `_process_task_request` in `nvflare/private/fed/server/fed_server.py`
- Fix client replies error handling in `nvflare/private/fed/server/job_runner.py`
- Fix return responses in `ClientEngine`
=> Fix resource manager clean up thread calling

nvflare/private/fed/client/client_engine.py
start_app:
- if start_app called when client is in `ClientStatus.STARTED` , this is not an error
abort_app:
- if abort_app called when client is in `ClientStatus.STOPPED` , this is not an error
- if abort_app called when client is in `ClientStatus.NOT_STARTED` , this is not an error
- if abort_app called when client is in `ClientStatus.STARTING`, this is not an error
abort_task:
- if abort_task called when client is in `ClientStatus.NOT_STARTED`, this is not an error
- if abort_task called when client is in `ClientStatus.STARTING`, this is not an error
=> Treat several messages as NON-ERROR execution

examples/cifar10/submit_job.py
Change to unique job name for cifar-10 examples to avoid race condition (writing to the same location) if multiple jobs running in the client machine
=> cifar-10: Use unique dir for datasplits

nvflare/apis/impl/job_def_manager.py, nvflare/apis/job_def.py, nvflare/apis/job_def_manager_spec.py, nvflare/fuel/hci/server/file_transfer.py, nvflare/private/fed/server/job_runner.py, tests/unit_test/apis/impl/job_def_manager_test.py
- Save the workspace to the job permanent storage after the job run complete.
- Delete the server workspace once workspace persisted.
- The download_job include the job run workspace.
- backward compatible with the existing jobs.
=> Save job workspace

.readthedocs.yaml, .readthedocs.yml
Add configuration for readthedocs so we can have 2.0 docs built to resolve #690 
2.0 docs did build with some default settings, but it is still recommended to have this config added.
=> add .readthedocs.yaml to build docs

nvflare/private/fed/client/client_executor.py
- Change print to logger.info in client executor for it to show up in log.txt
=> Change print to logger.info in client executor

nvflare/lighter/impl/docker.py, nvflare/lighter/impl/master_template.yml, nvflare/lighter/impl/workspace.py, nvflare/lighter/project.yml, nvflare/lighter/spec.py
Edit project.yml as before
After provision, one file (compose.yaml) and a folder (nvflare_compose) are created.
Users can do `docker compose build` and `docker compose up` (or `docker-compose build` and `docker-compose up` for old syntax) to launch the overseer, servers and clients in docker compose manner.
The admin client can reach that formation if the /etc/hosts include the ip and hostnames of those participants.
=> Docker compose

nvflare/lighter/impl/docker.py
The shared volume among all servers, for snapshot/job persistence, was accidentally removed during creating compose.yaml.
=> Fix the shared volume settings among servers in compose.yaml

nvflare/private/fed/client/client_runner.py, nvflare/private/fed/client/communicator.py
The engine in client runner should be an instance of ClientEngineExecutorSpec
=> Clean up ClientRunner and Communicator

nvflare/fuel/hci/server/hci.py, nvflare/lighter/impl/helm_chart.py, nvflare/lighter/impl/master_template.yml, nvflare/lighter/project.yml, nvflare/private/fed/server/fed_server.py
Users can deploy overseer and servers to kubernetes cluster with Helm Chart
1. Need to edit ConfigMap of ingress tcp conf and DaemonSet of nginx ingress
2. overseer and server names must be a DNS-1035 label (lower case alphanumeric or '-')
3. machine running clients or consoles must set /etc/hosts for resolving overseer and server names.
=> Helm chart

tests/unit_test/tool/package_checker/utils_test.py
- Use tempfile instead of "hello" since other program might generate this "hello" dir
=> Fix package checker utils test

nvflare/fuel/hci/security.py, nvflare/lighter/impl/cert.py, nvflare/lighter/impl/static_file.py, nvflare/lighter/project.yml, nvflare/lighter/provision.py
Three identity info is retrieved from get_identity_info, common_name, organization and role.
The existing get_certificate_common_name function is not removed for compatibility.
All users have at most one role.
Default client site resource manager changed to GPUResourceManager and args format changed, too.
=> Update cert reading (get_identity_info) and component (resource manager)

integration/monai/examples/spleen_ct_segmentation/README.md, integration/monai/examples/spleen_ct_segmentation/job/app/config/config_fed_server.json, integration/monai/monai_nvflare/monai_bundle_persistor.py, nvflare/app_common/pt/pt_file_model_persistor.py
- Allow to initialize the global model based on bundle configs.
- Update REAMDE to include simulator commands.
- Fixes error message in PTFileModelPersistor and logs info about restoring from ckpt.
=> add MONAI bundle persistor; update readme to include simulator commands

examples/xgboost/custom/xgboost_tree_fed_higgs_learner.py, examples/xgboost/job_configs/higgs_base/higgs_base/config/config_fed_client.json, examples/xgboost/job_configs/higgs_base/higgs_base/config/config_fed_server_bagging.json, examples/xgboost/submit_job.py, nvflare/apis/impl/controller.py, nvflare/app_common/executors/learner_executor.py, nvflare/app_common/learners/xgboost_tree_fed_learner.py, nvflare/app_common/workflows/scatter_and_gather.py, nvflare/fuel/hci/client/fl_admin_api.py, nvflare/fuel/hci/client/fl_admin_api_runner.py, nvflare/private/fed/app/client/client_train.py, nvflare/private/fed/app/simulator/simulator_worker.py, nvflare/private/fed/client/client_app_runner.py, nvflare/private/fed/client/client_json_config.py, nvflare/private/fed/client/client_run_manager.py, nvflare/private/fed/client/client_runner.py, nvflare/private/fed/client/scheduler_cmds.py, nvflare/private/fed/server/server_app_runner.py, nvflare/private/fed/server/server_engine.py, nvflare/private/fed/server/server_json_config.py, nvflare/private/fed/server/server_runner.py, nvflare/private/fed/simulator/simulator_app_runner.py, nvflare/private/json_configer.py
- Make `task_request_interval` configurable
- Make `task_check_period` configurable
- Change `task_fetch_interval` to be set by server side config's `task_request_interval`
- Fix `create_run_manageer` typo -> `create_run_manager`
- Fix `nvflare/private/fed/app/client/client_train.py`
- Fix `nvflare/fuel/hci/client/fl_admin_api_runner.py`
Make the following changes to `ScatterAndGather` workflow:
- Add `task_check_period` parameter, this means how often the controller checks for tasks
- Add `persist_every_n_rounds` parameter, this means how often do we want to call the model persistor to save the global model on server
- Add `snapshot_every_n_rounds`, parameter, this means how often do we want to persist the entire server snapshot
=> Make task_request_interval and task_check_period configurable

nvflare/dashboard/config.py
Requested by reviewers.  30 min is a reasonable value for timeout.  Currently, it's 15 min.
=> Increase token timeout to 30 min

nvflare/app_opt/xgboost/README.rst, nvflare/app_opt/xgboost/histogram_based/executor_base.py
In https://github.com/dmlc/xgboost/pull/8257 the `Rabit` API was switched to `Communicator`.
=> Switch to XGBoost Communicator API

nvflare/fuel/hci/client/fl_admin_api.py, nvflare/private/fed/client/admin.py
- If client side auth error, it only give back "not authorized"
=> Look for not authorized instead of Authorization Error when parsing

nvflare/apis/fl_constant.py, nvflare/apis/server_engine_spec.py, nvflare/private/fed/server/fed_server.py, nvflare/private/fed/server/job_runner.py, nvflare/private/fed/server/server_app_runner.py, nvflare/private/fed/server/server_engine.py, nvflare/private/fed/server/server_runner.py, nvflare/private/fed/simulator/simulator_app_runner.py, tests/unit_test/app_common/job_schedulers/job_scheduler_test.py
Added update_job_run_status to update the proper job run status.
Description:
At the end of ServerAppRunner application job run, it will check if the job run has FLContextKey.FATAL_SYSTEM_ERROR been reported. If it does, then post the job execution exception status to the parent process to update the job FINISHED:FINISHED_EXECUTION_EXCEPTION outcome. Otherwise, the job outcome will be FINISHED:COMPLETED.
system panic and server job exception will mark as FLContextKey.FATAL_SYSTEM_ERROR.
=> Enhance job run status

nvflare/app_common/app_event_type.py, nvflare/app_common/widgets/intime_model_selector.py, tests/unit_test/app_common/widgets/in_time_model_selector_test.py
- Normalize the weighted sum to add to 1.0, following the approach in DXO aggregators.
- Change the behavior of some logging messages to increase user-friendliness.
- Fix event type used for `_before_accept()` logic (using now `AppEventType.BEFORE_CONTRIBUTION_ACCEPT`).
=> update model selector

nvflare/app_common/app_event_type.py, nvflare/app_common/handlers/intime_model_selection_handler.py
- Normalize the weighted sum to add to 1.0, following the approach in DXO aggregators.
- Change the behavior of some logging messages to increase user-friendliness.
- Fix event type used for `_before_accept()` logic (using now `AppEventType.BEFORE_CONTRIBUTION_ACCEPT`).
=> update model selector 2.0

nvflare/fuel/hci/client/api.py, nvflare/fuel/hci/client/api_spec.py, nvflare/fuel/hci/client/file_transfer.py, nvflare/private/fed/client/training_cmds.py, nvflare/private/fed/server/job_runner.py, nvflare/private/fed/utils/app_deployer.py
This fix is for handling job signing in POC mode.  Basically, all jobs should not be signed and should not be verified in POC as there are no private keys/certificates.
=> Fix signing jobs in POC

nvflare/__init__.py
Currently, we need to import SimulatorRunner using
```
from nvflare.private.fed.app.simulator.simulator_runner import SimulatorRunner
```
With this change, it should be possible to import via
```
from nvflare import SimulatorRunner
```
=> Allow easier import of SimulatorRunner

research/quantifying-data-leakage/README.md, research/quantifying-data-leakage/index.html
Add readme to enable linking from published paper https://nvidia.github.io/NVFlare/research/quantifying-data-leakage
This directory will contain the tools necessary to recreate the chest X-ray experiments described in
"Do Gradient Inversion Attacks Make Federated Learning Unsafe?" [arXiv:2202.06924](https://arxiv.org/abs/2202.06924)
=> Add quantifying-data-leakage folder [skip ci]

docs/getting_started.rst, docs/real_world_fl/FLAdminAPI.rst, docs/real_world_fl/flare_api.rst, docs/real_world_fl/operation.rst, examples/hello-numpy-sag/hello_numpy_sag.ipynb
For hello scatter and gather, this is a Jupyter notebook using the new FLARE API to run the example. We can copy and modify the app name for other examples if this looks good and we want to include notebooks for those as well.
Also, add back the setting up and starting poc to the getting started page so the previous links work and the information is available.
=> Add notebook with FLARE API to example [skip ci]

nvflare/app_opt/xgboost/histogram_based/executor.py
string `squared_log` will lead to type error.
This issue is originally fixed in dev branch by https://github.com/NVIDIA/NVFlare/pull/1179. This PR is intended to patch 2.2 branch
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
Co-authored-by: Yuan-Ting Hsieh (謝沅廷) <yuantingh@nvidia.com>
Co-authored-by: Chester Chen <512707+chesterxgchen@users.noreply.github.com>
=> Imporve type error in FedXGBHistogramExecutor (#1179)

nvflare/private/fed/app/simulator/simulator_runner.py, nvflare/private/fed/server/server_commands.py, nvflare/private/fed/simulator/simulator_server.py
Fixes # .
Fixed the issue the simulator could not shutdown when the controller failed before client start.
For simulator wait for all the clients shutdown first, then shutdown the server. otherwise, the client heartbeat could not reach the server.
=> Wait for all the clients to shutdown first before shutdown server for simulator

nvflare/private/fed/app/client/worker_process.py, nvflare/private/fed/client/communicator.py, nvflare/private/fed/server/fed_server.py, nvflare/private/fed/server/server_engine.py
Fixes # .
Fixed the issue job status not updated properly with the MPM change.
Fixed the issue abort_job command hang with the MPM change.
Update the job status with proper complete, aborted and execution exception after the job complete.
Remove the improper cell.stop() to allow the abort_job command passed to the server job process.
=> Fixed the job status update and abort_job command.

examples/advanced/prostate/prostate_2D/custom/learners/supervised_monai_prostate_learner.py
Fixes #1342.
Fix the missing validation transform for prostate 2D example when cache_ratio=0, it should be w/o "_valid"
=> Fix validation transform bug

nvflare/dashboard/application/__init__.py, nvflare/dashboard/application/blob.py, nvflare/dashboard/cli.py, nvflare/lighter/impl/master_template.yml
This PR enables generating AWS cloud scripts for dashboard, server and client.
The command for all of them is similar to azure, just replace azure with aws on the --cloud option.
For example, to launch a server in AWS, type ./start.sh --cloud aws
=> Add support for AWS cloud launch scripts (dashboard/server/client)

nvflare/app_common/pt/__init__.py, nvflare/fuel/utils/class_utils.py
If a file requires an optional dependencies, then during our configuration process, the ModuleScanner should not go silent.
- It would be good to inform the users what package are missing if they want to use that file.
- Also remove unused methods
- filter out deprecation package so it won't print unnecessary messages.
=> Add warnings to ModuleScanner

nvflare/lighter/impl/master_template.yml
When launching multiple clients on Azure, the same resource name is used.  This PR randomizes the resource group name on client script so the issue can be avoided.
=> Randomize azure client resource group

nvflare/fuel/f3/cellnet/net_manager.py, nvflare/fuel/hci/client/api.py, nvflare/fuel/hci/client/cli.py, nvflare/fuel/hci/server/builtin.py
F3/Cellnet introduces many new admin commands for testing and analyzing the cell performance of the cell network. However these commands are not ready to be publicized. This PR makes such commands invisible or disabled:
- If a command could cause interruptive changes to the system (e.g. stop_net, stop_cell, etc), it is disabled
- Otherwise the command is made invisible to end user. The command is still accessible to the user.
Changes are in the following areas:
- Admin server is changed to send invisible commands to the client with visibility info. Internal commands are not sent.
- Admin client hides invisible commands from the user, but they are available to the user if the user knows the command name.
- The NetManager (which implements these commands) can be used in "for_test" mode. In …
=> Hide cell cmds

nvflare/private/fed/utils/decomposers/__init__.py
Build system depends on the dunder init python file to determine if one folder should be included.  This PR adds that file to nvflare/private/fed/utils/decomposers folder.
=> Add __init__.py to decomposers folder so build system will include it.

nvflare/lighter/impl/master_template.yml
This PR adds messages at the end of cloud launch scripts to show how to terminate EC2 instance in AWS / to delete resource group in Azure.
=> Add messages at the end of cloud launch scripts

nvflare/private/fed/app/simulator/simulator_runner.py, nvflare/private/fed/client/fed_client_base.py
Fixes # .
- To avoid the cell error at the END_RUN of simulator.
- fixed a minor display issue when client setup SP.
=> Avoid the simulator cell error after END_RUN.

nvflare/private/fed/app/deployer/simulator_deployer.py, nvflare/private/fed/client/fed_client_base.py
Fixes # .
- To enable the simulator to be able to use local/resources.json
- change the communication_timeout default to 10 sec
=> Enable Simulator to use resources.json.

nvflare/private/fed/app/simulator/simulator_runner.py, nvflare/private/fed/app/simulator/simulator_worker.py
Fixes # .
Fix the simulator hang due to the client executor missing import, or initialization error.
=> Fixed the simulator hang due to missing import.

nvflare/lighter/impl/master_template.yml
It's easier for users to be authenticated in Azure with az login --use-device-code as it does not rely on the browsers on that running machine.
=> Switch to --use-device-code for all az login cases [skip ci]

nvflare/lighter/impl/master_template.yml
Randomize the resource group names so users can run dashboard more than one time and the resource names will be be duplicate.
=> Randomize resource group to avoid duplicate resource group names [skip ci]

nvflare/lighter/impl/master_template.yml
In Azure cloud scripts, add `az group exists` to find if the resource group name exists.  If it exists, the resource group will not be created.  Instead, the same resource group is reused for following operations.
=> Check if resource group exists.

nvflare/apis/impl/controller.py, nvflare/apis/server_engine_spec.py, nvflare/fuel/f3/cellnet/cell.py, nvflare/private/aux_runner.py, nvflare/private/fed/client/client_engine_executor_spec.py, nvflare/private/fed/client/client_executor.py, nvflare/private/fed/client/client_run_manager.py, nvflare/private/fed/client/client_runner.py, nvflare/private/fed/client/communicator.py, nvflare/private/fed/cmi.py, nvflare/private/fed/server/server_engine.py, nvflare/private/fed/server/server_runner.py, nvflare/private/fed/simulator/simulator_server.py
This PR addresses the following issues:
- Clean up unnecessary error log messages during shutdown (NVBug 4005501. These messages are changed to debug level. This is implemented by setting requests generated during shutdown as "optional".
- Speed up job abort and termination process. Removed the artificial 10 secs delay to monitor the job process. This should at least partially solve NVBugs 4011353 and 4011356.
- Changed task retrieval log in communicator.py and client_runner.py to debug level, to reduce unnecessary log messages.
=> Fix shutdown log messages and speed up shutdown process

nvflare/lighter/impl/master_template.yml
Security groups can not be reused because the rules attached to them are specific for the VM.  Therefore, this PR randomizes the security group names to avoid reuse.
=> Randomize security group in AWS dashboard and client scripts

nvflare/private/aux_runner.py, nvflare/private/fed/server/server_command_agent.py, tests/unit_test/app_common/job_schedulers/job_scheduler_test.py
This PR fixes NVBug 4013497. The problem is caused by aux_runner's peer FL context handling logic. It used CellMessageInterface (CMI) for sending the message but didn't use it for handling incoming messages, and the peer FL context props were not handled properly. The CMI was designed to be a layer between cellnet and all upper layer modules. However it was only used for handling aux messages. This could cause other unwanted side effect.
This PR changes to not use CMI at all and handles peer props explicitly.
We can integrate CMI properly in a later version.
=> fixed peer context handling in aux runner

nvflare/private/fed/app/simulator/simulator_runner.py
Fixes # .
Fixed the simulator threads option issue when using multi-gpu
- When using multi_gpu simulator, set the threads to 1,
- when using single gpu in the --gpu option, use the default value 1, or use the user choose threads number.
=> Fixed the simulator threads option for multi_gpu case.

nvflare/lighter/impl/master_template.yml
Save Azure VM login info
Add Azure recommended option to stop warning.  Also save VM login credential into a local file so users can ssh into the VM in the future.
=> Change Azure VM create to remove warning

nvflare/apis/impl/bcast_manager.py, nvflare/apis/impl/controller.py, nvflare/fuel/f3/cellnet/cell.py, nvflare/fuel/f3/drivers/aio_grpc_driver.py, nvflare/private/fed/client/communicator.py, nvflare/private/fed/client/fed_client_base.py, nvflare/private/fed/server/server_runner.py, tests/unit_test/apis/impl/controller_test.py
The PR addresses the following issues:
- Clean up log messages of AioGrpcDriver. All connection related messages are changed to debug level;
- Fixed broadcast function in controller to quickly end a task when all expected responses are received. It used to still wait for "wait time after min responses received". It was useful in v2.0 since the system didn't know how many responses to expect. But since 2.1, we already changed to job scheduling and expected clients are known.
- Extended the default timeout for get_task to 30 seconds. This is to accommodate tasks that may have huge amount of data.
- Added message headers earlier in cellnet so they can be included in log messages when endpoint finding fails.
- Updated controller_test.py. The test case …
=> cleanup error msg; fix sag wait; fix get_task timeout

nvflare/private/fed/server/fed_server.py, nvflare/private/fed/server/job_runner.py, tests/integration_test/data/test_configs/ha/two_servers.yml, tests/integration_test/test_configs.yml
In the old codes, when we start more than 1 server, all of the servers will start JobRunner by default and it keeps reading and updating the job storage at the same time which might cause racing and other issues.
We change "run" of JobRunner to wait for server state to become HOT
- JobRunner will not proceed until server turns to HOT state
=> Fix job runner multiple start issue

examples/.gitignore, examples/hello-world/hello-numpy-cross-val/jobs/hello-numpy-cross-val/app/config/config_fed_server.json, examples/hello-world/hello-numpy-sag/jobs/hello-numpy-sag/app/config/config_fed_server.json, examples/hello-world/hello-pt/jobs/hello-pt/app/config/config_fed_server.json, examples/hello-world/hello-tf2/jobs/hello-tf2/app/config/config_fed_server.json, nvflare/app_common/np/np_trainer.py
If weights not provided, the aggregator is going to log warnings.
Provide weights for up to 2 clients for hello-examples.
=> Get rid of hello-examples warnings

nvflare/private/fed/server/fed_server.py, nvflare/private/fed/utils/app_authz.py
This PR addresses the following issues:
- NVBug 4019370. The fix is to silent log messages to DEBUG level for the dead_job notification messages. These messages are optional in nature.
- NVBug 3831404. The API status logic is confused between user "not authorized" and "BYOC not authorized". Changed the text to "BYOC not permitted" to avoid the conflict.
=> fix api status and dead job message

nvflare/apis/impl/any_relay_manager.py, nvflare/apis/impl/controller.py, nvflare/apis/impl/seq_relay_manager.py, runtest.sh, tests/unit_test/apis/impl/controller_test.py, tests/unit_test/fuel/utils/component_builder_test.py
The problem is related to this part of codes: https://github.com/NVIDIA/NVFlare/blob/dev/nvflare/apis/impl/seq_relay_manager.py#L112-L120 
The old controller code has a rare chance that a `client_task` has already been put inside the `task.last_client_task_map[client.name]` BUT its `task_sent_time` is None, which will cause this following line to failed:
`if task_result_timeout and time.time() - last_task.task_sent_time > task_result_timeout:`
=> Fix controller timing issue

nvflare/fuel/flare_api/flare_api.py, nvflare/fuel/sec/authz.py, nvflare/private/fed/server/job_cmds.py, tests/unit_test/private/fed/server/job_cmds_test.py
This PR improves list_jobs behavior based on user feedback:
- By default, jobs are listed in the order of submission times. A new "-r" option is added to list the jobs in the reverse order of submission times.
- Updated flare_api's list_jobs() method with a "reverse=False" arg to be consistent with the command behavior.
This PR also improves user/submitter info format when printing authz info. The info is usually printed as "name:org:role". If the user is not available, current format becomes "::", which is hard to read, as pointed out in NVBug 4011685.
This PR improves it as follows:
- If the user/submitter is not available, prints "None"
- If the user/submitter is available but some attributes (name, org, role) are not available, use "None" for the missing attribute.
=> fix job listing

nvflare/apis/controller_spec.py, nvflare/apis/impl/controller.py, nvflare/fuel/f3/cellnet/cell.py, nvflare/fuel/f3/mpm.py
This PR addresses the following issues:
- The exit status of a task was incorrectly set to TIMEOUT when the task is still waiting (e.g. bcast forever) after all expected responses are received. Corrected to only set to TIMEOUT if the task is waiting for a client that is already dead.
This change should fix NVBugs 4007603 and 4007785.
- Added topic info to log message when a request is timed out. This will help find the exact type of the timed-out request.
- Reduced the grace period and cleanup period of MPM to speed up the shutdown process.
=> fix wf task exit status handling

nvflare/fuel/f3/cellnet/cell.py, nvflare/private/fed/server/admin.py, nvflare/private/fed/server/job_cmds.py, nvflare/private/fed/server/job_runner.py, nvflare/private/fed/server/message_send.py
When aborting a job, the server sends abort commands to all clients and wait for their responses. However since some of the job cells may already be gone, the server will timeout and creates an error log message.
This PR makes the abort request "optional", and create the timeout message in DEBUG level.
This PR fixes NVBug 4027037.
This PR also added some minor improvements:
- Updated the help info of the "list_jobs" command with the "-r" option
- Added/fixed some docstrings.
- Shorten the wait time of the abort command to 2.0 secs from 10 secs
=> silent abort message logging

nvflare/fuel/hci/client/fl_admin_api.py
The old FLAdminAPI didn't support the "-d" option of the "list_jobs" command. This PR fixes it by using the returned "meta" info.
This PR fixes the bug reported in NVBug 4005332.
=> fix list_jobs detail handling

nvflare/app_common/executors/multi_process_executor.py, nvflare/fuel/f3/cellnet/cell.py, nvflare/private/fed/app/simulator/simulator_worker.py, nvflare/private/fed/client/fed_client_base.py, nvflare/private/fed/server/fed_server.py
Fixes # .
Change to not create the internal listener for the job cells. No need to create them.
=> not creating internal listener for the job cell.

examples/advanced/cifar10/cifar10-sim/jobs/cifar10_fedopt/cifar10_fedopt/config/config_fed_server.json, nvflare/fuel/utils/component_builder.py, tests/unit_test/fuel/utils/component_builder_test.py
For `PTFedOptModelShareableGenerator` we do want to treat those args as dictionary but NOT nested components.
This PR adds a "config_type" to distinguish between a dictionary should be built as component or just pass in as a regular dictionary. 
- [] Non-breaking change (fix or new feature that would not break existing functionality).
=> Add config_type to distinguish

nvflare/apis/impl/controller.py, nvflare/private/fed/server/server_commands.py, nvflare/private/fed/server/server_runner.py
Fixes # .
Fixed the simulator delay with large number of clients run.
A shared memory object issue in the controller task return caused the concurrent clients get_task request got the same task to run. This caused the simulator clients ran for multiple times.
=> Fixed the shared object issue in the controller task return.

docs/user_guide/cloud_deployment.rst
This PR describes that the source IP of ssh port, after deployment, can be updated in the AWS/Azure web if users try to login the VM from different machines.
=> Add information about ssh source IP (skip ci)

integration/monai/setup.py
Fixes # .
1. update python version support
2. update monai from 1.0.1 to 1.1.0 
3. update monai_flare build version from 0.21 to 0.22
=> update monai integration versions [skip_ci]

nvflare/private/fed/server/fed_server.py, nvflare/private/fed/server/job_runner.py, nvflare/private/fed/server/server_runner.py
After a job was aborted, the server status was "Stopped."  However, after this server was restarted, it picked that aborted job and continue running that job.  This PR fixed this issue.
=> Fix incorrect server status after job aborted and server restarted

nvflare/private/fed/server/job_cmds.py, nvflare/private/fed/server/job_runner.py
When we abort a job, we should just send abort job messages to the clients that are connected.
The clients that are connected at job launching time might be already dead/dropped.
=> Fix abort job with only connected clients

nvflare/private/fed/app/simulator/simulator_runner.py, nvflare/private/fed/client/fed_client_base.py
Fixes # .
Ensure to end the simulator after client exception, for example, too many files open error.
=> Ensure to end the simulator run after client exception.

nvflare/app_common/response_processors/global_weights_initializer.py
Fixes # .
Validate client name type in GlobalWeightsInitializer to be single string when weight method is "client".
=> Validate client name type in GlobalWeightsInitializer

nvflare/app_common/workflows/scatter_and_gather.py
Reverts NVIDIA/NVFlare#1595
I will address the clients sent back old/dead task results from previous SSID on the client side.
Not on the app layer.
=> Revert "Ignore unknown task result in SAG"

nvflare/apis/impl/controller.py, nvflare/fuel/f3/cellnet/net_manager.py, nvflare/fuel/f3/stats_pool.py, nvflare/fuel/flare_api/flare_api.py, nvflare/fuel/utils/stats_utils.py
The PR addresses the following issues:
- In controller.py, there is a bug in setting the dead client report time. The report time should only record the first time the report is received, not resetting it repeatedly; otherwise the dead client logic will never be triggered.
- Also changed to use config service for dead client/job processing parameters.
- Added stats pool to_dict logic to enable pool stats to be written to file.
- Modified flare_api to use a generic way to detect job completion.
=> fix controller dead client handling; added stats pool to_dict

nvflare/private/fed/client/client_runner.py
Change default initial task fetch interval at client side from 0.1 to 0.5.
0.1 is too aggressive.
Note that once we get the first task from server, we will just following server's suggestion on task fetch interval.
server side default is 2 seconds. `self.task_request_interval = 2  # default to 2 secs` in `server_json_config.py`
=> Change default initial task fetch interval at client side from 0.1 to 0.5

nvflare/private/fed/server/job_runner.py
Fixes # .
Fixed a save_workspace error, caused by a wrong indent.
=> Fixed a save_workspace error.

nvflare/private/fed/app/client/client_train.py, nvflare/private/fed/client/client_app_runner.py, nvflare/private/fed/client/communicator.py, nvflare/private/fed/client/fed_client_base.py, nvflare/private/fed/server/fed_server.py
Fixes # .
delay the overseer agent start for client job worker process.
=> delay the overseer agent start for client job worker process.

nvflare/private/fed/app/client/client_train.py
Fixes # .
remove the _ensure_daemon_process_shutdown in client_train.py which caused restart fail.
=> remove the _ensure_daemon_process_shutdown which caused restart fail.

nvflare/apis/fl_constant.py, nvflare/app_common/job_schedulers/job_scheduler.py, nvflare/private/fed/server/fed_server.py, nvflare/private/fed/server/job_runner.py, nvflare/private/fed/server/server_commands.py, nvflare/private/fed/server/server_engine.py, nvflare/private/fed/server/server_runner.py, tests/unit_test/private/fed/server/fed_server_test.py
If we have 2 servers, and keep promoting each other.
p1 -> p2 -> p1 (job runner dead)
We will shutdown the job runner then server is not functioning.
After HOT turn to COLD.
We should NOT shutdown job runner, but instead have it standby.
=> Do not shutdown job runner when server turn to cold state

examples/README.md
=> Fix readme typos [skip ci]

tests/integration_test/src/utils.py
Need to install requirements.txt before run prepare_data.sh
=> Install all requirements first in auto test config

nvflare/fuel/f3/qat/admin.py, nvflare/fuel/flare_api/flare_api.py, nvflare/fuel/hci/client/api.py, nvflare/fuel/hci/client/api_spec.py, nvflare/fuel/hci/client/cli.py, nvflare/fuel/hci/client/fl_admin_api.py, nvflare/fuel/hci/client/overseer_service_finder.py, nvflare/fuel/hci/client/static_service_finder.py, nvflare/fuel/utils/fsm.py, tests/integration_test/src/nvf_test_driver.py
- Remove login/login_with_poc function in `FLAdminAPI` as it conflicts with auto_login
- Our `AdminAPI` required `ServiceFinder` and it can't be None
- Make `auto_login_timeout` and `auto_login_interval` as arguments instead of hard-code
- Fix code style
=> Clean up AdminAPI

nvflare/fuel/f3/qat/time_comm.py, nvflare/fuel/f3/stats_pool.py
Fixes # .
CSV's writerow method is not thread safe. When it is called from different threads at the same time, its behavior is unpredictable. This PR put the call into a lock clause to ensure thread safety. Also added sanity check of inputs.
To make it easy to read stats record file (csv format), added CsvRecordReader.
Added the time_comm tool to compute total communication time of a job. This tool is implemented with the use of CsvRecordReader.
=> Make CsvRecordHandler thread safe

nvflare/dashboard/cli.py, nvflare/lighter/impl/master_template.yml
Based on current running nvflare version, dashboard will run either nvflare or nvflare-dev container image.
When the version is M.N.m, nvflare will be used.
When the version is M.N.mrcX, M.N.m.devX, nvflare-dev will be used.
=> Add dev/prod container images in local and cloud

nvflare/dashboard/application/blob.py, nvflare/lighter/impl/master_template.yml
This PR adds supports to launch AWS or Azure with container.  The NVFlare server or client is running inside that container.  These four combinations are supported: Server+AWS, Server+Azure, Client+AWS and Client+Azure.
=> Add support to run container in cloud scripts

docs/getting_started.rst
Fixes job path in docs on getting started page: https://github.com/NVIDIA/NVFlare/discussions/1730.
=> Update job path in getting started guide docs [skip ci]

docs/getting_started.rst
Fixes job path in docs on getting started page: https://github.com/NVIDIA/NVFlare/discussions/1730.
=> Update job path in getting started guide docs for 2.3 [skip ci]

nvflare/lighter/impl/master_template.yml
Add `-d` option to docker.sh to enable docker run in detached mode.  This will automatically run nvflare server/client inside the container.
When run docker.sh without `-d`, the original behavior applies.
Also add the feature to allow users to override MY_DATA_DIR and GPU2USE.  The default values will be used if the env var is not set.
If users run docker.sh with `MY_DATA_DIR=/var/tmp/data docker.sh` the /var/tmp/data in host will be mounted as /data in the docker.
If users run docker.sh without setting `MY_DATA_DIR` the default `/home/flclient/data` in host will be mounted as /data in the docker.
=> Add detached mode in docker.sh

nvflare/dashboard/application/blob.py
This PR enables dashboard to generate docker.sh in the downloaded startup kits.
The docker.sh file will be identical to that generated by provision CLI.
The docker image used in the docker.sh is from the text in `Docker Download Link` when project admin configures the project.  For example, if project admin sets it to `docker pull pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime` the docker image inside docker.sh will be `pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime`.
=> Add codes to generate docker.sh

.github/workflows/premerge.yml
Remove GITHUB premerge workflow branch restriction
=> remove github premerge workflow branch restriction [skip ci]

nvflare/app_opt/pt/file_model_persistor.py
Fix app_opt PTFileModelPersistor typo
=> Fix app_opt PTFileModelPersistor typo

.github/workflows/codeql.yml, nvflare/lighter/utils.py, tests/unit_test/lighter/utils_test.py
This PR updates the unit tests for server resigning on a signed job folder.  This will help check if the resigning works.
=> Add tests for resigning on signed folders

nvflare/security/logging.py, tests/unit_test/fuel/utils/component_builder_test.py
- Include exception type
- Fix unit test for https://github.com/NVIDIA/NVFlare/pull/1742 by @taleinat 
By Tal:
The `str()` of an exception normally doesn't include its type. Including the type of the exception is very useful.
In the rare cases of exceptions with no details in their string representation, this is especially significant.
This is similar to the format used in Python exception tracebacks:
```python
>>> int("a")
Traceback (most recent call last):
File "<pyshell#>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'a'
>>> try:
int("a")
except ValueError as exc:
print(str(exc))
invalid literal for int() with base 10: 'a'
```
=> [main] include exception type

tests/unit_test/lighter/utils_test.py
During CI tests with pytest xdist, two test cases in lighter/util may fail due to damaged test data caused by race conditions.  This PR puts those two cases in a group so they will run one by one.
=> Fix an issue in lighter utils CI tests

runtest.sh
Some tests can NOT be run in parallel, so we add "@pytest.mark.xdist_group".
However that only works if we run pytest using flag `--dist loadgroup`
- Add `--dist loadgroup` for running pytest.
(Follows: https://pytest-xdist.readthedocs.io/en/latest/distribution.html#running-tests-across-multiple-cpus)
=> Use --dist loadgroup for pytest

setup.cfg
Fixes CVE-2023-30861
CVE-2023-30861 instructs to upgrade flask to 2.2.5.  This PR sets the flask version to that.
=> Upgrade flask to 2.2.5 to address CVE-2023-30861.

docs/programming_guide/fl_component.rst
Documentation lines are not in sync with additions to the underlying document being referenced. Updated to include fire_event and fire_fed_event
https://github.com/NVIDIA/NVFlare/blob/main/nvflare/apis/fl_component.py#L28-L90
Current view ([link](https://nvflare.readthedocs.io/en/main/programming_guide/fl_component.html))
My changes include the relevant lines from the fl_component.py src
=> Update fl_component.rst [skip ci]

docs/programming_guide/data_exchange_object.rst
In the docs, the line numbers for this code preview are incorrect and yield this in the docs:
(source: https://nvflare.readthedocs.io/en/main/programming_guide/data_exchange_object.html)
Fixes # .
This shifts the line numbers so that they correctly render the DXO class.
=> Update data_exchange_object.rst [skip ci]

examples/advanced/random_forest/random_forest.ipynb
Missing comma broke syntax & caused compilation error.
Fixes # .
=> Fix bug in RFXGBoost notebook that prevented correct rendering [skip ci]

examples/advanced/sklearn-svm/README.md, examples/advanced/sklearn-svm/prepare_job_config.sh, examples/advanced/sklearn-svm/requirements.txt, examples/advanced/sklearn-svm/run_experiment_simulator.sh, nvflare/fuel/utils/config_factory.py, nvflare/private/fed/app/default_app_validator.py
Fixes integration tests automatic stage.
- CUML change their installation method, I remove the entry from requirements.txt and add text to refer users to correct installation
- nvflare/private/fed/app/default_app_validator.py WAS checking for "config_fed_server.json" and "config_fed_client.json", follow changes in PR #1824 to check for general "config_fed_server" and "config_fed_client", NOTE that there are several places throughout our code base use `JobConstants.SERVER_JOB_CONFIG` and `JobConstants.CLIENT_JOB_CONFIG` we might need to fix them
=> Fix auto integration tests

nvflare/app_common/workflows/cyclic_ctl.py
This PR adds a call to garbage collection at the end of each round so that the server can reclaim unused memory more often.
=> Add garbage collection at the end of each round in cyclic controller

tests/integration_test/data/test_configs/ha/kill_server_after_training_complete.yml, tests/integration_test/data/test_configs/ha/kill_server_during_training_after_first_round.yml, tests/integration_test/data/test_configs/ha/kill_server_during_training_before_first_round.yml, tests/integration_test/data/test_configs/ha/kill_server_during_training_sending_model.yml
When server re-starts back, after its restoring the previous state.
Sometimes the "get_stats" command does NOT reflect the server state right away.
So we wait 1 seconds for the state to be restored in the server.
=> Fix integration test configs timing issues

nvflare/fuel/f3/cellnet/new_cell.py
This PR improves the send_request timeout handling.  Originally, timeout is used to check if the last byte of reply arrives in time.  This PR change the timeout for sending progress, remote processing and receiving progress.
=> Improve NewCell send request timeout handling

nvflare/fuel/hci/client/config.py
Fixes # .
Fixed a bug the admin tool requires the resources path error.
Made the resources folder in the admin tool optional.
=> Fixed the admin tool requires the resources path.

nvflare/private/fed/app/simulator/simulator_worker.py
… due to https://github.com/NVIDIA/NVFlare/pull/1881 change.
Fixes # .
Fixed the simulator error when checking the end_run due to https://github.com/NVIDIA/NVFlare/pull/1881 change.
=> Changed the simulator to use client_runner.run_abort_signal.triggered

examples/hello-world/ml-to-fl/jobs/client_api1/app/custom/cifar10.py, examples/hello-world/ml-to-fl/jobs/client_api2/app/custom/cifar10.py, examples/hello-world/ml-to-fl/jobs/decorator/app/custom/cifar10.py
Fixes issues running on MacOS.
Starting Python3.8+, Python is using "spawn" for MacOS multiprocessing: https://docs.python.org/3/whatsnew/3.8.html#multiprocessing
And for "spawn" method, ONE has to safe guard the main method using `if __name__ == '__main__':`: https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods
Otherwise, when DataLoader num_worker >0, things will not work: https://github.com/pytorch/pytorch/issues/46648
=> Wrap training scripts inside main method

nvflare/private/fed/client/client_app_runner.py, nvflare/private/fed/client/client_json_config.py, nvflare/private/fed/client/client_runner.py, nvflare/private/fed/server/server_json_config.py, nvflare/private/fed/server/server_runner.py
Fixes # .
- Fixed the recursive FLComponent creation missing the event handling issue.
- Fixed the client job process missing the proper FLcomponent handlers issue.
- Server Runner set the workflow ID in the FLContext before the initialize_run(fl_ctx).
=> Fixed the recursive FLComponents creation.

nvflare/private/fed/client/client_app_runner.py, nvflare/private/fed/client/client_json_config.py, nvflare/private/fed/client/client_runner.py, nvflare/private/fed/server/server_json_config.py, nvflare/private/fed/server/server_runner.py
Fixes # .
- Fixed the recursive FLComponent creation missing the event handling issue.
- Fixed the client job process missing the proper FLcomponent handlers issue.
- Server Runner set the workflow ID in the FLContext before the initialize_run(fl_ctx).
=> Cherry-pick:  Fixed the recursive FLComponents creation

nvflare/dashboard/cli.py, nvflare/lighter/impl/master_template.yml
Fix the quotes that do not work in bash/zsh.
Fix an issue that does not include script common header in cloud launch scripts.
=> Rewrite double quote to heredocs to avoid bash/zsh issues

nvflare/fuel/f3/cellnet/core_cell.py, nvflare/fuel/f3/cellnet/defs.py, nvflare/fuel/f3/comm_config.py, nvflare/fuel/f3/drivers/aio_grpc_driver.py, nvflare/fuel/f3/drivers/aio_http_driver.py, nvflare/fuel/f3/drivers/aio_tcp_driver.py, nvflare/fuel/f3/drivers/driver_params.py, nvflare/fuel/f3/drivers/tcp_driver.py, nvflare/fuel/f3/sfm/conn_manager.py, nvflare/fuel/f3/sfm/heartbeat_monitor.py, nvflare/fuel/f3/sfm/sfm_conn.py, tests/unit_test/data/custom_drivers/com/example/warp_driver.py
Fixes FLARE-952 and FLARE-1438
1. Added heartbeat support to SFM. The heartbeat interval is controlled by comm parameter heartbeat_interval.
2. Disabled WAIT_TIL in Cellnet to get around the clock drift issue.
=> SFM Heartbeat Support

nvflare/fuel/f3/streaming/stream_utils.py
Fixes FLARE_1505
Registered a cleanup CB for MPM to shutdown thread pool used by streaming.
=> Kill stream threads on shutdown

examples/advanced/vertical_xgboost/README.md, examples/advanced/vertical_xgboost/jobs/vertical_xgb/app/config/config_fed_client.json, nvflare/app_opt/xgboost/histogram_based/executor.py
Updated for recently added vertical xgboost gpu support.
=> Update vertical xgb examples for gpu support

tests/unit_test/fuel/f3/communicator_test.py
This test had racing issue.
Multiple threads could try to modify a_ready/b_ready.
Changed to disable it for now.
=> Fix communicator_test.py

nvflare/apis/utils/fl_context_utils.py, nvflare/private/fed/server/server_command_agent.py
This PR adds a utility function that generate the serialized peer fl context.  The original way took about 4 seconds if the model size is large.  This new utility function takes almost no time.
Currently, this PR only changes the part handling aux_communication to the new utility function.  Other areas will be changed once this utility function is working properly and is tested thoroughly on aux_communication.
=> Improve the way to generate serialized peer fl context

nvflare/private/fed/client/command_agent.py, nvflare/private/fed/server/server_commands.py
This PR replaces the statements generating peer fl context with the new utility function in the remaining places that require sending the peer fl context.
On large models, the utility function takes about 50ms to finish, compared to the previous statements which takes about 3~4 seconds.
=> Complete the TODO places of generating peer fl context

nvflare/private/fed/client/communicator.py
This PR updates a few more places that create peer fl context before sending messages out.  The updates are to replace statements creating peer fl context with a utility function that performs the same functionality, but more efficiently.
=> Update a few more places that require generating peer fl context

nvflare/lighter/impl/master_template.yml
Removing leading space on closing EOF for azure scripts
=> Fix cloud scripts heredoc spacing

nvflare/apis/fl_constant.py, nvflare/private/fed/client/client_json_config.py, nvflare/private/fed/server/server_json_config.py
Fixes # .
This PR fixes a bug that could cause the whole system to become unworkable when a job's config files contain errors. At the end of job config processing, the config service is initialized with the section file to be the job's server/client config. However the config path is set to workspace! Since a workspace could contain many jobs, if any job happens to have a bad config file in it, and the config service happens to use it when searching the section file, the current job will crash.
The fix simply removes this section file since it is not used in our system at all.
=> fix job config section

nvflare/fuel/f3/comm_config.py, nvflare/fuel/f3/drivers/aio_grpc_driver.py, nvflare/fuel/f3/drivers/grpc/qq.py, nvflare/fuel/f3/drivers/grpc/utils.py, nvflare/fuel/f3/drivers/grpc_driver.py, nvflare/fuel/f3/drivers/net_utils.py, nvflare/fuel/f3/qat/admin.py, nvflare/fuel/f3/qat/run_cell.py, nvflare/fuel/f3/qat/run_server.py, nvflare/fuel/f3/sfm/conn_manager.py, nvflare/fuel/utils/config_service.py, nvflare/private/fed/server/server_runner.py, tests/unit_test/fuel/f3/communicator_test.py, tests/unit_test/fuel/f3/drivers/custom_driver_test.py, tests/unit_test/fuel/f3/drivers/driver_manager_test.py, tests/unit_test/lighter/utils_test.py
Fixes # .
This PR adds non-asyncio version of GRPC driver.  The AIO version of GRPC library could crash when the underlying network is unstable (like SIGSEGV) on the client side. This PR adds a GRPC driver using non-aio version of the GRPC library.
- The user can control which version of GRPC driver to use by either configuring comm_config.json or set the NVFLARE_USE_AIO_GRPC env variable.
- AIO and non-AIO version GRPC drivers can work together. For example, the server could be using AIO version whereas clients can use non-AIO version.
- Changed MAX_WAIT for reconnect to 10 seconds from 60 secs to make reconnect more quickly.
=> Restore non-aio grpc driver

nvflare/fuel/f3/drivers/aio_context.py, nvflare/fuel/f3/drivers/aio_grpc_driver.py, nvflare/fuel/f3/drivers/grpc_driver.py
Fixes # .
- Set exception handler for AIO event loop. This is necessary to gracefully stop AIO tasks that run into exceptions.
- Ensure GRPC channel is not closed multiple times to avoid potential exception
=> fix aio exception handling

nvflare/tool/job/config/config_indexer.py, nvflare/tool/job/config/configer.py, tests/unit_test/data/jobs/launch_everytime/app/config/config_fed_client.conf, tests/unit_test/data/jobs/launch_everytime/app/config/config_fed_server.conf, tests/unit_test/data/jobs/launch_everytime/meta.conf, tests/unit_test/data/jobs/launch_once/app/config/config_fed_client.conf, tests/unit_test/data/jobs/launch_once/app/config/config_fed_server.conf, tests/unit_test/data/jobs/launch_once/meta.conf, tests/unit_test/tool/job/config/configer_test.py
I encounter a situation where in config:
```
launch_once = true
```
And in CLI I use `-f config_fed_client.conf app_script=train_diff.py launch_once=false`
In the old logic, we will do this type conversion: bool("false") which equal to True.
Instead, we should be utilizing the same parsing rule as pyhocon and treat this value as boolean "False".
- Use pyhocon to do type conversion
- Remove unused argument
=> Fix job cli boolean replacement issue

nvflare/fuel/f3/cellnet/core_cell.py
Change from log error to warning when receiving reply after timeout
=> Fix for QA workflow scripts

nvflare/fuel/f3/cellnet/core_cell.py, nvflare/fuel/f3/comm_config.py, nvflare/fuel/f3/drivers/aio_context.py, nvflare/fuel/f3/drivers/aio_grpc_driver.py, nvflare/fuel/f3/drivers/grpc_driver.py, nvflare/fuel/f3/drivers/net_utils.py, nvflare/fuel/f3/sfm/conn_manager.py, nvflare/fuel/f3/streaming/byte_receiver.py, nvflare/fuel/f3/streaming/byte_streamer.py, nvflare/private/fed/client/client_json_config.py, nvflare/private/fed/server/server_json_config.py, nvflare/private/fed/server/server_runner.py
Fixes # .
This PR applies 2.3 enhancements to 2.4:
- Improve connection handling of GRPC drivers
- Set event loop's exception handler
- Reduce max wait for connection reconnect
- Enhance credential info
- Remove application conf section when initializing ConfigService. 
- Fixed byte_streamer to not create CommConfigurator during class creation, since the ConfigServer.initialize may not have been called!
=> Improve grpc 24

nvflare/fuel/f3/cellnet/cell.py, nvflare/fuel/f3/cellnet/core_cell.py
1. There will be a racing condition if the "send_blob" return right away, so we need to setup the waiter first in cell.py
2. The "_msg_size_mbs" needs to be called before "self._send_direct_message" because "self._send_direct_message" will transform the bytes back to objects, then it will lead to "_msg_size_mbs" failed.
- Move setup waiter in the front of "send_blob" in cell.py
- Move _msg_size_mbs call in the front of "_send_direct_message" in core_cell.py
=> Fix cell and core cell

nvflare/tool/job/config/config_indexer.py, tests/unit_test/tool/job/config/config_indexer_test.py
If the json or conf file contains a value of null, for example:
```
{
"a": 100,
"b": null
}
```
We should be able to parse / substitute it easily.
Bugs found and suggested fix by @holgerroth 
- Add value is None to is_primitive method
=> Add None to is_primitive to support null in conf/json files

nvflare/tool/job/config/configer.py
Fixes # .
-f x=1 
x and 1 both are treated as string in the CLI Job command. This PR will convert "1" back to 1 if possible
=> CLI Job upgrade, convert string to number if possible

examples/hello-world/ml-to-fl/README.md, examples/hello-world/ml-to-fl/np/README.md, examples/hello-world/ml-to-fl/np/code/train_diff.py, examples/hello-world/ml-to-fl/np/code/train_full.py, examples/hello-world/ml-to-fl/np/code/train_loop.py, job_templates/sag_np/config_fed_client.conf, job_templates/sag_np/config_fed_server.conf, job_templates/sag_np/info.conf, job_templates/sag_np/info.md, job_templates/sag_np/meta.conf
Adds different NumPy based mock training example to showcase different configurations of Client API.
Also showcase how to launch_once and use a training loop in custom/user training script.
- Add README of different configurations options of NVFlare Client API
- Add "sag_np" job template
=> Add NumPy + Client API example

nvflare/apis/event_type.py, nvflare/apis/fl_constant.py, nvflare/apis/fl_context.py, nvflare/apis/fl_exception.py, nvflare/fuel/utils/config_service.py, nvflare/private/fed/client/client_json_config.py, nvflare/private/fed/client/client_runner.py, nvflare/private/fed/server/server_json_config.py, nvflare/private/fed/server/server_runner.py, nvflare/private/fed/server/training_cmds.py, nvflare/private/fed/tbi.py, nvflare/widgets/fed_event.py
Fixes # .
Currently when the server_runner reaches the end of the work (all workflows are done), it returns and causes the job processing to end immediately. This will cause all communications to stop. The client_runner has the same behavior.
This could be problematic if some components still have unfinished work (e.g. the ServerFedEventRunner may still have unprocessed incoming log records).
This PR tries to fix this potential hole:
- Before ending the process, the runner fires a new event EventType.CHECK_END_RUN_READINESS to "ask" all components whether they are ready to end the run. 
- A component listens to this event. In its event handler, if the component has unfinished work, it sets the FLContextKey.NOT_READY_TO_END_RUN property into the fl_context.
- The runner looks for the …
=> Support graceful end_run processing

nvflare/fuel/f3/cellnet/connector_manager.py
Fixes # .
Currently ad-hoc connections are only allowed between gen2 cells. With this restriction, the two endpoints of a CellPipe won't be able to communicate directly.
This PR removes this restriction.
=> Remove gen2 restriction from ad-hoc policy

nvflare/apis/fl_constant.py, nvflare/private/fed/client/client_engine_executor_spec.py, nvflare/private/fed/client/client_run_manager.py, nvflare/private/fed/client/client_runner.py, nvflare/private/fed/client/communicator.py, nvflare/private/fed/client/fed_client.py, nvflare/private/fed/client/fed_client_base.py, nvflare/private/fed/tbi.py
Fixes # .
The timeout values for getTask and submitUpdate (task result) should/could be related to the task sizes of the job.
However, currently these timeout values can only be configured in "local/resources.json".  Since this file is for site admin to maintain and not accessible to end users, users won't be able to configure these values for their jobs. 
This PR makes it possible for the user to set the timeout values in config_fed_client.json of the job. If the values are not configured in config_fed_client.json, values from local/resources.json will be used.
=> support getTask and submitResult timeout in job config

nvflare/private/fed/app/simulator/simulator_runner.py, nvflare/private/fed/client/client_app_runner.py
Fixes # 
Fixed the SystemVarName.SECURE_MODE wrong value when running Simulator.
Set up the proper kv_list value in the server and client FedJsonConfigurator.
=> Fixed the SystemVarName.SECURE_MODE error in simulator

nvflare/apis/impl/job_def_manager.py, nvflare/apis/job_def_manager_spec.py, nvflare/apis/storage.py, nvflare/app_common/storages/filesystem_storage.py, nvflare/private/fed/server/job_runner.py, tests/unit_test/app_common/storages/storage_test.py
Fixes # .
This PR address the following issues:
- Currently the meta file stored in the job store could cause memory exhaustion since it uses ast.literal_eval to convert the content in meta file. This PR fixed this issue by using simple JSON files.
- The job scheduler retrieves job candidates for scheduling every second. This requires the scanning of the whole job store and reading each job's meta file. This is a lot of wasted processing since job's status never goes back to SUBMITTED. Added an enhancement such that if a job's status is not SUBMITTED, it will be skipped in future retrievals. 
- Improved job_runner to avoid wasted scheduling attempts when no clients are online. Not only the scheduling attempts are wasted, but it could also delay the scheduling of pending submitted jobs …
=> Fix meta file processing in storage and improve schedule job retrieval

nvflare/app_common/abstract/params_converter.py, nvflare/app_opt/pt/params_converter.py, nvflare/app_opt/tf/params_converter.py
Sometimes for the second conversion (convert from 3rd party to NVFlare) we need contextual information from the first conversion (convert from NVFlare to 3rd party).
One example for that is the HE conversion, where we want to convert the params and reshape it to linear and then reshape it back afterwards.
We can set/read an attribute in the fl_ctx to represent the model_dict's original Tensor's shape, so we can enable HE using ParamsConverter mechanism.
- Add fl_ctx in convert method of ParamsConverter
=> Add fl_ctx in convert method of ParamsConverter

nvflare/fuel/f3/drivers/aio_grpc_driver.py, nvflare/fuel/f3/drivers/grpc_driver.py
Fixes # .
This PR attempts to fix the "excepthook error" that sometimes occurs at the end of the FL server. According to Ming Chen's investigation, this error could be caused by the improper shutdown of the AIO gRPC server.
This PR tries to fix this problem with following changes:
- Once starting to stop the grpc server with a grace time, we'll wait for this grace time explicitly such that the "stop" process will have enough time.
- Set grpc_server object to None to potentially trigger garbage collection on this object, which could potentially force the stop process.
=> Fix excepthook error

nvflare/cli.py
When nvflare.cli parses command line options, it asks subcommands to handle those options.  When subcommands encounter unknown options, they return error and the list of unknown options.  Then nvflare.cli prints the helper messages explaining the errors.  This PR add a separator when forming the message.
=> Fix the missing separators in nvflare cli

nvflare/fuel/utils/pipe/cell_pipe.py, nvflare/fuel/utils/pipe/pipe.py, nvflare/fuel/utils/pipe/pipe_handler.py
Fixes NVBug https://nvbugswb.nvidia.com/NvBugs5/SWBug.aspx?bugid=4431630
Currently when CellPipe heartbeat messages fail, many error messages are logged. This is unnecessary since HB messages are repeated, especially at the beginning of the job when the two peers of the pipe are not started up at the same time.
=> Reduce CellPipe heartbeat error log

nvflare/lighter/impl/master_template.yml
When cloud scripts set the SSH inbound rule, it needs to determine the public IP address of the machine at which the scripts are running.  The scripts do a DNS name resolution by communicating with opendns.com.  However, some network configuration limits DNS name resolution to a specific server and does not allow resolving with other DNS servers.
This PR enhances the logic to set SSH inbound rule.  When the command `dig` returns an non-zero exit code or the public IP address could not be resolved, a warning message is displayed to remind users to set that inbound rule by themselves.
=> Enhance the cloud script on the SSH inbound rule

nvflare/fuel/f3/cellnet/core_cell.py, nvflare/fuel/f3/cellnet/defs.py
Fixes # .
The P2P message encryption is broken for CCWF.  This was caused by reuse of PAYLOAD_LEN msg header.
This PR fixes this by introducing a new message header CLEAR_PAYLOAD_LEN.
=> Fix p2p encrypt/decrypt

nvflare/private/defs.py, nvflare/private/fed/client/client_app_runner.py, nvflare/private/fed/client/client_engine.py, nvflare/private/fed/client/client_engine_internal_spec.py, nvflare/private/fed/client/client_executor.py, nvflare/private/fed/client/client_req_processors.py, nvflare/private/fed/client/training_cmds.py
Fixes # 
Enhance the client job status report.
Currently the client job status is directly checking with the client job process. However, when the client child cell has not been created when job starting, or the client child cell stopped after the job run, the parent process could not distinguish the difference. They were all marked as "not started".  The new approach will let the client job process to update the parent process what's the progress status of the job, The parent keeps an accurate client job status during the job run life cycle.
=> Enhanced the client job status

nvflare/fuel/hci/client/api.py, nvflare/ha/overseer/overseer.py, nvflare/private/fed/server/training_cmds.py
Fixes # .
Fix restarting the server breaks the current FlareAPI session issue.
When issuing the "restart" command, the CLI and FLARE API issued a shutdown command to the server and terminate the current FlareAPI session. Added back the auto-login to re-login the API for continuous operations.
=> added back the API auto login after server restart

examples/hello-world/step-by-step/cifar10/code/fl/train.py, job_templates/sklearn_linear/config_fed_client.conf, job_templates/sklearn_svm/config_fed_client.conf, job_templates/swarm_cse_pt/config_fed_client.conf, nvflare/app_common/abstract/params_converter.py, nvflare/app_common/ccwf/cse_client_ctl.py, nvflare/app_common/ccwf/cyclic_client_ctl.py, nvflare/app_common/ccwf/swarm_client_ctl.py, nvflare/app_common/executors/launcher_executor.py, nvflare/app_opt/pt/client_api_launcher_executor.py
- Add task name headers to ccwfs to support Client API TaskRegistry
- Add supported_tasks to ParamsConverter
=> Fix CCWF with Client API, ParamsConverter supported_tasks

examples/advanced/experiment-tracking/pt/learner_with_mlflow.py, examples/advanced/experiment-tracking/pt/learner_with_tb.py, examples/advanced/experiment-tracking/pt/learner_with_wandb.py
Adds global round info for logging metrics global step.
Previously when logging metrics in MLFlow, TB, and W&B, calculations were missing global round info. This adds the global epoch.
=> Add global round info for logging metrics global step

nvflare/private/fed/utils/fed_utils.py
Re-add numpy_decomposers to fed_utils.py since it has been separated from common_decomposers
=> Add numpy decomposers to fix 2.3 CI

nvflare/apis/impl/job_def_manager.py, nvflare/app_common/storages/filesystem_storage.py
Fix filesystem storage, _object_path() was used in tag_object()
=> Fix 2.2 CI

nvflare/private/fed/app/simulator/simulator_runner.py
Line 354 `run_status = self._get_return_code(return_dict, process, self.workspace)` is running in the main process while 
the workspace was being setup in the forked process.
Then this workspace setup will not be reflected back into the main process.
We move the workspace setup code inside the class constructor to solve this problem.
=> [2.4] Move workspace setup inside constructor

nvflare/app_common/abstract/params_converter.py
PR https://github.com/NVIDIA/NVFlare/pull/2260 add required functionalities but it breaks the "Filter" base class signature.
This PR removes the "Filter" base class inheritance
=> [2.4] Fix ParamsConverter signature

tests/integration_test/data/test_configs/standalone_job/hello_numpy_examples.yml, tests/integration_test/src/validators/np_sag_result_validator.py
=> Add hello-ccwf to ci

nvflare/private/fed/app/simulator/simulator_runner.py
Fixes # .
Removed the no need client custom path when creating the simulator client. Which caused appending long system PATH.
=> Removed the no need client custom path.

examples/advanced/cifar10/cifar10-sim/figs/plot_tensorboard_events.py
Fixes # .
Fixes a parsing error in the plotting script as in #2345.
=> Cifar10 fix plot

nvflare/apis/analytix.py, nvflare/app_opt/tracking/tb/tb_receiver.py
From MLflowWriter's "log_params"/"log_param" method, to TBReceiver's "add_scalar"/"add_scalars" method.
A simple conversion of data_type is incorrect.
We need to consider the type of the value to determine whether it is of data_type scalar (int or float)
or it is data_type text (str).
=> Fix tb receiver

examples/hello-world/ml-to-fl/np/code/train_loop.py, nvflare/app_common/launchers/subprocess_launcher.py
Capture stdout and stderr from subprocess in a thread and write the captured result to both logfile and stdout.
Note that since the output from print inside child process is usually buffered and may not appear on PIPE soon enough, the example python code, train_loop.py, always flushes its print.
=> [2.4] Add flush=True to print in subprocess

integration/nemo/examples/peft/README.md, integration/nemo/examples/prompt_learning/README.md, integration/nemo/examples/supervised_fine_tuning/README.md
note the directory for the docker run command
=> Clarify nemo example readme

nvflare/app_common/executors/client_api_launcher_executor.py, nvflare/app_common/executors/launcher_executor.py, nvflare/app_common/executors/task_exchanger.py, nvflare/fuel/utils/pipe/cell_pipe.py, nvflare/fuel/utils/pipe/file_pipe.py, nvflare/fuel/utils/pipe/pipe.py, nvflare/fuel/utils/pipe/pipe_handler.py
Fix PipeHandler receive blocks "send_heartbeat"
When sending heartbeats in PipeHandler (Line 323), we use timeout = None, which will be translated to use the default_request_timeout set to 5 seconds. This causes a problem where this send_to_peer(msg) can block the entire _try_read thread for up to 5 seconds. It is supposed to be a fast-checking loop.
When the loop is blocked, it also slows down the follow-up checking/sending heartbeat logic, making the system more prone to timeouts.
- Separate the sending of heartbeats outside of reading thread.
- To ensure the PipeHandler code re-usability, we make the "send" assumption of FilePipe to match CellPipe: If timeout is None, then wait forever.
=> [2.4] Fix Pipe and PipeHandler

nvflare/fuel/utils/pipe/file_pipe.py
FilePipe will create folders for communication if needed.
We need to get rid of those folders so it will not confuses users.
- Remove the created folder
=> Clean up FilePipe remains

.github/workflows/markdown-links-check.yml, .github/workflows/mlc_config.json, integration/nemo/examples/README.md, integration/nemo/examples/peft/README.md, integration/nemo/examples/prompt_learning/README.md, integration/nemo/examples/prompt_learning/prompt_learning_20B.md, integration/nemo/examples/supervised_fine_tuning/README.md
- Fix NEMO integration examples link.
- Ignore "catalog.ngc.nvidia.com" in link checks since it requires login
In the future we should make each example's NEMO version consistent.
=> [2.4] Fix NEMO links

.github/workflows/markdown-links-check.yml, .github/workflows/mlc_config.json, integration/nemo/examples/README.md, integration/nemo/examples/peft/README.md, integration/nemo/examples/prompt_learning/README.md, integration/nemo/examples/prompt_learning/prompt_learning_20B.md, integration/nemo/examples/supervised_fine_tuning/README.md
Fix nemo links, each example has different version:
- PEFT: Nemo v1.22.0, docker version 23.10
- Supervised fine tuning: Nemo v1.20.0, docker version 23.06
- prompt learning: Nemo v1.17.0, docker version 23.02
=> Fix NEMO links

nvflare/app_common/ccwf/common.py, nvflare/app_common/ccwf/cse_server_ctl.py, nvflare/app_common/ccwf/swarm_server_ctl.py
Fixes #4562056
The CCWF's cross-site-eval workflow (CSE) assumes all evaluatees have local models. However, depending on the config of the Swarm Learning workflow (usually before CSE) of the job, some clients may only be aggregators and don't train. In this case, the client that is not a trainer won't be able to submit local model, which causes the CSE to fail.
This PR fixes this issue by checking the client against the training clients list of Swarm Learning workflow. Only training clients will be treated as evaluatees.
=> Exclude non-training clients from cse

nvflare/fuel/utils/fobs/README.rst
The DatumManager is not mentioned in the FOBS README. It's fixed.
=> [2.4] Fixed the FOBS doc to add support for DatumManager

nvflare/app_opt/lightning/api.py
If users calling patch many times, we should not append more than one FLCallback and/or RestoreState
=> [2.4] Lightning API Patch just once

nvflare/app_opt/lightning/api.py
Lightning client api patch multiple times should just append once
Copy of #2416
=> Lightning client api patch multiple times

nvflare/private/fed/app/simulator/simulator_runner.py, nvflare/private/fed/app/simulator/simulator_worker.py
Fixes # .
Fixed the wrong path of workspace object in the simulator worker.
=> Fixed the wrong workspace object in the simulator worker

nvflare/private/fed/app/simulator/simulator_runner.py, nvflare/private/fed/app/simulator/simulator_worker.py
Fixes # .
Fixed the wrong path of workspace object in the simulator worker.
=> [2.4] Fixed the wrong workspace object in the simulator worker

nvflare/app_opt/xgboost/histogram_based_v2/controller.py, nvflare/app_opt/xgboost/histogram_based_v2/executor.py
Fixes 4570002 .
The current version of XGB integration only supports local XGB GRPC server and clients, there is no need for user to specify grpc options - default setting is sufficient.  This PR removes the grpc options arg from controller and executor.
We can add these args back when/if we need to support remote XGB GRPC server/clients in the future.
=> [2.4] always use default grpc opts

nvflare/fuel/f3/cellnet/cell.py
Same as #2406 
CellPipe's channel or all user defined application channels should have streaming capabilities unless otherwise opt out.
=> Enable StreamCell for all application channels

nvflare/private/fed/server/server_engine.py
Fixes 4574333
These two lines were incorrectly removed in https://github.com/NVIDIA/NVFlare/pull/2048/
These two lines were incorrectly removed in https://github.com/NVIDIA/NVFlare/pull/2048/
We need both RequestHeader.REQUIRE_AUTHZ and RequestHeader.ADMIN_COMMAND to do authorization
=> [2.4] Fix check resource auth

nvflare/private/fed/server/server_engine.py
Fixes 4574333
These two lines were incorrectly removed in https://github.com/NVIDIA/NVFlare/pull/2048
We need both RequestHeader.REQUIRE_AUTHZ and RequestHeader.ADMIN_COMMAND to do authorization
=> Add back request header

nvflare/app_opt/xgboost/histogram_based_v2/adaptor_controller.py, nvflare/app_opt/xgboost/histogram_based_v2/adaptors/grpc_client_adaptor.py, nvflare/app_opt/xgboost/histogram_based_v2/defs.py
Fixes #4572122.
When XGB client fails to start, the status and exit code were not set properly. So even though the XGB client already stopped , the server won't get notified properly.
This PR fixes this issue by setting the correct status code and exit code. When server receives the notification, it will terminate the job immediately.
=> [2.4] Improve xgb runner status check

nvflare/app_opt/tracking/wandb/wandb_receiver.py
Same as https://github.com/NVIDIA/NVFlare/pull/2444 for main
=> Check wandb login

nvflare/apis/utils/reliable_message.py
Python 3.8 ThreadPoolExecutor does not have this argument: https://docs.python.org/3.8/library/concurrent.futures.html
=> [2.4] Remove cancel_futures args

nvflare/private/fed/app/client/sub_worker_process.py
Fixes #2427 
The cell stop should just be run by the mpm callbacks. (in L174)
=> [2.4] Fix sub_worker_process shutdown

nvflare/fuel/utils/pipe/file_pipe.py, nvflare/fuel/utils/pipe/pipe_handler.py
When one end of pipe is shutting down, the pipe handler on this side is trying to send the END or ABORT event to the other side, and it blocks there forever.
If the other end has already shutdown, then our system never end.
- PipeHandler send Abort or End needs to fire and forget, so we use small number 0.1 instead of waiting forever
- Add a default timeout for FilePipe so it will not wait forever for control signals
=> [2.4] Fire and forget for pipe handler control messages

nvflare/apis/wf_controller_spec.py, nvflare/app_common/app_constant.py, nvflare/app_common/workflows/base_fedavg.py, nvflare/app_common/workflows/fedavg.py, nvflare/app_common/workflows/model_controller.py, nvflare/app_common/workflows/scaffold.py
- Add WFControllerSpec API for simpler definition for users
- Add non-blocking option to send_model()
=> Add controller interface

nvflare/private/fed/client/admin.py, nvflare/private/fed/server/server_engine.py
Fixes # .
Fixed the authorization failure for submit_job command when performing from lead role.
=> Fixed the authz and site_security check for check_resource command

nvflare/lighter/impl/cert.py
By design, provisioners can add clients or admins in project.yml and do provision to get additional client/admin startup kits.  The certs and private keys of existing participants are kept the same so that there is no need to re-distribute those existing startup kits.
When the role of existing admin changes in project.yml, its cert/private key and thus the role in subject's unstructured_name, do not change.  This causes confusion as provisioners may think a new set of cert/private key is generated.
This PR adds a warning during provisioning time so that provisioners know what to do to generate the new startup kits.
=> [2.4] Add warning when the same admin in project.yml has different role

nvflare/app_opt/pt/in_process_client_api_executor.py
remove old `task_fn_args` from `PTInProcessClientAPIExecutor`
=> Remove task_fn_args

nvflare/apis/impl/controller.py, nvflare/apis/responder.py, nvflare/private/fed/client/client_runner.py, nvflare/private/fed/server/server_runner.py
Fixes # .
This PR tries to fix incorrect client drop issues of v2.3 used by AV.
The dead client handling in controller is flawed:
- If there is network glitch between client and server, the SJ could get "client dead" report. There is a grace period of 30 secs and any getTask and submitResult received in the 30 secs, the client would be revived. However if the client's training takes long time, the client won't send such messages, which will result in the client to be considered dead.
- The client CJ keeps sending HBs to SJ, but currently HBs are not used to revive dead client.
- cyclic controller intercepts the dead-client report messages and incorrectly handles it.
This PR tries to fix these issues:
- No controllers should intercept dead-client report handling. It should be handled only …
=> [2.3] fix client death handling

nvflare/private/fed/app/utils.py
`init_security_content_service()` doesn't need to create Workspace object
=> Fix simulator workspace

nvflare/fuel/f3/drivers/aio_grpc_driver.py, nvflare/fuel/f3/drivers/grpc_driver.py
Log all exceptions at error level for both AIO and sync GRPC drivers.
=> [2.3] Changed exception log to error level for GRPC drivers

nvflare/app_common/widgets/metric_relay.py
Follow #2495, we should start heartbeat at START_RUN.
And we don't need to have heartbeat timeout at NVFlare client executor side, because LauncherExecutor will handle it.
=> [2.4] Fix metric relay pipe handler timeout

nvflare/fuel/f3/drivers/aio_grpc_driver.py
AioGrpcDriver exception handling bug: in python 3.8, `asyncio.CancelledError` was changed to subclass `BaseException` instead of `Exception`, so it will not be caught with `except Exception as ex:`
=> [2.3] Fix 2.3 unit tests

nvflare/app_common/ccwf/server_ctl.py
Check workflow id when handling event before calling `_update_client_status()` for the case of multiple workflows
=> Fix update client status

nvflare/fuel/f3/drivers/aio_grpc_driver.py
remove excessive `secure_format_traceback()`
=> [2.3] Remove unneeded tracebacks

tests/integration_test/src/validators/np_sag_result_validator.py
unblock CI for now, need further investigation for "No module named '_sysconfigdata__x86_64-linux-gnu'""
=> [2.3] Ignore sysconfigdata test error

nvflare/app_common/executors/launcher_executor.py, nvflare/app_common/executors/task_exchanger.py
To address both scenarios where launch_once is set to False or True, we remove the skip condition ``if self._current_task is None: continue``. This skip condition is inaccurate.
The LauncherExecutor should not use this skip; instead, it should verify whether the external process is running to determine whether to pause or resume the PipeHandler heartbeat.
For instance, consider a scenario where the TASK is very large (4GB or more).
When launch_once is set to False, the PipeHandler heartbeat begins at the "START_RUN" event, while the NVFlare client process attempts to pull the task from the server. This process can take a significant amount of time (up to 300 seconds or more). The external process is only started after the task is pulled (in the execute method). Since the PipeHandler …
=> [2.4] Rely on launcher check_run_status to pause/resume heartbeat

nvflare/app_common/executors/in_process_client_api_executor.py, nvflare/app_common/executors/launcher_executor.py, nvflare/app_common/workflows/base_fedavg.py, nvflare/app_common/workflows/fedavg.py, nvflare/app_common/workflows/model_controller.py, nvflare/app_common/workflows/scaffold.py, nvflare/app_common/workflows/wf_controller.py, nvflare/client/in_process/api.py
- make round-based information optional for controller, launcher, and in-process client api sides
- fix in-process client api bug (previously we were creating a new InProcessClientAPI for each task which would require calling flare.init() on the client-side each time)
- rename ModelController method to broadcast_model()
- add default persistor_id with warning if persistor does not exist
=> Enhance WFController

tests/integration_test/run_integration_tests.sh
preflight tests currently occasionally fail with `TimeoutError: Lock error: Matplotlib failed to acquire the following lock file:
/root/.cache/matplotlib/fontlist-v330.json.matplotlib-lock`
experimented with clearing matplotlib cache dir, needs more investigation
=> Temporarily disable preflight tests

nvflare/private/fed/app/simulator/simulator.py, nvflare/private/fed/app/simulator/simulator_runner.py
Fixes # 
Address the simulator run large number of clients performance issue.
Simulator only runs the END_RUN events for those active running clients when the workflow finishes the run. All those swapped out clients need to be swapped in and re-created to run the END_RUN event handling. Most of the applications the END_RUN event handling are not needed when the client processes are not active. Change the simulator to provide an "end_run_for_all" option. The default is false. Only set it to run END_RUN event handling for all clients when explicitly set.
Also change to use multi-threads to run the END_RUN event handling if needed.
=> Simulator end run for all clients

examples/advanced/job_config/hello-pt/hello_pt_job.py, nvflare/job_config/fed_job_config.py
Fixes # .
simplify Pythonic job simulator_run to take only workspace parameter.
=> simplify Pythonic job simulator_run with only workspace parameter

nvflare/app_common/workflows/base_fedavg.py, nvflare/app_common/workflows/fedavg.py
Allow users to define `aggregate_fn` without needing to overwrite FedAvg's `run()` routine.
=> User-defined aggregate_fn

integration/monai/examples/spleen_ct_segmentation_local/README.md, integration/monai/examples/spleen_ct_segmentation_sim/README.md, integration/monai/monai_nvflare/client_algo_executor.py
Follows https://github.com/Project-MONAI/MONAI/pull/7745 to pass False so MONAI bundle logging will not disable NVFlare logging.
=> [2.4] Update ClientAlgo

nvflare/dashboard/cli.py
This PR adds options in dashboard cli for cloud deployment.  Originally, those options were in server and client cloud deployment scripts.
=> Add option in dashboard cli for AWS vpc and subnet

examples/hello-world/step-by-step/cifar10/code/fl/train_with_mlflow.py
Fixes # .
global step calculation bug
=> [2.4] Fix global steps in MLflow example

integration/monai/setup.py
Update the monai_nvflare setup.py to 0.2.8 and its nvflare dependency to ~=2.4.1rc8
=> [2.4] Bump up monai nvflare

nvflare/fuel/utils/class_utils.py, nvflare/job_config/fed_job_config.py, tests/unit_test/fuel/utils/class_utils_test.py
Fixes # .
Moved the get_component_init_parameters to class_utils for sharing function.
=> Moved the get_component_init_parameters to class_utils

nvflare/job_config/fed_job_config.py
Fixes # .
To support  moving the component class into the top-level main script for job creation API.
=> added handle for class in the to-level main script for job creation API.

examples/hello-world/job_api/tf/requirements.txt, examples/hello-world/job_api/tf/src/cifar10_tf_fl.py, examples/hello-world/job_api/tf/src/tf_net.py, examples/hello-world/job_api/tf/tf_fedavg_script_executor_cifar10.py, nvflare/app_opt/tf/model_persistor.py
Fixes # .
Enable delayed Keras model build for job API. Otherwise, the model would be built twice (once during job creation and once during simulation), which causes the code to hang.
=> Enable delayed model build

nvflare/app_common/app_constant.py, nvflare/app_common/statistics/hierarchical_numeric_stats.py, nvflare/app_common/workflows/hierarchical_statistics_controller.py, tests/unit_test/app_common/statistics/hierarchical_numeric_stats_test.py
This change adds hierarchical federated statistics support.
The existing `StatisticsController` outputs global statistics in a flat hierarchy. There are usecases where global statistics are required to be generated as per the given hierarchy configuration where NVFlare clients can be specified to belong to a particular hierarchy.
The new class `HierarchicalStatisticsController` is added to support hierarchical statistics. It is derived from `StatisticsController` and takes additional argument `hierarchy_config` for hierarchy specification file providing details about all the clients and their hierarchy.
Example hierarchy config file contents:
{
"Manufacturers": [
{
"Name": "Manufacturer-1",
"Orgs": [
{
"Name": "Org-1",
"Sites": ["Site-1"]
},
{
"Name": "Org-2",
"Sites": ["Site-2"]
}
],
}, …
=> Add hierarchical statistics support

nvflare/fuel/hci/client/fl_admin_api.py, nvflare/fuel/hci/cmd_arg_utils.py, nvflare/private/fed/server/shell_cmd.py
Fixes # .
This PR fixes bug https://nvbugspro.nvidia.com/bug/4686492
When a log file (log.txt) is rotated, the previous file name becomes "log.txt.1". and file extension becomes "1". Admin commands like "cat" won't work from this file.
This PR fixes this problem for version 2.4.
=> [2.4] Support log file rotation in admin commands

nvflare/fuel/hci/client/fl_admin_api.py, nvflare/fuel/hci/cmd_arg_utils.py, nvflare/private/fed/server/shell_cmd.py
Fixes # .
This PR fixes https://nvbugspro.nvidia.com/bug/4686492
When a log file (log.txt) is rotated, the previous file name becomes "log.txt.1". and file extension becomes "1". Admin commands like "cat" won't work from this file.
This PR fixes this problem.
=> [2.5] Support log file rotation in admin commands

CONTRIBUTING.md, docs/contributing.rst, docs/real_world_fl/flare_api.rst
Fixes # .
This change fixes:
- Typos in the `build_doc.sh` references.
- Incorrect rendering of python code blocks on Flare API page.
Came across few typos while going through the provisioning documentation. The python code blocks were getting rendered incorrectly on FLARE API page as can be seen below:
This change fixes it to:
And fixes few typos where `build_doc.sh` was referenced as `build_docs.sh`
=> Fix docs typos

nvflare/lighter/dummy_project.yml, nvflare/lighter/ha_project.yml
Fixes # .
This change just fixes comments in `project.yml` templates to make it more clear.
The `project.yml` generated by `nvflare provision` command has comments `change overseer.example.com to the FQDN of the overseer` and `change example.com to the FQDN of the server` but the actual values nowhere has `example.com` mentioned and it is confusing.
=> Fix `project.yml` master templates

integration/xgboost/processor/src/nvflare-plugin/local_processor.cc, nvflare/app_opt/xgboost/histogram_based_v2/runners/xgb_client_runner.py
Fixes https://jirasw.nvidia.com/browse/FLARE-2047
Introduced a bug in LocalProcessor when fixing a memory leak. Used wrong function (reserve->resize).
Fixed a typo discovered by QA.
=> [2.4] Fixed a LocalProcessor bug and a typo

docs/programming_guide/execution_api_type/client_api.rst
Fixes # .
Updated the client_api executor docs to explain the "launch_once" option for in-process and sub-process executors.
=> update client_api executor docs

nvflare/lighter/impl/docker.py
Fixes # .
The `compose.yml` generated by the `DockerBuilder` class adds a build section only for the overseer. As a result, when we have non-HA mode `project.yml`, generated `compose.yml` won't have the build section and so `docker compose build` won't build the required NVFlare docker image.
This change adds a build section in the generated `compose.yml` even for clients and servers. It fixes the above issue and also with this change, same `compose.yml` can be used to build/run individual servers and clients using the `docker compose` method.
=> Fix DockerBuilder to add `build` section

nvflare/private/fed/server/server_engine.py, nvflare/private/fed/simulator/simulator_server.py
Fixes # .
Allow the ServerRunner to pass END_RUN aux messages to the clients when running the simulator. Still keeps the behavior to avoid un-necessary error messages if client run finishes earlier when sending the messages.
=> Allow the simulator to pass the End_Run aux message to clients

nvflare/app_common/workflows/scatter_and_gather.py
Fixes # .
Changed the ScatterAndGather default persistor_id value from "" to "persistor".
=> Change the ScatterAndGather default persistor_id

nvflare/lighter/impl/aws_template.yml, nvflare/lighter/impl/master_template.yml, nvflare/lighter/tplt_utils.py
Deploying cloud infrastructure across multiple AWS regions can be challenging due to each region having unique AMI image IDs. With these proposed changes, the user will be prompted to select their region first, followed by their desired image name (default: ubuntu-*-22.04-amd64-pro-server). After confirming an amd64 or arm64 image name pattern, NVFlare will look up the appropriate AMI image ID, identify a compatible GPU instance type based on resources.json, and present the user with these new defaults. Dynamically obtaining the AMI ID also ensures that the user always has the latest image with all security updates already installed. 
I tested the following combinations over the last few days but only the 24.04 ARM option seems to fail with NVidia drivers 535 and 550. The instances just …
=> AWS cloud deployments: Adding multi-region capability and auto-detection of GPU instance types and AMI images 

nvflare/apis/utils/reliable_message.py
Fixes # .
This PR fixes a potential memory issue in the receiving side of the ReliableMessage.
When a request is received, a RequestReceiver object is created and kept in a table. Currently, after the request is finished, we still keep the RequestReceiver object in the table. RM has a monitoring process that will eventually release the object from the table. However this could take many minutes (depending on how tx_timeout is configured) before this happens. The problem is that all reply messages (could be very big) will remain in the table until the monitoring process remove them. This could potentially cause OOM if there are many requests in quick succession.
This PR solve this problem by releasing the RequestReceiver object immediately after the request is done and replied …
=> [2.4] Release RM request receiver after finished

examples/getting_started/tf/nvflare_tf_getting_started.ipynb, examples/getting_started/tf/tf_fedavg_script_executor_cifar10.py
Fixes #[2040](https://jirasw.nvidia.com/browse/FLARE-2040)
default params exchange format is pytorch, need to change for tensorflow
=> Add correct params exchange format for tf

nvflare/apis/event_type.py, nvflare/apis/utils/reliable_message.py, nvflare/app_opt/xgboost/histogram_based_v2/adaptors/grpc_client_adaptor.py, nvflare/app_opt/xgboost/histogram_based_v2/adaptors/xgb_adaptor.py, nvflare/app_opt/xgboost/histogram_based_v2/controller.py, nvflare/app_opt/xgboost/histogram_based_v2/defs.py, nvflare/app_opt/xgboost/histogram_based_v2/executor.py, nvflare/app_opt/xgboost/histogram_based_v2/sec/client_handler.py, nvflare/app_opt/xgboost/histogram_based_v2/sec/sec_handler.py
Fixes FLARE-2053
Made changes so ipcl-python package is only required for vertical secure training using nvflare plugin.
=> [2.4] Remove ipcl requirement for other training mode except vertical secure

nvflare/lighter/impl/aws_template.yml, nvflare/lighter/impl/azure_template.yml, nvflare/lighter/impl/master_template.yml
Sorry about this folks, should have known better but there was an OSX compatibility issue with my recent pull request 2650
This new PR addresses a bug with MacOS introduced with c73f6149a92d0b1c3d909381e33c4cf2e718e964 because "read -i" requires Bash >= 4 (newer than 2009 !) as OSX only comes with Bash 3.2 by default (you can use brew to install a newer version)
Refactor of prompt function has:
- editable prompts with read -i ONLY if Bash >= 4
- in cases where you do not want or need an editable prompt (e.g. AMI ID) you leave out the 3rd argument
- fully compatible with previous prompt function (only cosmetic changes in azure template)
so if you are on Bash >= 4 you can edit the default values in place (except the AMI id)
```
* Cloud EC2 region, press ENTER to accept default: us-west-2
* …
```
=> BUGFIX: cloud deployment script issue with OSX 

nvflare/app_common/workflows/base_model_controller.py, nvflare/app_common/workflows/model_controller.py
#[4717625](https://nvbugspro.nvidia.com/bug/4717625)
- expose `min_responses` argument in ModelController's `send_model_and_wait()`
- hide `wait_time_after_min_received` argument, set default to 0
=> Add min_responses to send_model_and_wait()

examples/advanced/cifar10/cifar10-sim/jobs/cifar10_central/cifar10_central/config/config_fed_server.json, examples/advanced/cifar10/cifar10-sim/jobs/cifar10_fedavg/cifar10_fedavg/config/config_fed_server.json, examples/advanced/cifar10/cifar10-sim/jobs/cifar10_fedprox/cifar10_fedprox/config/config_fed_server.json, examples/advanced/lr-newton-raphson/job/newton_raphson/app/custom/newton_raphson_workflow.py, examples/getting_started/pt/fedavg_model_learner_xsite_val_cifar10.py, examples/getting_started/pt/fedavg_script_executor_cifar10.py, examples/getting_started/pt/fedavg_script_executor_dp_filter_cifar10.py, examples/getting_started/pt/fedavg_script_executor_lightning_cifar10.py, examples/getting_started/pt/nvflare_lightning_getting_started.ipynb, examples/getting_started/pt/nvflare_pt_getting_started.ipynb, examples/getting_started/tf/nvflare_tf_getting_started.ipynb, examples/getting_started/tf/tf_fedavg_script_executor_cifar10.py, integration/monai/examples/mednist/job_templates/fedavg_mednist/config_fed_server.conf, job_templates/fedopt_pt/config_fed_server.conf, nvflare/app_common/workflows/base_fedavg.py, nvflare/app_common/workflows/base_model_controller.py, nvflare/app_common/workflows/cyclic.py, nvflare/app_common/workflows/fedavg.py, nvflare/app_common/workflows/model_controller.py, nvflare/app_common/workflows/scaffold.py, research/fed-bpt/src/global_es.py, tests/integration_test/data/jobs/pt_mc_fedavg/app/config/config_fed_server.conf, web/src/components/code.astro
ModelController enhancements #[2049](https://jirasw.nvidia.com/browse/FLARE-2049)
1. BaseFedAvg: change `min_clients` -> `num_clients` for clarity now that we hid `wait_time_after_min_received` and we are sending to `num_clients` targets rather than all clients.
2. Improve docstring of `sample_clients()`
3. Clarify meaning of `timeout` in `send_model_and_wait()` and `send_model()`
4. Add `min_responses` and hide `wait_time_after_min_received` (https://github.com/NVIDIA/NVFlare/pull/2675)
=> Enhance ModelController arguments

examples/getting_started/pt/nvflare_lightning_getting_started.ipynb, examples/getting_started/pt/nvflare_pt_getting_started.ipynb, examples/getting_started/tf/nvflare_tf_getting_started.ipynb
add src download and simulator command option if using Google Colab
=> Update getting started notebooks for 2.5.0rc

nvflare/apis/utils/reliable_message.py
- checkout the nvflare/apis/utils/reliable_message.py from 2.4 to main
=> Use ReliableMessage from 2.4

nvflare/cli.py, nvflare/tool/poc/poc_commands.py, nvflare/utils/cli_utils.py
If users type "nvflare config" without entering any information, the old code will just raise an Exception and users see only:
```
"raise ValueError(f"job_templates_dir='{args.job_templates_dir}', it is not a directory")"
```
Add a new behavior so if specified nothing, users can check where the file is, and what is the current content of that hidden file.
If any directory is specified, the behavior is the same as before.
- Add print_hidden_config
- Reuse methods from nvflare/utils/cli_utils.py
=> Enhance CLI command config

nvflare/fuel/f3/cellnet/cell_cipher.py, nvflare/fuel/f3/cellnet/core_cell.py
After 7/20/2024, our CI has been failing with the following error:
```
TypeError: unsupported operand type(s) for +: 'memoryview' and 'bytes'
```
The old cryptography package (version 42.0.8) when it does the following code:
```
def _sym_enc(k: bytes, n: bytes, m: bytes) -> bytes:
cipher = Cipher(algorithms.AES(k), modes.CBC(n), backend=default_backend())
encryptor = cipher.encryptor()
padder = padding.PKCS7(PADDING_LENGTH).padder()
padded_data = padder.update(m) + padder.finalize()
return encryptor.update(padded_data) + encryptor.finalize()
```
If the "m" is an object of type `memoryview`, the `padder.update(m)` will return an object of `bytes` type.
With the new cryptography package (version 43.0.0) released in 7/20/2024 when it does `padder.update(m)` with a `memoryview` type it will …
=> Fix cell encrypt

nvflare/private/fed/app/simulator/simulator_runner.py
Fixes # .
keep the local resources for simulator. Users can add any local settings in the "local" folder within the simulator workspace.
=> keep the local resources for simulator

tests/integration_test/overseer_test.py
10 second is not enough for the client agent to get the updated SP address.
Increase this test case to wait 20 seconds before checking.
=> Fix overseer test timing

docs/programming_guide/controllers/model_controller.rst, docs/programming_guide/fl_model.rst, docs/programming_guide/workflows_and_controllers.rst, nvflare/app_common/workflows/base_model_controller.py, nvflare/app_common/workflows/model_controller.py
=> Add ModelController documentation

integration/monai/examples/spleen_ct_segmentation_local/README.md
- Update REAME for clarification on MLflow server / ui
=> Update MONAI example

job_templates/cyclic_cc_pt/config_fed_client.conf, job_templates/cyclic_pt/config_fed_client.conf, job_templates/sag_cse_pt/config_fed_client.conf, job_templates/sag_gnn/app_1/config_fed_client.conf, job_templates/sag_gnn/app_2/config_fed_client.conf, job_templates/sag_np/config_fed_client.conf, job_templates/sag_np_cell_pipe/config_fed_client.conf, job_templates/sag_np_metrics/config_fed_client.conf, job_templates/sag_pt/config_fed_client.conf, job_templates/sag_pt_deploy_map/app_1/config_fed_client.conf, job_templates/sag_pt_deploy_map/app_2/config_fed_client.conf, job_templates/sag_pt_he/config_fed_client.conf, job_templates/sag_pt_mlflow/config_fed_client.conf, job_templates/sag_tf/config_fed_client.conf, job_templates/sklearn_kmeans/config_fed_client.conf, job_templates/sklearn_linear/config_fed_client.conf, job_templates/sklearn_svm/config_fed_client.conf, job_templates/swarm_cse_pt/config_fed_client.conf, job_templates/xgboost_tree/config_fed_client.conf, nvflare/app_common/executors/task_exchanger.py, nvflare/app_common/widgets/metric_relay.py, setup.cfg
Cherry-pick from #2415 #2442 #2472 #2525
=> Cherry pick fixes from 2.4

docs/user_guide/federated_xgboost/secure_xgboost_user_guide.rst
=> Update xgboost user guide

docs/examples/fl_experiment_tracking_mlflow.rst
=> Fix config file name in doc

nvflare/private/fed/app/utils.py
Fixes # .
Change to use process.kill() to kill the children processes. This force kill the example like flow child process.
=> Improve the kill children processes

nvflare/apis/utils/reliable_message.py, nvflare/app_opt/xgboost/histogram_based_v2/adaptors/grpc_server_adaptor.py
Fixes FLARE-2184
Add a lock in processing receiving messages so messages are not processed twice.
=> Add lock to reliable message

nvflare/app_common/ccwf/ccwf_job.py, nvflare/job_config/api.py, nvflare/job_config/script_runner.py
Fixes # .
The CCWFJob's SwarmClientConfig and CyclicClientConfig require the executor to be Executor. This will cause the type check to fail when using ScriptRunner as the executor, since ScriptRunner is not a true Executor.
Disabled the type check in CCWFJob.
Also improved ScriptRunner to return component IDs added to the job.
=> Support ScriptRunner in ccwf_job

nvflare/apis/utils/reliable_message.py, nvflare/app_opt/xgboost/histogram_based_v2/adaptors/grpc_server_adaptor.py, nvflare/app_opt/xgboost/histogram_based_v2/adaptors/xgb_adaptor.py
1. Added XGB debug info in reliable message log. This will try to nail down a problem reported by QA.
2. Ignore GRPC errors after XGB shutdown. This will alleviate the issues caused by unknown GRPC failures at the end of training.
=> Added Debug in ReliableMessage and Ignore XGB errors after shutdown

nvflare/apis/fl_constant.py, nvflare/app_common/launchers/subprocess_launcher.py, nvflare/private/fed/app/simulator/simulator_runner.py, nvflare/private/fed/client/client_executor.py, nvflare/private/fed/server/server_engine.py, nvflare/private/fed/utils/fed_utils.py
…ath.
Fixes # .
Fixed the SubprocessLauncher missing app_custom_folder in the PYTHONPATH, which caused the ScriptRunner launch_external_process failure.
=> Fixed the SubprocessLauncher missing app_custom_folder in PYTHONPATH

nvflare/app_common/abstract/fl_model.py
- Add check for FLModel metrics to be a dict to avoid unclear error in [4778901](https://nvbugswb.nvidia.com/NVBugs5/redir.aspx?url=/4778901)
- Decorator was using float for metrics which was inconsistent with FLModel usage, however team decided decorator pattern will be deprecated
An alternative option is to instead check that the result.metrics are dicts before using WeightedAggregationHelper()
=> Add FLModel parameter checks

nvflare/app_common/workflows/base_model_controller.py, nvflare/app_common/workflows/model_controller.py
Address [4822385](https://nvbugswb.nvidia.com/NVBugs5/redir.aspx?url=/4822385) to use AppConstants.DEFAULT_PERSISTOR_ID
=> Clarify default persistor_id

nvflare/apis/utils/reliable_message.py
Added a check for duplicate ReliableMessage request so no duplicate message was received.
=> Added check for duplicate RM request

nvflare/app_opt/xgboost/histogram_based_v2/adaptors/xgb_adaptor.py
Remove a debug statement that causes XGB training failures.
=> Fix an XGB Failure caused by len()

examples/advanced/vertical_federated_learning/cifar10-splitnn/jobs/cifar10_psi/site-1/config/config_fed_client.json, examples/advanced/vertical_federated_learning/cifar10-splitnn/jobs/cifar10_psi/site-2/config/config_fed_client.json, research/one-shot-vfl/jobs/cifar10_psi/site-1/config/config_fed_client.json, research/one-shot-vfl/jobs/cifar10_psi/site-2/config/config_fed_client.json
Fixes # .
Fixed the wrong dh_psi_task_handler path in the example and research folder.
=> Fixed the wrong dh_psi_task_handler path

nvflare/app_opt/flower/applet.py, nvflare/app_opt/flower/executor.py, nvflare/app_opt/flower/flower_job.py
Fixes # .
This PR adds the support of passing custom env variables to Flower client. This is necessary to enable Flower client with Flare's client api to check the env var for config processing.
=> support passing custom env vars for flower client

research/quantifying-data-leakage/src/nvflare_gradinv/learners/cxr_learner.py, research/quantifying-data-leakage/start_fl_sim.sh
Fixes # .
* Fixes the path when cross site validation result after training
* Add info for clients that don't validate. Validation only happens on "site-1" in this example.
=> Gradient inversion: fix cross-validation path

nvflare/app_common/abstract/launcher.py, nvflare/fuel/utils/class_utils.py
Fixes # .
Make the Launcher extends FLComponent. Print out the class loading error for module scan.
=> Make the Launcher extends FLComponent

nvflare/app_common/executors/client_api_launcher_executor.py, nvflare/app_common/executors/task_exchanger.py, nvflare/app_common/widgets/metric_relay.py, nvflare/client/config.py, nvflare/client/ex_process/api.py, nvflare/job_config/script_runner.py
Fixes [4820226](https://nvbugspro.nvidia.com/bug/4820226).
- Using the LauncherExecutor with Cyclic failed due to the FlareAgent timing out while the first site trains
- Add heartbeat_timeout to config for FlareAgent and set heartbeat_timeout=0 to not timeout in ScriptRunner ex-process mode
=> Fix heartbeat timeout config

nvflare/job_config/fed_job_config.py
Fixes # .
Change to match the last index of module_path from source_file.
=> Fix for last index of module path

research/fed-bn/README.md, research/fed-bn/create_job.sh, research/fed-bn/run_job.sh
Per VDR finding, update the job/workspace path and add the tensorboard path in FedBN example 
=> Update fedbn example

examples/hello-world/step-by-step/cifar10/cse/cse.ipynb, examples/hello-world/step-by-step/cifar10/cyclic_ccwf/cyclic_ccwf.ipynb
=> Fix sbs notebooks

examples/advanced/finance-end-to-end/requirements.txt, examples/advanced/finance/requirements.txt, examples/advanced/random_forest/requirements.txt, examples/advanced/vertical_xgboost/requirements.txt, examples/advanced/xgboost/histogram-based/requirements.txt, examples/advanced/xgboost/tree-based/requirements.txt, examples/hello-world/step-by-step/higgs/xgboost/requirements.txt, integration/xgboost/encryption_plugins/README.md
- Ping to a specific wheel: https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/federated-secure/xgboost-2.2.0.dev0%2B4601688195708f7c31fcceeb0e0ac735e7311e61-py3-none-manylinux_2_28_x86_64.whl
- CUDA support 12.2 and 12.4
=> Update xgboost requirements

nvflare/fuel/f3/streaming/blob_streamer.py, nvflare/private/aux_runner.py
1. Added debug info for memoryview error
2. Check the request type for aux message dispatcher
=> Added debug info for memoryview error

nvflare/job_config/fed_job_config.py, tests/unit_test/job_config/fed_job_config_test.py
Fixes # .
trim the whitespace of the clients and gpu from the job simulator_run.
=> trim the whitespace of the clients and gpu from the job simulator_run

nvflare/job_config/script_runner.py
- To support both TransferType.FULL and TransferType.DIFF for InProcessClientAPIExecutor and ClientAPILauncherExecutor
- Add parameter for now. Will look to further enhance in the future to clarify/consolidate FLModel.params_type and executor's params_transfer_type for better experience
=> Add params_transfer_type to ScriptRunner

examples/advanced/random_forest/README.md, examples/advanced/random_forest/random_forest.ipynb, examples/advanced/sklearn-linear/README.md, examples/advanced/sklearn-linear/sklearn_linear_higgs.ipynb, examples/advanced/vertical_xgboost/README.md, examples/advanced/xgboost/README.md, examples/advanced/xgboost/data_job_setup.ipynb, examples/hello-world/step-by-step/higgs/README.md
Cherry-pick https://github.com/NVIDIA/NVFlare/pull/2941
=> [2.5] Update higgs data link

nvflare/lighter/utils.py
The local/resources.json.default was not generated correctly in dashboard.  This may cause jobs received by the server could not be dispatched/scheduled.
=> [2.5] Fix dashboard server resource

nvflare/fuel/f3/streaming/blob_streamer.py, nvflare/fuel/f3/streaming/byte_receiver.py, nvflare/fuel/f3/streaming/stream_types.py
Fixes FLARE-2241
1. Refactored F3 streaming code so it's more object oriented, easier to debug.
2. Fixed a few corner cases found during testing with a testing driver that injects duplicate packets.
=> [2.5] F3 Streaming Code Rewrite

examples/advanced/xgboost/histogram-based/xgboost_histogram_higgs.ipynb, examples/advanced/xgboost/tree-based/utils/plot_tensorboard_events.py
=> [2.5] Fix simulator result path

examples/advanced/psi/user_email_match/README.md, examples/advanced/psi/user_email_match/requirements.txt, nvflare/app_common/psi/dh_psi/dh_psi_workflow.py
Update openmind-psi ==2.0.4 to support python 3.11
=> update PSI to support python 3.11

nvflare/app_common/ccwf/ccwf_job.py, nvflare/job_config/api.py
Fixes # .
Currently when the same object is used in a job, duplicate config will be created, which will cause two object instances to be created during run time.
This PR makes it possible for the object to be reused multiple times without creating separate object instances.
This change is necessary in case that same object instance (e.g. model persistor) is used for different workflows in the same job.
=> [Main] Support object reuse

nvflare/tool/job/job_cli.py
Fixes # .
The disutils package has been deprecated in Python 3.12. Replaces it with shutil package.
=> Replace the distutils with shutil

web/public/scripts/ua_latest.js, web/src/components/clickTracker.astro, web/src/components/code.astro, web/src/components/gettingStarted.astro, web/src/components/hero.astro, web/src/components/learnMore.astro, web/src/components/overview.astro, web/src/components/series.astro, web/src/components/tutorials.astro, web/src/layouts/Layout.astro
- using umami analytics with self hosted script
- add events to track activity for different sections
=> Add umami analytics

nvflare/app_common/ccwf/ccwf_job.py, nvflare/job_config/api.py
=> [2.5] Job api update

ci/run_integration.sh, setup.cfg
Update test script to support Python 3.12 Jenkins CI.
Same as #3001
=> Update test script

nvflare/fuel/f3/streaming/byte_receiver.py, nvflare/fuel/f3/streaming/byte_streamer.py, nvflare/fuel/f3/streaming/stream_utils.py
Refactored byte_streamer.py to change TxTask into an object, similar to the refactoring of RxTask.
=> Refactoring F3 Streaming sender

examples/hello-world/hello-flower/README.md, examples/hello-world/hello-flower/flwr-pt-tb/flwr_pt_tb/client.py, examples/hello-world/hello-flower/flwr-pt-tb/flwr_pt_tb/server.py, examples/hello-world/hello-flower/job.py, nvflare/app_opt/flower/flower_pt_job.py
Fixes #2962 .
- Get rid of set_context, get_context as that is deprecated by Flower
- Separate FlowerJob and FlowerPytorchJob
- Change to new style of Flower server code
=> Update flwr job object, client, server

docs/real_world_fl/overview.rst
Fixes #3021 .
Removed leading space, which was causing the link to brake.
=> [#3021] Fixed broken doc ref to 'helm_chart'

research/fed-bpt/README.md, research/fed-bpt/requirements.txt
Fixes # .
Cherry-pick https://github.com/NVIDIA/NVFlare/pull/3029
=> [2.5] Fedbpt fix

docs/quickstart.rst, docs/user_guide/nvflare_cli/poc_command.rst, examples/tutorials/setup_poc.ipynb
=> Enhance POC notebook and docs

docs/quickstart.rst
=> Use multi-line table

nvflare/app_opt/xgboost/histogram_based_v2/mock/mock_executor.py, nvflare/app_opt/xgboost/histogram_based_v2/mock/mock_secure_executor.py
Fixes # .
The mock executors in XGboost is out of sync with the XGBExecutor base.  This PR fixes these problems.
=> Fix mock executors

nvflare/app_opt/tf/job_config/base_fed_job.py, nvflare/app_opt/tf/tb_receiver.py
Add TF based TBAnalyticsReceiver
- Add TF based TBAnalyticsReceiver
=> [2.5] Add TF based TBAnalyticsReceiver

examples/advanced/finance-end-to-end/README.md, examples/advanced/finance-end-to-end/xgboost.ipynb
Fixes # .
Correction for figure mis-alignment on finance end-to-end readme
=> Update finance end-to-end readme for figure position

nvflare/fuel/f3/cellnet/cell.py, nvflare/fuel/f3/cellnet/utils.py, nvflare/fuel/f3/streaming/byte_streamer.py, nvflare/fuel/f3/streaming/stream_types.py, nvflare/fuel/utils/waiter_utils.py, nvflare/private/aux_runner.py, nvflare/private/fed/client/client_engine_executor_spec.py, nvflare/private/fed/client/client_run_manager.py, nvflare/private/fed/client/communicator.py, nvflare/private/fed/server/server_commands.py
Fixes # .
This PR adds the capability to abort/cancel the sending of a message. Without this, the system cannot be quickly aborted if the message is big.  This function is more important when streaming large messages or large number of objects, which can take long time.
=> Support aborting messages

nvflare/lighter/impl/aws_template.yml, nvflare/lighter/impl/azure_template.yml
Fixes #3045
Update the images used by dashboard launch scripts.
=> Update dashboard cloud base image version to meet Python 3.9

examples/advanced/vertical_federated_learning/cifar10-splitnn/src/splitnn/cifar10_learner_splitnn.py
Fixes # .
Add no_grad to validation steps to reduce GPU memory consumption.
Fixes https://github.com/NVIDIA/NVFlare/issues/3067
=> Add no_grad to validation steps

nvflare/private/fed/app/simulator/simulator_runner.py, nvflare/private/fed/utils/fed_utils.py, tests/unit_test/private/fed/app/simulator/simulator_runner_test.py
Fixes # .
Fixed the custom pythonpath missing issue for the simulator client run execution. Set up the custom PYTHONPATH before SImulatorRunner should be carried over to the client run execution.
=> [2.5] --- Fix custom pythonpath missing

nvflare/private/fed/simulator/simulator_server.py, tests/unit_test/fuel/f3/streaming/streaming_test.py, tests/unit_test/private/fed/app/deployer/simulator_deployer_test.py
Fixes # .
Added Simulator SP Aux message support.
=> Add Simulator SP Aux message support

examples/advanced/xgboost/histogram-based/requirements.txt, examples/advanced/xgboost/tree-based/requirements.txt, nvflare/app_opt/xgboost/histogram_based_v2/runners/xgb_client_runner.py
#3044 does not work with vertical splits.
- Add a check for split mode
- Add missing requirements
=> Fix xgb explainability issue

nvflare/fuel/f3/streaming/tools/utils.py
Renamed RX_CELL from server to receiver to avoid cell name conflicts with other tests.
=> Fix the streaming test conflict

nvflare/lighter/impl/static_file.py, nvflare/lighter/spec.py, nvflare/tool/poc/poc_commands.py
Fixes # .
Previous change to Provision broke the "poc start" command behavior: the user is prompted for username.  This PR fixes this.
The fix now allows a project to be provisioned in a specified "mode".  If the mode is not specified, then the project is provisioned in normal mode. If the mode is set to "poc", then when creating fed_admin.json (in StaticFileBuilder), the user's name will be added to the file, and the cred_type is set to "local_cert". 
The provision mode is set into the provision context (the "ctx"), which will allow any builder to do mode-specific processing.
=> Fix poc command

nvflare/private/fed/app/simulator/simulator_runner.py
Fixes # .
Fixed the simulator without custom folder job run error. Add check for the job custom folder existence.
=> Fix the simulator without custom folder job run error

nvflare/apis/fl_constant.py, nvflare/fuel/f3/cellnet/core_cell.py, nvflare/fuel/f3/cellnet/defs.py, nvflare/lighter/utils.py, nvflare/private/defs.py, nvflare/private/fed/app/client/client_train.py, nvflare/private/fed/app/client/worker_process.py, nvflare/private/fed/app/deployer/simulator_deployer.py, nvflare/private/fed/app/server/runner_process.py, nvflare/private/fed/app/server/server_train.py, nvflare/private/fed/app/simulator/simulator_worker.py, nvflare/private/fed/client/client_app_runner.py, nvflare/private/fed/client/client_engine.py, nvflare/private/fed/client/client_executor.py, nvflare/private/fed/client/communicator.py, nvflare/private/fed/client/fed_client_base.py, nvflare/private/fed/server/client_manager.py, nvflare/private/fed/server/fed_server.py, nvflare/private/fed/server/server_engine.py, nvflare/private/fed/utils/fed_utils.py, nvflare/private/fed/utils/identity_utils.py
Fixes # .
Currently Flare's message security comes from mutual TLS: server and client authenticate each other when making connections. This means that only clients that have the right startup kits can make a connection to the server. 
The requirement of one-way SSL between the server and clients breaks this assumption: the server could be exposed to the internet and any one could write a client to connect to the server. To ensure message security, explicit message authentication is required.
This PR implements message authentication: messages received by the server must have an auth token, and the token must be validated successfully to prove that it was issued by the server!
Here is how it works:
- The client first tries to login to the server. The server/client authenticate each other …
=> [2.5] Support explicit message authentication

nvflare/apis/fl_constant.py, nvflare/app_common/executors/client_api_launcher_executor.py, nvflare/app_common/executors/in_process_client_api_executor.py, nvflare/client/config.py, nvflare/client/ex_process/api.py, nvflare/fuel/data_event/utils.py, nvflare/fuel/utils/pipe/cell_pipe.py, nvflare/private/defs.py, nvflare/private/fed/client/communicator.py, nvflare/private/fed/utils/fed_utils.py
Fixes # .
Messages between CJ and Client API Agent could be relayed through the Server. Without proper authentication headers, these messages will be blocked. This PR adds auth headers to all such messages.
=> [2.5] Add authentication to Client API messages

nvflare/app_common/executors/client_api_launcher_executor.py, nvflare/client/config.py, nvflare/client/ex_process/api.py, nvflare/fuel/utils/pipe/cell_pipe.py, nvflare/private/fed/client/fed_client_base.py
Fixes # .
This PR adds support of Connection Security (TLS, mTLS, Clear) to Cell Pipe. This is necessary to ensure that client API based cells can connect to the server properly.
=> [2.5] Support connection security for cell pipe

nvflare/lighter/provision.py
Fixes #3093 .
When project_name in project.yml is longer than 64, generating the root CA cert fails due to CN field limit.  This PR truncates the project_name so it will not be longer than 64.  A friendly message is shown during provisioning if this happens.
=> Keep project_name shorter than the limit

docs/user_guide/federated_xgboost/secure_xgboost_user_guide.rst
Moved plugin building instructions to prerequisite section.
=> [2.5] Updated XGBoost User Guide

nvflare/client/ex_process/api.py
Fixes # .
One line code update to fix the `module 'nvflare' has no attribute 'app_opt'` error when using external process with numpy exchange format for pytorch
=> Fix external lib issue when used for pytorch with numpy exchange

nvflare/fuel/utils/fobs/fobs.py, tests/unit_test/fuel/utils/fobs/fobs_test.py
FOBS class loader didn't handle lazy-loaded class correctly. So some class can't be found.
It's fixed by using importlib.
=> [2.5] Fixed the FOBS lazy loading issue

nvflare/private/fed/client/client_engine.py
Fixes # .
Changed the client send_aux_request only log when receiving the response from the server.
=> update the client send_aux_request logging

tests/unit_test/app_common/executors/task_script_runner_test.py
The build directory sometimes is removed during the test is running,
right after the check "if os.path.exists(build_dir)", so we add "ignore_errors=True"
=> Add ignore_errors=True when trying to remove the build dir

nvflare/job_config/script_runner.py
The original hardcode 0 has a problem, if the external user code has an exception and the program will never return.
Our FL client job process (running LauncherExecutor) will never ends.
By using the default heartbeat_timeout value, if the FL client job process does not receive the heartbeat from the user process for heartbeat_timeout seconds, then we will consider it dead.
- Remove the hardcode 0 and use the default value for LauncherExecutor
=> Remove the hardcode 0 and use the default value for LauncherExecutor

examples/advanced/brats18/README.md
=> Fix Brats18 readme typo [skip ci]

nvflare/private/fed/app/fl_conf.py
Fixes # .
Currently connection security value is stored to the databus when creating the client engine. However, CellPipe might be created during job config file processing (when creating components), which needs the value of conn security. However, at this time the client engine has not been created, hence the value is not available.
This PR fixes the problem by saving the conn security value to the databus in the "start_config" method of the CP's config, which happens before component creation. This guarantees that the value is available when CellPipe is created.
=> [2.5] Fix conn sec saving

nvflare/app_opt/flower/applet.py
Fixes # .
Since the supernode is started with its current working directory set to the client app dir, if the custom directory is not an absolute path, it needs to be passed relative to the app dir.
=> [2.5] Fix flower app path

nvflare/app_opt/flower/applet.py
Fixes #3169.
Since the supernode is started with its current working directory set to the client app dir, if the custom directory is not an absolute path, it needs to be passed relative to the app dir.
=> Fix custom dir path passed to Flower client supernode subprocess

nvflare/job_config/script_runner.py
The original hardcode 0 has a problem, if the external user code has an exception and the program will never return.
Our FL client job process (running LauncherExecutor) will never ends.
By using the default heartbeat_timeout value, if the FL client job process does not receive the heartbeat from the user process for heartbeat_timeout seconds, then we will consider it dead.
=> [2.5] Remove hardcode heartbeat_timeout 0

nvflare/app_opt/pt/decomposers.py
Cherry-picked support for BF16 datatype in TensorDecomposer from main.
=> [2.5] Cherry-picking BF16 support in FOBS

nvflare/app_common/launchers/subprocess_launcher.py
This PR reads the subprocess stdout as binary data. It addresses the subprocess launcher deadlock issue when the output is not line-oriented or binary.
=> [2.5] Fix subprocess read deadlock

examples/hello-world/ml-to-fl/pt/src/cifar10_lightning_ddp_fl.py, examples/hello-world/ml-to-fl/pt/src/cifar10_lightning_ddp_original.py, examples/hello-world/ml-to-fl/pt/src/cifar10_lightning_fl.py, examples/hello-world/ml-to-fl/pt/src/cifar10_lightning_original.py, examples/hello-world/ml-to-fl/pt/src/lit_net.py
When using the external process (SubprocessLauncher)
(1) In the last round the CJ will consider the job finish right after "fit" is called, thus the predict/test stage of external program will be killed in the middle
(2) the standalone lightning training script (`examples/hello-world/ml-to-fl/pt/src/cifar10_lightning_original.py`) is not working because of import (`from src.net import Net`)
- Remove the test/predict stage as it is not required
- Move the Net definition inside the lit_net.py file so import will not be an issue when running standalone lightning training
=> [2.5] Remove test/predict in lightning fl example

nvflare/app_common/launchers/subprocess_launcher.py
This fixes the subprocess launcher deadlock issue caused by readline.
It's cherry-picked from 2.5 branch.
=> Fixed the subprocess read deadlock

nvflare/apis/fl_constant.py, nvflare/private/fed/client/client_req_processors.py, nvflare/private/fed/client/training_cmds.py, nvflare/private/fed/server/job_cmds.py, nvflare/security/security.py
Fixes # .
This PR removes the obsolete start_app command. It is cherry-picked from commits of this PR: https://github.com/NVIDIA/NVFlare/pull/3313
=> [2.6] Remove start_app command

nvflare/app_opt/flower/applet.py, nvflare/app_opt/flower/controller.py
Fixes # .
Currently every time a message is received from Flower client causes a status query to superlink. Though this gives us the most accurate status info, unfortunately frequent status query can drastically slow down Flower's training process.
To control query frequency, this PR adds the "superlink_min_query_interval" config arg to FlowerController.  The SJ will do status query no more frequent than the specified interval.
=> [2.6] Reduce flower status query frequency

nvflare/app_opt/tf/scaffold.py
Fixes # .
TF scaffold rm numerics check as it causes compatibility issues with CUDA training in the scaffold example. This option is only relevant for debugging and can be safely removed.
=> [2.6] TF scaffold rm numerics check

nvflare/app_opt/tf/scaffold.py
Fixes #3232.
TF scaffold rm numerics check as it causes compatibility issues with CUDA training in the scaffold example. This option is only relevant for debugging and can be safely removed.
=> TF scaffold rm numerics check

nvflare/fuel/utils/wfconf.py
Fixes # .
Currently we do var substitution for all string type arg values. If the value happens to contain curly brackets but content within the brackets is not a valid var name (as reported in https://github.com/NVIDIA/NVFlare/issues/3229), the substitution will fail.
This PR adds protection to the substitution: if it fails, the original value will be returned.
=> [2.6] Fix var substitution in config parsing

nvflare/lighter/impl/azure.py
Fixes # .
Added missing replacement dict when generating start script with templates.
=> Fix azure start script generation in azure provision builder

nvflare/fuel/utils/wfconf.py
Fixes # .
Currently we do var substitution for all string type arg values. If the value happens to contain curly brackets but content within the brackets is not a valid var name (as reported in https://github.com/NVIDIA/NVFlare/issues/3229), the substitution will fail.
This PR adds protection to the substitution: if it fails, the original value will be returned.
=> Fix var substitution in config parsing

nvflare/cli.py
Fixes #3296
nvflare cli doesn't exit with none-zero code when subcommands raises exceptions.  This fixes such issue.
=> [2.5] Add exit code when nvflare provision encounter exception

nvflare/app_common/tie/process_mgr.py
While testing the TIE + Flower job, I discovered that if the process outputs to STDERR, any attempt to use STDOUT for retrieving results fails when the two streams are mixed together.
For example:
https://github.com/NVIDIA/NVFlare/blob/2.6/nvflare/app_opt/flower/applet.py#L225-L232
This PR separates STDERR from STDOUT to prevent mixing the two streams and ensure proper handling of the output.
Fixes # .
=> Cherry-pick Separate STDERR from STDOUT in tie (#3346)

nvflare/fuel/utils/fobs/datum.py, nvflare/fuel/utils/fobs/fobs.py, tests/unit_test/apis/utils/decomposers/flare_decomposers_test.py, tests/unit_test/app_common/decomposers/common_decomposers_test.py
Changed FOBS to use externalizer to handle larger than 4GB items in dict.
Cherry-picked from 2.6.
=> Use externalizer in FOBS

nvflare/fuel/f3/streaming/tools/README.md, nvflare/private/stream_runner.py, tests/tools/file_streaming/app/config/config_fed_client.json, tests/tools/file_streaming/app/custom/file_streaming.py
1. Added timeout parameter to the file streaming testing job
2. Fixed some problem in error handling in streaming code.
3. Cleaned up README to remove reference to file_sender.py/file_receiver.py
=> [2.6] Added error handling in file streaming tool

nvflare/app_common/ccwf/cse_server_ctl.py
Fixes # .
This PR fixes a bug in prep_model task assignment: the min_responses should be number of targets, instead of 1.
=> [2.6] Fix CSE Prep Model Task

nvflare/lighter/constants.py, nvflare/lighter/impl/static_file.py
Fixes # .
Fixed the missed "ha_mode" replacement when generating start.sh in server's startup kit.
Added the missing system_info.ipynb to the admin startup kit generation.
=> [2.6] Fix server start.sh arg replacement and add system_info.ipynb

nvflare/app_opt/flower/applet.py, nvflare/app_opt/flower/controller.py
Cherry-pick of #3343
Currently every time a message is received from Flower client causes a status query to superlink. Though this gives us the most accurate status info, unfortunately frequent status query can drastically slow down Flower's training process.
To control query frequency, this PR adds the
"superlink_min_query_interval" config arg to FlowerController. The SJ will do status query no more frequent than the specified interval.
Fixes # .
=> Cherry-pick of [2.6] Reduce flower status query frequency (#3343)

nvflare/private/fed/client/client_run_manager.py
Fixes # .
The "client" arg of ClientRunManager is set to None when used in Simulator. This PR handles this case and determines the FQSN and is_leaf by using default values.
=> [2.6] Handle None client in ClientRunManager

tests/tools/file_streaming/app/custom/controller.py, tests/tools/file_streaming/app/custom/file_streaming.py
1. Added a 5 seconds delay in the controller in file streaming testing job to avoid client timeout at the end.
2. Added support for multiple clients.
=> Added delay to shutdown controller

nvflare/app_opt/xgboost/histogram_based_v2/aggr.py, nvflare/app_opt/xgboost/histogram_based_v2/sec/processor_data_converter.py
Ignore -1 slot number in the bin assignment returned from XGBoost during aggregation in Python.
=> [2.6] Ingore -1 in slot numbers

examples/advanced/cifar10/cifar10-real-world/jobs/cifar10_fedavg_stream_tb/cifar10_fedavg_stream_tb/config/config_fed_client.json, examples/advanced/cifar10/pt/learners/cifar10_learner.py, examples/advanced/cifar10/pt/learners/cifar10_model_learner.py, examples/advanced/cifar10/pt/learners/cifar10_scaffold_learner.py, examples/advanced/cifar10/pt/learners/cifar10_scaffold_model_learner.py
The AnalyticsSender now is a lower level thing and does not have add_scalar.
The add_scalar functionality was moved already into TBWriter.
So we should use TBWriter instead
- Update CIFAR10 example to use TBWriter
=> [2.6] Update CIFAR10 to use TBWriter

examples/advanced/cifar10/cifar10-real-world/jobs/cifar10_fedavg_stream_tb/cifar10_fedavg_stream_tb/config/config_fed_client.json, examples/advanced/cifar10/pt/learners/cifar10_learner.py, examples/advanced/cifar10/pt/learners/cifar10_model_learner.py, examples/advanced/cifar10/pt/learners/cifar10_scaffold_learner.py, examples/advanced/cifar10/pt/learners/cifar10_scaffold_model_learner.py
The AnalyticsSender now is a lower level thing and does not have add_scalar.
The add_scalar functionality was moved already into TBWriter. So we should use TBWriter instead
- Update CIFAR10 example to use TBWriter
Fixes # .
=> Cherry-pick Update CIFAR10 to use TBWriter (#3449)

examples/advanced/edge/jobs/hello_async/app/config/config_fed_client.json, examples/advanced/edge/jobs/hello_async/app/config/config_fed_server.json, examples/advanced/edge/jobs/hello_async/meta.json, examples/advanced/edge/jobs/hello_sync/app/config/config_fed_client.json, examples/advanced/edge/jobs/hello_sync/app/config/config_fed_server.json, examples/advanced/edge/jobs/hello_sync/meta.json, nvflare/edge/assessors/async_num.py, nvflare/edge/executors/edge_model_executor.py, nvflare/edge/updaters/emd.py
Fixes # .
Sync (without sampling) is a special case to async scheme under the following settings:
Assuming we have 4 leaf nodes, and the total device is 4N, then to have a synchronized scheme with all devices participating in a synchronized manner, we set
- Client-side, num_devices = N 
- Server-side, num_updates_for_model = device_selection_size = min_hole_to_fill = 4N
- Server-side, set device_reuse to True
In this way, server will have to wait for all devices to report (num_updates_for_model) to cast a new model, and have to wait for the entire list become empty (min_hole_to_fill) to fill, and the same device will get new model (device_reuse) for local training
To further simulate sync with over-sampling, we can set
- Server-side, num_updates_for_model = min_hole_to_fill = 4N, …
=> Edge - add hello_async and hello_sync schemes 

nvflare/private/fed/app/simulator/simulator_runner.py
This small PR resolves the `logging` deprecation warnings:
```python
/home/runner/work/NVFlare/NVFlare/nvflare/private/fed/app/simulator/simulator_runner.py:228: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
=> Fix logging deprecation warnings

README.md, docs/examples/hello_fedavg_numpy.rst, docs/examples/hello_pt_job_api.rst, docs/examples/hello_tf_job_api.rst, docs/getting_started.rst, docs/index.rst, docs/installation.rst, docs/quickstart.rst, docs/real_world_fl.rst, docs/real_world_fl/cloud_deployment.rst, docs/real_world_fl/containerized_deployment.rst, docs/resources/Dockerfile, pyproject.toml, setup.cfg, setup.py, tests/unit_test/app_common/workflow/cyclic_ctl_test.py
1. Previous Quickstart contains Installation, Deployment, actual quickstart (the run of one example), introduction to simulator, introduction to POC, which is too much information
2. Typos in our documentation
3. python 3.8 is not supported anymore
- Split the previous Quickstart content into Installation, Getting Started, Containerized Deployment, and Quickstart
- Fix typos
- Remove python3.8
=> [2.6] Update documentation

examples/advanced/distributed_optimization/requirements.txt, examples/advanced/llm_hf/requirements.txt, examples/hello-world/hello-flower/flwr-pt-tb/pyproject.toml, examples/hello-world/hello-flower/flwr-pt/pyproject.toml, examples/tutorials/self-paced-training/part-4_advanced_federated_learning/chapter-8_federated_LLM_training/08.2_llm_sft/requirements.txt, examples/tutorials/self-paced-training/part-4_advanced_federated_learning/chapter-8_federated_LLM_training/08.3_llm_peft/requirements.txt
Our code should be able to work with any torch greater than 2.0 or something, so there's no need to ping to a specific version.
remove torch version pings
=> Remove torch ping version

nvflare/lighter/spec.py
Revert the wrong change of Builder spec in https://github.com/NVIDIA/NVFlare/pull/3478
- Revert changes
- Add docstring
=> Revert Builder spec change

tests/integration_test/data/projects/authz.yml, tests/integration_test/data/projects/dummy.yml
Remove template builder in tests as they are deprecated.
=> Remove template builder in tests

integration/nemo/examples/peft/peft.ipynb, integration/nemo/examples/prompt_learning/prompt_learning.ipynb, integration/nemo/examples/prompt_learning/prompt_learning_20B.md
Fixes # .
Huggingface links are broken. Found the original data link.
=> Fix financial phrase bank dataset links

nvflare/lighter/impl/cert.py
Fixes # .
Server Name is used as CN of the cert. But the CN cannot exceed 63 chars. So we have to truncate it to make the cert.
Server Name also serves as the identity of the server for all clients to verify, and it must match the CN in the server's cert.
Server Name is also the default host name (unless default host is explicitly specified) for clients to connect to. Truncated name won't be a valid host name.
We have to accommodate all these factors:
- We truncate the server name and use it for both name and subject of the server. This will satisfy CN requirement of the cert, and will satisfy server identity validation by clients.
- We check whether the DEFAULT_HOST property is explicitly specified in the server. If not, we explicitly set it to the original name.
=> Support long server name

web/src/components/hero.astro
Fixes # .
Adds link to [summer of code](https://developer.nvidia.com/flare-summer-of-code-2025) website. Preview looks like this
=> [Website] add summer of code banner[skip ci]

nvflare/fuel/utils/fobs/decomposers/via_file.py
Fixes # .
Msg root based sharing of serialization results is flawed. The message payload could be changed within the life of a task. The changes could be caused by before_task_sent_cb, or by filters. Before we find a solution to automatically detect and handle payload changes, we will disable the msg root based sharing.
=> Disable msg root processing

nvflare/fuel/hci/client/api.py
Fixes # .
This PR adds validation of login timeout value to the admin API's connect call.  If a value is not specified, it will use the default value defined in admin config.
=> Fix admin login timeout default

nvflare/job_config/api.py, nvflare/job_config/fed_job_config.py
Fixes # .
Currently, if a module is not in NVFLARE package, the Job API applies the magic of determining its class path and copying the source into the "custom" folder of generated job. When the module is in an app package that will be included in the final python env (e.g. docker container), then this magic is not desired. In fact, including the source code could cause confusion when resolving class path.
This PR implements a simple solution by letting the Job API user specify app packages to be excluded from this behavior.
If the package name of a module is in the specified app package list, then the magic won't be applied.
=> Support app packages in job API

nvflare/edge/executors/hug.py
This PR fixes an issue where `ETEdgeModelExecutor` (and other edge executors using `HierarchicalUpdateGatherer`) would log spurious timeout errors during normal job completion. The timeout occurs due to a race condition between task completion and final parent update attempts.
When a federated learning job completes successfully, the following sequence can occur:
1. Parent sends `end_task` signal to child
2. Child attempts one final update to parent  
3. Parent has already finished and no longer accepts updates
4. Child receives `TIMEOUT` return code and logs it as an ERROR
This creates confusing error logs like:
```
ETEdgeModelExecutor - ERROR - error updating parent None: TIMEOUT, self.update_timeout=1000.0
```
Even though the job completed successfully, these timeout errors suggest …
=> Update HUG timeout error msg

nvflare/app_common/ccwf/client_ctl.py, nvflare/app_common/ccwf/cse_client_ctl.py, nvflare/app_common/ccwf/swarm_client_ctl.py
Fixes # .
In order to reduce peak memory usage, this PR adds garbage collection after heavy activities such as client training and aggregation.
=> Add active garbage collection in CCWF

nvflare/edge/executors/edge_model_executor.py, nvflare/edge/mud.py
Fixes # .
The PT model needs to be converted to ET format before sending to a device. There are two issues with current implementation:
- The model is converted every time a new request is received from the device, even though the conversion is the same for all devices.
- The conversion is not done within a lock. When multiple devices ask for the model at the same time, the multiple conversions happen concurrently, which could break the integrity of the converted result.
This PR fixes these issues:
- The model is converted only once. Converted result is cached for later reuse.
- The check-and-convert process is placed within a lock.
=> Convert ET model once for each task

nvflare/lighter/edge_project.yml
EdgeBuilder is required for the real deployment
EdgeBuilder is required for the real deployment
=> Fix edge project default

nvflare/job_config/api.py, nvflare/job_config/stats_job.py, nvflare/recipe/fedstats.py
Fixes # .
Job name wasn't correctly propagated in StatsJob.
=> Fix job name in StatsJob

nvflare/app_common/statistics/statistics_config_utils.py, nvflare/app_opt/statistics/quantile_stats.py
In some cases, the quantile is configured but only for selected features. We should be able to handle such cases
=> handle cases where quantile config is un-defined for certain features 

nvflare/app_common/widgets/decomposer_reg.py
Fixes # .
Due to security concern raised by NVIDIA security team, we had to take out "auto decomposer registration" function from FOBS.  The application will have to explicitly register custom decomposers.
This PR adds a DecomposerRegister widget that can be used to configure and load any custom decomposers.
To use it, simply include it as a component in config_fed_server.json and/or config_fed_client.json.
"components": [
{
"id": "decomposer_reg",
"path": "path.to.custom.decomposer",
"args": {
"classes": ["nvflare.app_opt.pt.decomposers.TensorDecomposer"]
}
}
]
=> Add decomposer register

nvflare/edge/simulation/feg_api.py
Fixes # .
Added missing job_name in the getJob call. This is to fix bug https://nvbugspro.nvidia.com/bug/5433909.
=> Fix missing job name in edge simulation feg_api

nvflare/fuel/f3/mpm.py
Fixes QA bug FLARE-2599
Increases the grace period so the shutdown error msg won't show up easily, as suggested by QA
=> Increase the grace period so error msg won't show up

nvflare/app_opt/confidential_computing/snp_authorizer.py, nvflare/lighter/cc_provision/impl/onprem_packager.py
Sometimes the AMD server attestation failed because of network instability or rate limiting some transient errors.
We added retry in this PR.
We added retry in this PR.
=> Enhance snp with retry
