examples/hello-numpy-cross-val/custom/np_trainer.py
examples/hello-numpy-cross-val/custom/np_validator.py
examples/hello-numpy-sag/custom/np_trainer.py
examples/hello-pt/custom/cifar10trainer.py
examples/hello-pt/custom/cifar10validator.py

- Cleanup hello-numpy, hello-cross-val and hello-pt examples.

Cleanup examples

---

nvflare/app_common/pt/tb_receiver.py

- Add docstring to nvflare/app_common/pt/tb_receiver.py

Add docstrings to TB receiver

---

nvflare/app_common/widgets/streaming.py

- Add docstring to nvflare/app_common/widgets/streaming.py

Add docstring to streaming widget

---

nvflare/app_common/widgets/convert_to_fed_event.py

- Add docstring to nvflare/app_common/widgets/convert_to_fed_event.py

Add docstrings to ConvertToFedEvent widget

---

nvflare/widgets/widget.py

- Add docstring to nvflare/widgets/widget.py

Add docstring to widget

---

examples/hello-monai/custom/monai_trainer.py
examples/hello-monai/custom/train_configer.py

This PR enhances the monai example by:
1. enable the downloaded dataset to be accessed via different runs.
2. remove useless comments.
3. use latest MONAI API for `AsDiscreted`.
4. clean the code format with the help of `flake8`, `isort` and `black`.
The changes have been tested locally.

enhance monai example

---

nvflare/widgets/info_collector.py

- Add docstring to nvflare/widgets/info_collector.py

Add dostring to info_collector widget

---

nvflare/app_common/widgets/streaming.py
test/app_testing/test_apps/tb_streaming/config/config_fed_client.json
test/app_testing/test_apps/tb_streaming/config/config_fed_server.json
test/app_testing/test_apps/tb_streaming/custom/custom_executor.py

- Update streaming widget to use function 
- Update tb_streaming app in test_apps

Update streaming widget to use just function but not component

---

nvflare/private/fed/server/sys_cmd.py

Fixed the admin command "sys_info client" error.

Fixed the sys_info client error

---

nvflare/apis/analytix.py
nvflare/app_common/widgets/streaming.py
test/test_analytix.py
test/test_streaming.py

Fixes #52 
- Add error checks
- Fix typos
- Add a boolean self._end in AnalyticsReceiver to indicate if END_RUN event has been fired already

Fix #52 streaming errors

---

nvflare/apis/event_type.py
nvflare/apis/fl_component.py
nvflare/widgets/info_collector.py

Fixes #53 
- Add log_critical to FLComponent
- Add docstrings to FLComponent

Add log critical to FLComponent and update docstrings

---

examples/cifar10/README.md
examples/cifar10/figs/plot_tensorboard_events.py
examples/cifar10/pt/trainers/cifar10_trainer.py
examples/cifar10/run_fl.py
examples/cifar10/run_poc.sh

Some minor updates to CIFAR-10 example.

some minor updates to cifar10 example

---

examples/README.md
examples/hello-cyclic/README.md
examples/hello-monai/README.md
examples/hello-numpy-cross-val/README.md
examples/hello-numpy-sag/README.md
examples/hello-pt/README.md
examples/hello-tf2/README.md

fix spelling
SAG readme
add example readmes

add example README files

---

test/app_testing/test_apps/tb_streaming/custom/custom_controller.py
test/app_testing/test_apps/tb_streaming/custom/custom_executor.py
test/app_testing/test_apps/validators/tb_result_validator.py

Update TensorBoard streaming app tests

---

test/app_testing/test_apps/validators/tb_result_validator.py

Fix TensorBoard streaming app test's result validator

---

docs/installation.rst

update the statement about Python version compatibility

---

nvflare/apis/impl/controller.py
nvflare/apis/impl/seq_relay_manager.py
nvflare/apis/utils/format_check.py
nvflare/app_common/aggregators/accumulate_model_aggregator.py
nvflare/app_common/aggregators/intime_accumulate_model_aggregator.py
nvflare/app_common/filters/percentile_privacy.py
nvflare/app_common/homomorphic_encryption/he_intime_accumulate_model_aggregator.py
nvflare/app_common/pt/pt_fedopt.py
nvflare/app_common/workflows/cyclic_ctl.py
nvflare/lighter/poc.py
nvflare/lighter/provision.py
setup.py
test/app_testing/site_launcher.py
test/app_testing/test_runner.py

Related to #78.
- Remove "=" in f-string
- Remove walrus operator

Remove = in format string and remove walrus operator for supporting Python 3.7

---

nvflare/lighter/impl/master_template.yml

This PR will close #91.
Signed-off-by: Isaac Yang <isaacy@nvidia.com>

Remove multi_gpu in provision template

---

CODEOWNERS
CODE_OF_CONDUCT.md
CONTRIBUTING.md

- IsaacYangSLA, yhwen owners for repo
- madil90, YuanTingHsieh owners for test

Add codeowners

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Update code of conduct and contributing guide

---

nvflare/lighter/impl/master_template.yml
nvflare/poc/client/startup/start.sh
nvflare/poc/client/startup/sub_start.sh
nvflare/poc/server/startup/start.sh
nvflare/poc/server/startup/sub_start.sh

This will close #98 .
Signed-off-by: Isaac Yang <isaacy@nvidia.com>

Yield CUDA_VISIBLE_DEVICES settings to users

---

nvflare/lighter/impl/static_file.py
nvflare/lighter/project.yml

This will close #105.
Signed-off-by: Isaac Yang <isaacy@nvidia.com>

Add option of app_validator

---

nvflare/private/fed/app/fl_conf.py
nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/app/trainers/server_deployer.py

To fix the missing config_validator parsing.

Added the missing config_validator parsing.

---

examples/README.md
examples/cifar10/README.md
examples/cifar10/configs/cifar10_fedavg_stream_tb/config/config_fed_client.json
examples/cifar10/configs/cifar10_fedavg_stream_tb/config/config_fed_server.json
examples/cifar10/pt/learners/cifar10_learner.py
examples/cifar10/run_experiments.sh

Add streaming tensorboard support to CIFAR-10 example

---

examples/cifar10/README.md
examples/cifar10/configs/cifar10_fedavg_stream_tb/config/config_fed_client.json
examples/cifar10/pt/learners/cifar10_learner.py

use AnalyticsSender for TensorBoard metric streaming.
Closes #112

Enhance tb streaming

---

examples/hello-monai/custom/monai_trainer.py
nvflare/lighter/project.yml
nvflare/private/fed/app/client/client_train.py
nvflare/private/fed/app/client/worker_process.py
nvflare/private/fed/app/server/server_train.py

Change NVFlare to NVIDIA Flare

---

.gitignore
docs/user_guide/application.rst
docs/user_guide/provisioning_tool.rst
nvflare/lighter/impl/auth_policy.py
nvflare/lighter/impl/cert.py
nvflare/lighter/impl/he.py
nvflare/lighter/impl/signature.py
nvflare/lighter/impl/static_file.py
nvflare/lighter/impl/template.py
nvflare/lighter/impl/workspace.py

Fix workflow by removing apidocs from gitignore so it can be checked in with the built docs into docs branch automatically, and add docstring documentation for provisioning builders and link to them in docs.

Fix workflow for automatically building docs, improve docs

---

nvflare/apis/utils/local_logger.py
nvflare/app_common/widgets/streaming.py
nvflare/private/fed/client/client_runner.py

codes in apis folder should not depend on app_common folder.
That is why we need this change.

Refactor LocalLogger to remove the dependency on LogSender.

---

nvflare/private/fed/app/client/client_train.py
nvflare/private/fed/app/client/worker_process.py
nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/client/client_engine.py
nvflare/private/fed/client/client_executor.py
nvflare/private/fed/server/server_engine.py

To remove the "/tmp/fl_server" and "/tmp/fl/uid" workspace dependency for FL server and client.

Removed the use of tmp folders for the server and client.

---

nvflare/apis/utils/local_logger.py
nvflare/app_common/widgets/log_streaming.py
nvflare/app_common/widgets/streaming.py
test/app_testing/test_apps/tb_streaming/custom/custom_executor.py
test/test_streaming.py

Fix #134 
- Rename log_receiver.py to log_streaming.py
- Move LogSender into log_streaming.py and rename to LogAnalyticsSender
- Update streaming.py docstrings and removed unused codes
- Update unit tests

Update docstrings and clean up streaming

---

nvflare/__init__.py
nvflare/lighter/poc.py
setup.py

Fix poc permission

---

nvflare/app_common/shareablegenerators/full_model_shareable_generator.py

Fix issue 156 on numpy default casting

---

docs/faq.rst
docs/quickstart.rst
docs/user_guide/application.rst

Adds a bit to the documentation to help users with specific cases encountered. Improves linking so the information is more accessible.
Closes #157 and #149

Add to the documentation to clarify about specific cases

---

nvflare/private/fed/server/admin.py
nvflare/private/fed/server/client_manager.py
nvflare/private/fed/server/cmd_utils.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/info_coll_cmd.py
nvflare/private/fed/server/result_processor.py
nvflare/private/fed/server/run_manager.py
nvflare/private/fed/server/server_aux_runner.py
nvflare/private/fed/server/server_cmd_modules.py
nvflare/private/fed/server/server_engine.py
nvflare/private/fed/server/server_engine_internal_spec.py
nvflare/private/fed/server/server_json_config.py
nvflare/private/fed/server/server_runner.py
nvflare/private/fed/server/shell_cmd.py
nvflare/private/fed/server/sys_cmd.py
nvflare/private/fed/server/training_cmds.py

Fix #173 
- Fix docstrings style issue
- Remove unused codes

Fix private/fed/server docstrings

---

nvflare/apis/analytix.py
nvflare/apis/app_validation.py
nvflare/apis/aux_spec.py
nvflare/apis/client.py
nvflare/apis/client_engine_spec.py
nvflare/apis/controller_spec.py
nvflare/apis/dxo.py
nvflare/apis/event_type.py
nvflare/apis/filter.py
nvflare/apis/fl_component.py
nvflare/apis/fl_constant.py
nvflare/apis/fl_context.py
nvflare/apis/fl_exception.py
nvflare/apis/impl/any_relay_manager.py
nvflare/apis/impl/bcast_manager.py
nvflare/apis/impl/controller.py
nvflare/apis/impl/send_manager.py
nvflare/apis/impl/seq_relay_manager.py
nvflare/apis/impl/task_manager.py
nvflare/apis/responder.py
nvflare/apis/server_engine_spec.py
nvflare/apis/shareable.py
nvflare/apis/signal.py
nvflare/apis/utils/common_utils.py
nvflare/apis/workspace.py
nvflare/widgets/comp_caller.py
nvflare/widgets/fed_event.py
nvflare/widgets/info_collector.py
nvflare/widgets/widget.py

- fix pydocstyle issues in apis and widgets

improve docstrings for apis and widgets

---

nvflare/fuel/hci/client/api_spec.py

Fix show_stats command

---

nvflare/app_common/filters/exclude_vars.py
nvflare/app_common/filters/percentile_privacy.py
nvflare/app_common/filters/svt_privacy.py
nvflare/app_common/handlers/intime_model_selection_handler.py
nvflare/app_common/pt/pt_file_model_locator.py
nvflare/fuel/hci/client/cli.py
runtest.sh
setup.cfg

Fix all issues of isort/black after including nvflare/private folder

---

nvflare/private/fed/server/server_engine.py
nvflare/private/fed/server/training_cmds.py

Fix admin shutdown client issue

---

nvflare/fuel/hci/client/api.py
nvflare/fuel/hci/client/api_status.py
nvflare/fuel/hci/client/cli.py
nvflare/fuel/hci/client/fl_admin_api.py
nvflare/fuel/hci/server/login.py
nvflare/fuel/hci/server/sess.py
nvflare/private/fed/server/admin.py

- Admin client now automatically logouts after timeout with needing a user input

Quit admin after timeout dev

---

examples/cifar10/figs/plot_tensorboard_events.py

Update cifar10 plotting script

---

nvflare/private/fed/app/server/server_train.py

Hi :)
Here is the PR to fix the server startup folder not being correctly propagated
fixes #239 
Thanks!

Fix server startup path propogation

---

nvflare/lighter/impl/master_template.yml

Minor changes to master-template.yml to support older versions of bash

---

nvflare/fuel/hci/tools/admin.py
nvflare/poc/admin/startup/fed_admin.json
nvflare/poc/admin/startup/fed_admin_HA.json
nvflare/poc/admin/startup/fl_admin.sh

Add fed_admin.json and fed_admin_HA.json in poc directory to work with new admin.py script for launching the admin client with the json config.

Change fl_admin launch script to use fed_admin.json config for poc mode

---

nvflare/app_common/aggregators/dxo_aggregator.py
nvflare/app_common/aggregators/intime_accumulate_model_aggregator.py
nvflare/app_common/aggregators/weighted_aggregation_helper.py
test/unit_test/app_common/test_accumulate_weighted_aggregator.py
test/unit_test/app_common/test_in_time_accumulate_weighted_aggregator.py

Fix #182
Fix #248 
- Added new test cases
- Fixed logic error in InTimeAccumulateWeightedAggregator
- Updated docstrings

Fix intime accumulated aggregators and add tests

---

nvflare/ha/overseer/worker.py
runtest.sh

- Add license
- Exclude proto folder

Fix license issue

---

nvflare/app_common/homomorphic_encryption/he_intime_accumulate_model_aggregator.py

Bugfix HE aggregator

---

nvflare/fuel/hci/conn.py
nvflare/fuel/hci/server/hci.py

1. Message size is limited to 0.5 GB
2. Connection is timed out after idling for 10 seconds
3. Number of admin connections is limited to 128

Fix #258 by adding 3 measures against DoS attacks

---

nvflare/fuel/hci/server/hci.py

Fix a small isort issue by #295

Fix isort issue

---

.github/workflows/premerge.yml
nvflare/apis/overseer_spec.py
nvflare/ha/overseer/overseer.py
nvflare/ha/overseer_agent_app.py
nvflare/lighter/impl/auth_policy.py
nvflare/lighter/impl/cert.py
nvflare/lighter/impl/he.py
nvflare/lighter/project.yml
requirements-min.txt
setup.py

Update cert building process
Update dependencies

Add props to SP dataclass

---

examples/federated_analysis/configs/fed_analysis/config/config_fed_client.json
examples/federated_analysis/configs/fed_analysis/config/config_fed_server.json
examples/federated_analysis/configs/fed_analysis/custom/analysis_constants.py
examples/federated_analysis/configs/fed_analysis/custom/analysis_controller.py
examples/federated_analysis/configs/fed_analysis/custom/analysis_executor.py

make task name configurable

---

nvflare/fuel/hci/client/api.py
nvflare/fuel/hci/client/cli.py
nvflare/fuel/hci/client/file_transfer.py
nvflare/ha/ha_admin_cmds.py
nvflare/ha/overseer/utils.py

Refactor overseer_agent to AdminAPI from cli, so it can also be used by the FLAdminAPI. For HA it is now required to enable auto_login, since the admin client needs to login after switching to a new SP.

Refactor overseer_agent to AdminAPI from cli, add ha commands

---

nvflare/lighter/poc.py

Enable poc command in 'pip install -e .' environment.

---

nvflare/app_common/homomorphic_encryption/he_model_decryptor.py
nvflare/app_common/homomorphic_encryption/he_model_shareable_generator.py

support data kind WEIGHTS in HE

---

nvflare/private/fed/client/communicator.py
nvflare/private/fed/utils/fed_utils.py

Fix #311
- Fix typos
- Remove unused codes

Clean up communicator

---

nvflare/private/event.py
nvflare/widgets/fed_event.py

Fix log exception bug

---

nvflare/apis/fl_component.py

Fix FLComponent docstring typo

---

examples/cifar10/configs/cifar10_fedavg_stream_tb/config/config_fed_client.json
examples/hello-pt-tb/config/config_fed_client.json
nvflare/app_common/app_event_type.py
nvflare/app_common/widgets/streaming.py

Add event_type to AnalyticsSender

---

nvflare/app_common/homomorphic_encryption/he_intime_accumulate_model_aggregator.py
nvflare/app_common/homomorphic_encryption/he_model_decryptor.py
nvflare/app_common/homomorphic_encryption/he_model_shareable_generator.py

Fix he issues

---

nvflare/app_common/storages/filesystem_storage.py
nvflare/app_common/storages/s3_storage.py
test/unit_test/app_common/test_storage.py

- add implementation-agnostic storage tests
- currently works for FilesystemStorage, in the future will try to automate the setup of an S3 compatible Minio bucket

add storage tests

---

nvflare/app_common/filters/svt_privacy.py

Fixes https://github.com/NVIDIA/NVFlare/issues/343

343 fixes svt_privacy

---

nvflare/lighter/impl/static_file.py

Improve fed_(server|client).json readability

---

nvflare/apis/storage.py
nvflare/apis/utils/format_check.py
nvflare/app_common/storages/filesystem_storage.py
nvflare/app_common/storages/s3_storage.py
requirements-dev.txt
runtest.sh
test/unit_test/app_common/test_storage.py

- add automated S3 storage test using local minio server
- update storage spec and docstrings
- move validate args to utils

Storage improvements

---

nvflare/app_common/filters/svt_privacy.py

Fixes https://github.com/NVIDIA/NVFlare/issues/343

343 fixes svt_privacy (#348)

---

nvflare/fuel/sec/security_content_service.py
nvflare/lighter/impl/signature.py
nvflare/lighter/utils.py

Remove pickle dump/load calls from handling signature file

---

nvflare/apis/impl/study_manager.py

study manager

---

nvflare/lighter/study.py

Add study config user app

---

nvflare/apis/impl/study_manager.py
nvflare/apis/study_manager_spec.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_command_agent.py
nvflare/private/fed/server/server_commands.py
nvflare/private/fed/server/server_engine.py

Fix import issues

---

.github/workflows/build_docs.yml
.github/workflows/premerge.yml
requirements-dev.txt
test/app_testing/run_app_tests.sh
test/app_testing/run_example_tests.sh
test/app_testing/validators/pt_model_validator.py

Fix main ci

---

nvflare/ha/overseer/utils.py
nvflare/lighter/study.py

Fixes #379 .
Thanks @nvkevlu for spotting other places using yaml.load

Fix some uncaught yaml loader codes.  Replace them with safe_load

---

nvflare/ha/overseer/mem_store.py
nvflare/ha/overseer/overseer.py
nvflare/ha/overseer/redis_store.py
nvflare/ha/overseer/sql_store.py
nvflare/ha/overseer/utils.py

Remove refresh api as it wipes out all records.

---

nvflare/apis/impl/study_manager.py
nvflare/apis/study_manager_spec.py

Fix a few issues on study manager

---

nvflare/fuel/sec/security_content_service.py
nvflare/lighter/impl/signature.py
nvflare/lighter/provision.py
nvflare/lighter/utils.py

Yaml loader known to unsafe.  Switch to yaml's safe_loader to reduce safety concerns. (#380)

Cherry-pick from dev-2.1 for yaml load issue

---

nvflare/apis/fl_constant.py
nvflare/apis/fl_context.py
nvflare/apis/fl_snapshot.py
nvflare/apis/server_engine_spec.py
nvflare/private/defs.py
nvflare/private/fed/app/client/worker_process.py
nvflare/private/fed/app/server/runner_process.py
nvflare/private/fed/client/admin_commands.py
nvflare/private/fed/client/client_engine.py
nvflare/private/fed/client/client_engine_internal_spec.py
nvflare/private/fed/client/client_executor.py
nvflare/private/fed/client/client_req_processors.py
nvflare/private/fed/client/client_run_manager.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/client/fed_client_base.py
nvflare/private/fed/client/info_coll_cmd.py
nvflare/private/fed/client/process_aux_cmd.py
nvflare/private/fed/client/training_cmds.py
nvflare/private/fed/server/cmd_utils.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/info_coll_cmd.py
nvflare/private/fed/server/server_aux_runner.py
nvflare/private/fed/server/server_commands.py
nvflare/private/fed/server/server_engine.py
nvflare/private/fed/server/server_engine_internal_spec.py
nvflare/private/fed/server/server_runner.py
nvflare/private/fed/server/training_cmds.py
nvflare/widgets/info_collector.py

Multi run support

---

nvflare/apis/impl/job_def_manager.py
nvflare/apis/job_def.py
nvflare/apis/job_def_manager_spec.py
nvflare/private/fed/server/job_cmds.py
nvflare/private/fed/server/server_engine.py

- Spec: list_all -> get_all_jobs
- Updated docstrings
- Fixed usages
- Fixed format issues in the files changed
Note that we might need to add try block around the store API calls because they might throw exceptions.

Fix job def and manager specs

---

nvflare/ha/overseer/overseer.py
nvflare/ha/overseer/utils.py

Include admin API (for privileged users only) to set system state

Add system state into overseer reply.

---

nvflare/apis/fl_constant.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/job_runner.py
nvflare/private/fed/server/server_engine.py
nvflare/private/fed/server/server_engine_internal_spec.py

- Add locking for the snapshot write.
- keeps the participating clients for the job in the snapshot.

Added snapshot write lock.

---

nvflare/lighter/impl/master_template.yml
nvflare/lighter/project.yml

Currently server required the following:
- "PYTHONPATH" set in environment variable
- "authorization" section

Add required section for server to start normally in provision (secure) mode

---

nvflare/private/fed/client/client_executor.py
nvflare/private/fed/server/server_engine.py

- Not all environment will set the PYTHONPATH environment variable

Add default env var PYTHONPATH if it is not set

---

nvflare/private/fed/server/job_runner.py

Enhance error message reporting

---

test/app_testing/run_app_tests.sh
test/app_testing/run_example_tests.sh

Download CIFAR10 dataset first to avoid race condition when multiple clients are running on the same machine

Download first to avoid race condition

---

nvflare/fuel/hci/client/api.py
nvflare/fuel/hci/client/fl_admin_api.py
nvflare/fuel/hci/client/fl_admin_api_runner.py
nvflare/fuel/hci/client/fl_admin_api_spec.py
nvflare/private/fed/server/job_cmds.py

- Update FLAdminAPI Runner to work with provisioned startup package and fed_admin.json instead of individual args
- add abort_job command into FLAdminAPI
- add auth for delete_job and clone_job

Add to FLAdminAPI, fix FLAdminAPI runner

---

nvflare/fuel/hci/client/cli.py

removes the need to enter the username password for poc mode

clean up experience with admin client for poc mode

---

nvflare/apis/server_engine_spec.py
nvflare/app_common/job_schedulers/__init__.py
nvflare/app_common/job_schedulers/job_scheduler.py
nvflare/lighter/project.yml
nvflare/poc/client/startup/fed_client.json
nvflare/poc/client/startup/fed_client_HA.json
nvflare/poc/server/startup/fed_server.json
nvflare/poc/server/startup/fed_server_HA.json
nvflare/private/fed/server/server_engine.py

- Update `ServerEngineSpec`
- Move `job_scheduler.py` into app_common

Move job scheduler from private to app_common

---

nvflare/private/fed/server/job_runner.py

Add log info for deploy and start the app to clients.

Enhance Job_runner logging.

---

nvflare/private/fed/server/training_cmds.py

Not allow shutdown while still jobs running.

Not allow shutdown while still jobs running.

---

nvflare/lighter/impl/he.py
nvflare/private/fed/server/job_runner.py

Fixed an out-of-date black codestyle check.

Fixed codestyle.

---

nvflare/fuel/hci/client/api.py
nvflare/lighter/impl/he.py
nvflare/private/fed/server/job_runner.py
tests/integration_test/admin_controller.py
tests/integration_test/apps/cross_val_one_client/config/config_fed_server.json
tests/integration_test/site_launcher.py
tests/integration_test/system_test.py
tests/integration_test/test_ha.yml
tests/integration_test/test_internal.yml
tests/integration_test/validators/cross_val_result_validator.py
tests/integration_test/validators/global_model_eval_validator.py
tests/integration_test/validators/sag_result_validator.py

- Clean up integration tests
- Remove "PIPE" to avoid "bad file descriptor" error

Fix integration tests

---

nvflare/fuel/hci/client/fl_admin_api.py
nvflare/fuel/hci/client/fl_admin_api_runner.py

update the FLAdminAPI runner to work better with 2.1, removing some of the features that are no longer relevant or working.

update FLAdminAPI runner

---

.github/workflows/premerge.yml
tests/integration_test/system_test.py
tests/integration_test/test_internal.yml

- Add back HA test cases into CI/CD

Add back HA test cases

---

nvflare/apis/storage.py
nvflare/app_common/storages/filesystem_storage.py
nvflare/app_common/storages/s3_storage.py
runtest.sh
tests/unit_test/app_common/storages/storage_test.py

- Remove `get_full_meta` from api
- Update docstrings
- Update unit tests

Update storage and tests

---

runtest.sh
tests/integration_test/apps/pt/config/config_fed_client.json
tests/integration_test/apps/pt/custom/cifar10trainer.py
tests/integration_test/apps/pt/custom/cifar10validator.py
tests/integration_test/system_test.py
tests/integration_test/test_internal.yml

- Add setup/teardown for each app/job test cases
- Move CIFAR data download outside of controller for this tests
- Make custom CIFAR trainer/validator data_path configurable

Update cifar10 data setup procedure in integration tests apps

---

nvflare/apis/fl_constant.py
nvflare/apis/job_scheduler_spec.py
nvflare/app_common/job_schedulers/job_scheduler.py
nvflare/private/fed/app/deployer/base_client_deployer.py
nvflare/private/fed/app/deployer/server_deployer.py
nvflare/private/fed/app/fl_conf.py
nvflare/private/fed/server/job_runner.py
nvflare/private/fed/server/server_engine.py

Changed the Job Scheduler to use event base add / remove job. Updated the JobSchedulerSpec to delete the remove_job().

Changed the job scheduler to use event.

---

nvflare/private/fed/app/deployer/server_deployer.py

- Remove unused codes
- Add instance variables in `__init__` method

Clean up server deployer

---

nvflare/private/fed/server/server_engine.py
nvflare/private/fed/server/server_engine_internal_spec.py

Clean up server engine internal spec

---

nvflare/private/fed/server/training_cmds.py

- Rename dest -> dst
- Remove unused codes

Clean up training cmds

---

nvflare/private/fed/server/server_runner.py

- Add more information in debugging logs

Clean up server runner

---

nvflare/private/fed/server/fed_server.py

- Remove unused statements
- Rename taskname -> task_name
- Rename dest -> dst

Clean up fed server

---

nvflare/lighter/impl/he.py
requirements-dev.txt
requirements-doc.txt
requirements-extra.txt
requirements-min.txt
setup.py

Fixes #130 
To pip install nvflare with tenseal: pip install nvflare[HE]
To install dependencies with tenseal: pip install -r requirements-extra.txt

Make tenseal optional

---

nvflare/apis/utils/format_check.py
nvflare/fuel/hci/client/fl_admin_api.py
nvflare/fuel/hci/client/fl_admin_api_spec.py
nvflare/ha/ha_admin_cmds.py
nvflare/private/fed/server/info_coll_cmd.py

add HA specific commands to FLAdminAPI and improve usage description for show_stats command

add HA specific commands to FLAdminAPI

---

runtest.sh
tests/unit_test/app_common/filters/exclude_vars_test.py

- Add junitxml to unit test
- Update exclude vars test

Add junitxml to unit test and update exclude var test

---

nvflare/apis/job_def.py
nvflare/apis/job_scheduler_spec.py
nvflare/apis/server_engine_spec.py
nvflare/app_common/job_schedulers/job_scheduler.py
nvflare/lighter/project.yml
nvflare/poc/server/startup/fed_server.json
nvflare/poc/server/startup/fed_server_HA.json
nvflare/private/fed/server/server_engine.py
tests/unit_test/app_common/job_schedulers/__init__.py
tests/unit_test/app_common/job_schedulers/job_scheduler_test.py

- Added "app_name" into DispatchInfo
- Added more logs into DefaultJobScheduler
- Added more checks to avoid send check resource requests
- Changed default max_jobs to 1 to be consistent with 2.0 behavior
- Added JobScheduler unit tests

Update job scheduler and add unit tests

---

nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_command_agent.py
nvflare/private/fed/server/server_commands.py
nvflare/private/fed/server/server_engine.py
nvflare/private/fed/server/server_runner.py

To work around a Python internal issue which caused a digest error between process data communication when using the Tensor in the model weights.

To support Tensor used in the model weights for cross_validation.

---

nvflare/apis/resource_manager_spec.py
nvflare/app_common/resource_managers/list_resource_manager.py
nvflare/private/fed/client/client_executor.py
nvflare/private/fed/client/scheduler_cmds.py
tests/unit_test/app_common/resource_managers/list_resource_manager_test.py

- Update ListResourceManager
- When checking, add those resources into "reserved resources" and return a token
- For each reserved resource, check expiration time periodically
- Add unit tests
- Call resource_consumer.consume before start app

Fix list resource manager and add tests

---

.github/workflows/blossom-ci.yml

Signed-off-by: Peixin Li <pxli@nyu.edu>
Since blossom will do an integrity check of the workflow file to make sure that we did not skip any required steps, so there is not too much we can modify.
Generally copied from the MONAI and updated the allowed list for NVFlare repo.
**NOTE:** since we are initiating the CI check and will make adjustment based on test, please expect changes to this file could go back and forth in coming days.

Init blossom-ci workflow

---

nvflare/app_common/widgets/event_recorder.py

- Change expected type of run_num from int to str

Fix event recorder

---

nvflare/app_common/np/np_formatter.py
nvflare/app_common/np/np_model_locator.py
nvflare/app_common/np/np_model_persistor.py
nvflare/app_common/np/np_trainer.py
nvflare/app_common/np/np_validator.py

Fix np codes

---

tests/README.md
tests/integration_test/README.md
tests/integration_test/data/apps/tb_streaming/custom/custom_controller.py
tests/integration_test/data/single_app_as_job/test_example_apps.yml
tests/integration_test/data/single_app_as_job/test_ha.yml
tests/integration_test/data/single_app_as_job/test_internal_apps.yml
tests/integration_test/data/system/1_server_2_clients.yml
tests/integration_test/data/system/ha_1_server_2_clients.yml
tests/integration_test/system_test.py
tests/integration_test/test_cases.yml

- Add README to test
- Add single_app_as_job flag
- Put single_app_as_job related yaml in a folder
- Move "snapshot_path", "job_store_path" into system setup yaml since they related to POC folder

Clean up CI integration tests

---

nvflare/private/fed/app/client/worker_process.py
nvflare/private/fed/app/deployer/base_client_deployer.py
nvflare/private/fed/client/client_engine.py

Fix the issue when overseer is down, the job could not successfully run issue.

pass the SP target info to the client process.

---

3rdParty/SimpleITK.LICENSE.txt
3rdParty/dcmqi.LICENSE.txt
3rdParty/dicom2nifti.LICENSE.txt
3rdParty/pynrrd.LICENSE.txt

Tools needed for prostate datasets preprocessing and format conversion.

Add license files for tools needed for prostate

---

nvflare/private/fed/server/job_runner.py

Fixed the issue if a client in the deploy_map not online, the job failed to deploy and run issue.

Fix client not online deploy error

---

docs/appendix/converting_from_previous.rst
docs/examples/hello_cross_val.rst
docs/examples/hello_numpy.rst
docs/user_guide/admin_commands.rst
docs/user_guide/high_availability.rst
docs/user_guide/job.rst
nvflare/private/fed/server/job_cmds.py

- remove delete_job for now
- Address ticket to explain relationship between job and app
- Address ticket about adding documentation to describe abort tasks/jobs

address issues from QA by adding to docs, removing delete_job

---

nvflare/ha/ha_admin_cmds.py
nvflare/private/fed/server/shell_cmd.py

- Add defensive programming checks to resolve issue QA ran into
- Check that status is stopped so there are no active running jobs on server before shutdown_system

add validation for shutdown_system

---

nvflare/app_common/homomorphic_encryption/he_model_encryptor.py

Also print exception message if it occurs.

Update HE exception message

---

nvflare/lighter/project.yml
nvflare/poc/server/startup/fed_server.json
nvflare/poc/server/startup/fed_server_HA.json
tests/integration_test/data/system/1_server_2_clients.yml
tests/integration_test/data/system/ha_1_server_2_clients.yml

- Change `/tmp` to a common root `/tmp/nvflare/`

Change tmp path under tmp/nvflare

---

nvflare/app_common/job_schedulers/job_scheduler.py

- Sort the jobs in scheduler based on submit time

Sort the jobs in scheduler based on submit time

---

tests/unit_test/app_common/storages/storage_test.py

Remove S3 storage unit test

---

tests/integration_test/run_integration_tests.sh

Add set -e to integration test script

Add set -e to integration test script

---

nvflare/apis/fl_snapshot.py
nvflare/apis/state_persistor.py
nvflare/app_common/state_persistors/storage_state_persistor.py
nvflare/app_common/storages/filesystem_storage.py
nvflare/lighter/project.yml
nvflare/poc/server/startup/fed_server.json
nvflare/poc/server/startup/fed_server_HA.json
tests/integration_test/admin_controller.py
tests/integration_test/data/ha/kill_server_after_training_complete.yml
tests/integration_test/data/ha/kill_server_during_training_after_first_round.yml
tests/integration_test/data/ha/kill_server_during_training_before_first_round.yml
tests/integration_test/data/ha/kill_server_during_training_sending_model.yml
tests/integration_test/site_launcher.py
tests/integration_test/test_fladminapi.py
tests/unit_test/app_common/storages/storage_test.py

- Create directory in `__init__` of `FilesystemStorage` if it does not exist
- Change the arg name to make it more clear
- Update docstrings
- Fix unit test and integration tests

Fix snapshot persistor with storage

---

nvflare/app_common/resource_managers/list_resource_manager.py
tests/unit_test/app_common/resource_managers/list_resource_manager_test.py

- Instead of adding it to the back, we add in the front

Add cancelled resources to front

---

nvflare/private/fed/client/admin.py
nvflare/private/fed/client/admin_msg_sender.py
nvflare/private/fed/client/client_engine.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_engine.py
nvflare/private/fed/server/server_status.py

Add proper actions to close the ThreadPool when shutdown the system. This is to avoid the random bad file descriptor errors.

Added proper system shutdown to avoid random Bad file descriptor errors.

---

examples/cifar10/start_fl_secure.sh

Client GPU resources will be managed by nvflare

cifar-10: don't set cuda visible devices

---

nvflare/private/fed/server/job_runner.py
nvflare/private/fed/server/server_engine.py

- Fix abort job when server execution exception

Fix abort job when server execution exception

---

nvflare/private/fed/app/client/worker_process.py
nvflare/private/fed/client/client_engine.py
nvflare/private/fed/client/client_executor.py
nvflare/private/fed/server/job_runner.py

add description for Yuhong to explain why this solve the race condition: 
there are two race condition points
1) use token_file when create child process
2)  start_run

fixed jobs run race condition issue.

---

docs/best_practices.rst
docs/examples/hello_pt.rst
docs/examples/hello_tf2.rst
docs/faq.rst
docs/programming_guide/fl_context.rst
docs/programming_guide/shareable.rst
docs/user_guide/operation.rst
docs/user_guide/overview.rst

Add to docs:
- mention that secure content cannot be altered
- add more on run_number -> job_id
- add item about IP change for FL server issue to FAQ
- abort_task usage

make additions in docs to address various issues

---

nvflare/fuel/hci/zip_utils.py

- Missing import Optional in this file

Add missing import

---

tests/integration_test/validators/__init__.py
tests/unit_test/app_common/aggregators/accumulate_weighted_aggregator_test.py
tests/unit_test/app_common/aggregators/in_time_accumulate_weighted_aggregator_test.py
tests/unit_test/app_common/widgets/in_time_model_selector_test.py

- Fix the run number issue in unit tests

Fix unit test run number issue

---

nvflare/lighter/impl/workspace.py
nvflare/lighter/project.yml

Fix issue #638 by removing DistributionBuilder

---

nvflare/fuel/hci/server/file_transfer.py
nvflare/private/fed/server/job_meta_validator.py
tests/unit_test/private/fed/server/job_meta_validator_test.py

- Remove fl_ctx in init method of job meta validator

Remove fl_ctx in init method of job meta validator

---

nvflare/ha/overseer/overseer.py
nvflare/ha/overseer/utils.py
nvflare/poc/overseer/startup/start.sh

Start overseer in debug mode in POC

Show better messages to users when starting overseer in POC mode

---

examples/hello-pt-tb/custom/pt_learner.py
examples/hello-pt/custom/pt_model_locator.py

Fix hello examples

---

nvflare/fuel/sec/security_content_service.py
nvflare/private/fed/app/client/client_train.py
nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/utils/fed_utils.py

- Clean up secure content check method
- Move it to the common fed_utils.py

Clean up secure content check method

---

tests/unit_test/apis/impl/job_def_manager_test.py

import mock from unittest

---

examples/brats18/pt/learners/supervised_learner.py
examples/brats18/pt/learners/supervised_monai_brats_learner.py
examples/brats18/result_stat/plot_tensorboard_events.py
examples/cifar10/delete_run.sh
examples/cifar10/figs/plot_tensorboard_events.py
examples/prostate/prostate_2D/pt/learners/supervised_learner.py
examples/prostate/prostate_2D/pt/learners/supervised_monai_prostate_ditto_learner.py
examples/prostate/prostate_2D/pt/learners/supervised_monai_prostate_learner.py
examples/prostate/prostate_3D/pt/learners/supervised_learner.py
examples/prostate/prostate_3D/pt/learners/supervised_monai_prostate_ditto_learner.py
examples/prostate/prostate_3D/pt/learners/supervised_monai_prostate_learner.py
examples/prostate/result_stat/plot_tensorboard_events.py

update run_number to job_id in examples

update run_number to job_id in examples

---

nvflare/fuel/hci/zip_utils.py
tests/unit_test/fuel/hci/zip_utils_test.py
tests/unit_test/private/fed/server/job_meta_validator_test.py

- `_path_join` is refactored to be `normpath_for_zip`
- Added unit tests for `nvflare/fuel/hci/zip_utils.py`

Add unit test for fuel/hci/zip_utils.py

---

examples/brats18/README.md
examples/brats18/result_stat/plot_tensorboard_events.py
examples/brats18/submit_job.sh
examples/prostate/prostate_2D/README.md
examples/prostate/prostate_2D/submit_job.sh
examples/prostate/prostate_3D/README.md
examples/prostate/prostate_3D/submit_job.sh
examples/prostate/result_stat/plot_tensorboard_events.py

Typo corrections and info updates

Readme updates on brats and prostate

---

docs/user_guide/operation.rst

Remove env command in doc

---

docs/examples/access_result.rst
docs/examples/hello_tf2.rst
docs/user_guide/application.rst
docs/user_guide/job.rst
docs/user_guide/overview.rst
docs/user_guide/workspace.rst

- As title, follow up of PR #655

Update workspace related documentation

---

docs/example_applications.rst
docs/flare_overview.rst
docs/highlights.rst
docs/quickstart.rst

- update the format, not content

Update documentation format

---

docs/conf.py
docs/example_applications.rst
docs/examples/access_result.rst
docs/examples/hello_tf2.rst
docs/faq.rst
docs/flare_overview.rst
docs/highlights.rst
docs/index.rst
docs/programming_guide/fl_context.rst
docs/programming_guide/high_availability.rst
docs/programming_guide/system_architecture.rst
docs/quickstart.rst
docs/user_guide/FLAdminAPI.rst
docs/user_guide/application.rst
docs/user_guide/job.rst
docs/user_guide/overview.rst
docs/user_guide/workspace.rst

- Rename all 2.1.0 to 2.1
- Change docs/conf.py version/release

Remove last number of version in doc content

---

ci/run_premerge_cpu.sh
ci/run_premerge_gpu.sh
docs/example_applications.rst
docs/examples/access_result.rst
docs/examples/hello_tf2.rst
docs/flare_overview.rst
docs/highlights.rst
docs/quickstart.rst
docs/user_guide/application.rst
docs/user_guide/job.rst
docs/user_guide/overview.rst
docs/user_guide/workspace.rst

Cherry-pick:
- #600
- #684
- #685

Pick up main changes

---

nvflare/app_common/np/np_model_persistor.py

- from `log_exception` to `log_info`

Change np model persistor log level

---

nvflare/fuel/hci/client/fl_admin_api.py
nvflare/fuel/hci/client/fl_admin_api_spec.py

- As titled, follow up of PR #682

Remove env command in fl admin api

---

ci/run_premerge_gpu.sh

Add dns entries into ci scripts

Add dns entries into ci scripts

---

CITATION.cff

Add doi to citation file

---

.github/workflows/build_docs.yml
.github/workflows/premerge.yml
ci/run_premerge_cpu.sh
ci/run_premerge_gpu.sh
runtest.sh
setup.py
tests/integration_test/data/single_app_as_job/test_hello_numpy.yml
tests/integration_test/data/single_app_as_job/test_hello_pt.yml
tests/integration_test/data/single_app_as_job/test_hello_tf.yml
tests/integration_test/data/single_app_as_job/test_internal_numpy.yml
tests/integration_test/data/single_app_as_job/test_internal_pt.yml
tests/integration_test/data/single_app_as_job/test_internal_tf.yml
tests/integration_test/run_integration_tests.sh
tests/integration_test/system_test.py
tests/integration_test/test_cases.yml

- Split tests into numpy/TF/PT
- Update GitHub workflow

Update main branch CI scripts

---

examples/hello-cyclic/custom/tf2_model_persistor.py
examples/hello-cyclic/custom/trainer.py
examples/hello-tf2/custom/tf2_model_persistor.py
examples/hello-tf2/custom/trainer.py
tests/integration_test/tf2/model_persistor.py
tests/integration_test/tf2/trainer.py

Fix typos in tf related codes in examples and tests

---

runtest.sh

Add cov.xml to unit test script

---

tests/integration_test/src/provision_site_launcher.py
tests/integration_test/src/site_launcher.py

Wait for cleanup process before start next test case

---

nvflare/apis/overseer_spec.py
nvflare/ha/dummy_overseer_agent.py
nvflare/ha/ha_admin_cmds.py
nvflare/ha/overseer_agent.py
nvflare/ha/overseer_agent_app.py
requirements-min.txt

- Remove unused methods in spec
- Add required methods in spec
- Update requirements-min.txt
- Fix `_conditional_cb` typo
- Change `_overseer_info` to `overseer_info` since other class need access

Fix overseer code style and issues

---

integration/README.MD
integration/sample/README.MD
research/README.MD
research/sample_research/README.MD

- These modifications are written by @chesterxgchen

Add research and integration folder

---

nvflare/lighter/impl/cert.py

Add org to cert

---

examples/hello-mpi/app_client/config/config_fed_client.json
examples/hello-mpi/app_client/custom/__init__.py
examples/hello-mpi/app_client/custom/mpi_execute.py
examples/hello-mpi/app_server/config/config_fed_server.json
examples/hello-mpi/app_server/custom/__init__.py
examples/hello-mpi/app_server/custom/mpi_controller.py
examples/hello-mpi/meta.json
nvflare/apis/collective_comm_constants.py
nvflare/apis/fl_constant.py
nvflare/app_common/collective_comm/__init__.py
nvflare/app_common/collective_comm/collective_comm_widget.py
nvflare/app_common/collective_comm/collective_functor.py
nvflare/private/fed/app/deployer/server_deployer.py
nvflare/private/fed/app/server/runner_process.py
nvflare/private/fed/server/collective_comm_waiter.py
nvflare/private/fed/server/collective_command_agent.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_command_agent.py
nvflare/private/fed/server/server_commands.py
nvflare/private/fed/server/server_engine.py
tests/unit_test/private/fed/server/fed_server_test.py

- Add collective communication mechanisms
- Collective communication constants
- Collective communication command agent
- Add collective communication widget and functor to handle AllReduce, AllGather, Broadcast
- Collective communication widget
- Collective functor
- Add a hello-mpi example to demonstrate the capabilities
- MPIExecutor
- MPIController

Add Collective communication and hello-mpi example

---

nvflare/fuel/utils/gpu_utils.py
nvflare/lighter/poc_commands.py

Move GPU utils out of poc_commands for later reuse

---

tests/integration_test/run_integration_tests.sh
tests/integration_test/validators/cross_val_result_validator.py
tests/integration_test/validators/job_result_validator.py
tests/integration_test/validators/np_model_validator.py
tests/integration_test/validators/np_sag_result_validator.py
tests/integration_test/validators/pt_model_validator.py
tests/integration_test/validators/tb_result_validator.py
tests/integration_test/validators/tf_model_validator.py
tests/unit_test/tool/package_checker/utils_test.py

Update integration test validator log level

---

nvflare/lighter/cli_exception.py
nvflare/lighter/nvflare.py
nvflare/lighter/poc_commands.py
nvflare/lighter/provision.py
nvflare/tool/preflight_check.py
tests/unit_test/lighter/poc_commands_test.py

1) add nvflare provision command ( add deprecate warning to provision command) 
2) add nvflare preflight_check command

consolidate NVFLARE CLI

---

research/auto-fed-rl/index.html

Redirecting to https://github.com/guopengf/Auto-FedRL

link to temporary Auto-FedRL repo

---

nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/client/fed_client_base.py

- Added message for FLCommunicationError.

Addressed several QA issues.

---

nvflare/fuel/hci/client/fl_admin_api.py
nvflare/fuel/hci/table.py
nvflare/private/fed/server/training_cmds.py

Fix get_connected_clients in fl_admin_api

---

integration/monai/examples/spleen_ct_segmentation/virtualenv/requirements.txt
integration/monai/setup.py

removes pytorch-ignite dependency from monai_nvflare package and adds min version requirements.

update monai_nvflare dependecies

---

integration/monai/examples/spleen_ct_segmentation/README.md

use latest argument names in instructions

Update sim arguments in monai-fl example [skip ci]

---

integration/monai/examples/spleen_ct_segmentation/README.md

use latest argument names in instructions

update readme simulator arguments

---

.github/workflows/codeql.yml

add CodeQL action

---

.github/workflows/blossom-ci.yml

Signed-off-by: YanxuanLiu <yanxuanl@nvidia.com>
add holgerroth to blossom trigger list

added holgerroth to trigger list

---

nvflare/apis/fl_exception.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/client/fed_client_base.py

Fixed the FLCommunicationError log error

Fixed the FLCommunicationError log error.

---

build_docker.sh
nvflare/dashboard/application/__init__.py
nvflare/dashboard/application/clients.py
nvflare/dashboard/application/project.py
nvflare/dashboard/application/store.py
nvflare/dashboard/application/users.py
nvflare/dashboard/dashboard.yaml

Set download attachment filename to include quote

Remove CORS because setting baseUrl to "" works

---

nvflare/apis/fl_exception.py
nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/app/simulator/simulator_worker.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/client/fed_client_base.py

Cherry-pick the 16e9db7b0dd6e558d12952a7c354f3ae72abc91d and 11e5b013577ed5b3851951d6de519211a20b08e2 into dev.

cherry-pick 2.2 changes into dev

---

nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/app/simulator/simulator_worker.py

Fix issues:
1. Several log message syntax issues.
2. empty log message when error happened
3. log file consistent format
4. passing the parent pid to child process, instead of fetching from the child process

Fixed some log issues and a timing issue for CTR-C kill the simulator.

---

nvflare/dashboard/application/clients.py
nvflare/dashboard/application/store.py

Fix editing site name

---

nvflare/lighter/poc.py
nvflare/lighter/poc_commands.py

Issue is caused by unpack_archive only to current directory not dest poc directory

2.2_Branch: fix POC command bug [skip ci]

---

nvflare/app_common/resource_consumers/gpu_resource_consumer.py
nvflare/app_common/resource_managers/gpu_resource_manager.py
nvflare/app_common/resource_managers/list_resource_manager.py
nvflare/app_common/resource_managers/resouce_manager.py
nvflare/fuel/utils/check_utils.py
nvflare/fuel/utils/gpu_utils.py
tests/unit_test/app_common/resource_managers/gpu_resource_manager_test.py
tests/unit_test/app_common/resource_managers/list_resource_manager_test.py

- Create a base class `BaseResourceManager`
- Add GPUResourceManager (it reads from site.json)
-  it supports number of gpus and gpu memory (treat each GPU has same GPU memory)
- Add GPUResourceManager unit test
- Update GPUResourceConsumer to match with GPUResourceManager

Add GPU resource consumer

---

nvflare/app_opt/xgboost/controller.py
nvflare/app_opt/xgboost/executor_base.py

- Fix _get_certificates function return True in the end
- Fix get server address in executor

Fix hello-xgboost in secure mode

---

nvflare/private/fed/app/default_app_validator.py
nvflare/private/fed/app/fl_app_validator.py
nvflare/private/fed/app/fl_conf.py
nvflare/private/fed/utils/app_deployer.py
nvflare/private/fed/utils/fed_utils.py

- Server app just need to have config_fed_server.json
- Client app just need to have config_fed_client.json

Fix app validator

---

requirements-min.txt
setup.py

pip install nvflare[HE]
Fix #913

Add pip install optional extra [HE]

---

nvflare/apis/utils/decomposers/flare_decomposers.py
nvflare/private/fed/app/client/client_train.py
nvflare/private/fed/app/client/sub_worker_process.py
nvflare/private/fed/app/client/worker_process.py
nvflare/private/fed/app/server/runner_process.py
nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/app/simulator/simulator_worker.py
nvflare/private/fed/client/fed_client.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/utils/fed_utils.py

Fixed the PTMultiProcessExecutor error. Create the fobs_initialize() for all the processes.

Fix mgpu executor

---

examples/brats18/result_stat/plot_tensorboard_events.py
examples/cifar10/figs/plot_tensorboard_events.py
examples/cifar10/pt/learners/cifar10_scaffold_learner.py
examples/cifar10/pt/utils/cifar10_data_splitter.py
examples/cifar10/submit_job.py
examples/federated_statistics/df_stats/data_utils.py
examples/federated_statistics/df_stats/df_stats_job/custom/df_statistics.py
examples/federated_statistics/image_stats/image_stats_job/custom/image_statistics.py
examples/hello-monai-bundle/app/custom/bundle_configer.py
examples/hello-monai-bundle/app/custom/monai_trainer.py
examples/hello-monai/app/custom/monai_trainer.py
examples/hello-monai/app/custom/train_configer.py
examples/prostate/data_preparation/utils/mhd_to_nifti.py
examples/prostate/prostate_3D/pt/learners/supervised_monai_prostate_learner.py
examples/prostate/result_stat/plot_tensorboard_events.py
examples/xgboost/utils/prepare_job_config.py
nvflare/app_common/aggregators/xgboost_bagging_aggregator.py
nvflare/app_common/learners/xgboost_tree_fed_learner.py
nvflare/app_common/model_persistors/json_model_persistor.py
nvflare/app_common/shareablegenerators/xgb_model_shareable_generator.py
nvflare/app_common/workflows/scatter_and_gather.py
nvflare/private/fed/client/client_runner.py

Fix code format [skip ci]

---

examples/hello-cyclic/README.md
examples/hello-numpy-cross-val/README.md
examples/hello-numpy-sag/README.md
examples/hello-pt-tb/README.md
examples/hello-pt/README.md
examples/hello-tf2/README.md

Update hello-* example readme to use simulator [skip ci]

---

nvflare/apis/dxo.py
nvflare/app_common/aggregators/dxo_aggregator.py

Remove unused vars in datakind

Remove unused vars in datakind

---

nvflare/app_common/resource_consumers/list_resource_consumer.py

- To support ListResourceManager

Add ListResourceConsumer to support ListResourceManager [skip ci]

---

nvflare/private/fed/server/server_engine.py

it should return empty string when success

Fix server engine abort_app_on_server

---

nvflare/lighter/ha_project.yml
nvflare/lighter/impl/workspace.py

- Remove unused parts and correct docstring

Clean up lighter project.yml and workspace docstring [skip ci]

---

examples/xgboost/histogram-based/job_configs/base/app/custom/higgs_executor.py
nvflare/app_opt/xgboost/histogram_based/executor.py

Fix xgboost histogram based issue [skip ci]

---

.github/workflows/blossom-ci.yml

Signed-off-by: YanxuanLiu <yanxuanl@nvidia.com>
add 4 new members to trigger list of blossom-ci

[CICD] add new members to trigger list of blossom-ci [skip ci]

---

nvflare/dashboard/application/store.py
nvflare/dashboard/config.py

Truncate project's short name to 16 chars if its length exceeds 16.

Use randomly generated string as SECRET_KEY if users do not set it

---

nvflare/private/fed/app/deployer/server_deployer.py
nvflare/private/fed/app/deployer/simulator_deployer.py

Make heartbeat_timeout optional

---

nvflare/fuel/hci/client/fl_admin_api.py

fix status of response to not throw PermissionError if the command response was SUCCESS

fix status of response

---

integration/monai/examples/spleen_ct_segmentation/README.md
integration/monai/examples/spleen_ct_segmentation/virtualenv/requirements.txt
integration/monai/monai_nvflare/client_algo_statistics.py
integration/monai/setup.py

Fixes default feature name if only single-channel images are used.

fix single channel default feature name [skip ci]

---

integration/monai/monai_nvflare/client_algo_statistics.py

Raise error in case of user misconfigurations.

Check config for monai fed stats [skip ci]

---

README.md
docs/key_features.rst
docs/release_notes/2.2.1/migration_notes.md

With this change, the front facing NVFLARE README IS changed !!!. Please review carefully
1) Update NVFLARE README.md to include
a) Quick Start 
b) Release Hightlights
c) migration notes -- migration to 2.2.1
2) update the key_features.rst 
update the link for moani integration to point to integration folder.

NVFLARE README Update etc. [skip ci]

---

README.md
docs/release_notes/2.2.1/migration_notes.md

README UPDATE [slip ci]

---

docs/publications_and_talks.md

fix date and order [skip ci]

---

nvflare/app_common/decomposers/common_decomposers.py

- Need ModelLearnable decomposer after PR https://github.com/NVIDIA/NVFlare/pull/1105

Add ModelLearnable decomposers

---

nvflare/app_common/app_event_type.py
nvflare/app_common/widgets/intime_model_selector.py
tests/unit_test/app_common/widgets/in_time_model_selector_test.py

apply same changes as in dev branch. See https://github.com/NVIDIA/NVFlare/pull/1116.

update model selector 2.1 

---

nvflare/app_common/app_event_type.py
nvflare/app_common/widgets/intime_model_selector.py
tests/unit_test/app_common/widgets/in_time_model_selector_test.py

apply same changes as in dev branch. See https://github.com/NVIDIA/NVFlare/pull/1116.

update model selector 2.2

---

.github/ISSUE_TEMPLATE/feature_request.md

Add feature request issue template [skip ci]

---

.github/ISSUE_TEMPLATE/question.md

Add question issue template [skip ci]

---

.github/workflows/premerge.yml
integration/monai/examples/spleen_ct_segmentation/download_spleen_dataset.py
integration/monai/examples/spleen_ct_segmentation/submit_job.py
integration/monai/monai_nvflare/client_algo_statistics.py
integration/monai/monai_nvflare/utils.py
integration/monai/setup.py
nvflare/app_common/statistics/statistics_privacy_cleanser.py
nvflare/app_opt/statistics/visualization/statistics_visualization.py
nvflare/dashboard/__init__.py
nvflare/fuel/hci/client/overseer_service_finder.py
nvflare/fuel/utils/fsm.py
runtest.sh
tests/integration_test/data/apps/cyclic/custom/__init__.py
tests/unit_test/apis/controller_spec_test.py
tests/unit_test/apis/impl/controller_test.py
tests/unit_test/app_common/widgets/in_time_model_selector_test.py

- Enable header scan in "runtest.sh"
- Add missing headers
- Fix code formats
- Add more python version in "premerge" pipeline

Enable header scan and fix unit tests

---

nvflare/private/fed/app/fl_conf.py
nvflare/private/fed/server/fed_server.py

. Fixed a server parent process race condition.
. Fixed a client privacy.json component scan issue.

Fixed a race condition and client privacy.json issue.

---

CONTRIBUTING.md

unit tests follow the `*_test.py` pattern.
```
tests/integration_test/system_test.py
tests/integration_test/overseer_test.py
tests/unit_test/apis/impl/controller_test.py
tests/unit_test/apis/impl/job_def_manager_test.py
tests/unit_test/apis/analytix_test.py
tests/unit_test/apis/controller_spec_test.py
tests/unit_test/apis/fl_context_test.py
tests/unit_test/apis/utils/decomposers/flare_decomposers_test.py
tests/unit_test/apis/utils/job_utils_test.py
tests/unit_test/apis/utils/format_check_test.py
tests/unit_test/app_common/widgets/in_time_model_selector_test.py
tests/unit_test/app_common/widgets/streaming_test.py
tests/unit_test/app_common/statistics/min_max_cleanser_test.py
tests/unit_test/app_common/statistics/hist_bins_cleanser_test.py …
```

Fix unit test filename pattern [skip ci]

---

examples/hello-pt-tb/app/custom/test_custom.py
examples/hello-pt/app/custom/test_custom.py

Add example tests per TME requests

add example unit tests

---

runtest.sh

The recent change in runtest.sh broken the ./runtest.sh -u command
I restored the old changes. @YuanTingHsieh  if you like your changes, you will need to write a new PR and well test the code.

restore the changes to fix the bug introduced.

---

nvflare/fuel/hci/client/api.py
tests/integration_test/src/admin_controller.py

- As title, old changes from previous PR break our integration tests

Add missing poc_key in api.py

---

docs/user_guide/fl_simulator.rst

update the simulator docs [skip ci]

---

docs/user_guide/fl_simulator.rst

Simulator docs update for main branch.

Main simulator docs [skip ci]

---

integration/monai/examples/spleen_ct_segmentation/virtualenv/requirements.txt

Add some missing requirements to the MONAI stats example

add missing dependencies [skip ci]

---

nvflare/app_common/filters/svt_privacy.py

1214 svt_privacy adds an option for random.choice replacement 

---

nvflare/apis/impl/controller.py
nvflare/apis/server_engine_spec.py
nvflare/private/fed/server/server_engine_internal_spec.py

- Clean up some logic in controller.py
- Set the instance variable `self._engine` in `initialize_run` and just use it afterwards

Clean up controller logic

---

nvflare/tool/package_checker/check_rule.py
nvflare/tool/package_checker/client_package_checker.py
nvflare/tool/package_checker/overseer_package_checker.py
nvflare/tool/package_checker/package_checker.py
nvflare/tool/package_checker/server_package_checker.py
nvflare/tool/package_checker/utils.py
tests/integration_test/data/projects/dummy.yml
tests/integration_test/preflight_check_test.py
tests/integration_test/run_integration_tests.sh
tests/integration_test/src/__init__.py
tests/integration_test/src/action_handlers.py
tests/integration_test/src/admin_controller.py
tests/integration_test/src/constants.py
tests/integration_test/src/poc_site_launcher.py
tests/integration_test/src/provision_site_launcher.py
tests/integration_test/src/site_launcher.py
tests/integration_test/src/utils.py
tests/integration_test/system_test.py
tests/unit_test/tool/package_checker/utils_test.py

- Fix #1217 #1220 #1222
- Add unit tests and integration tests for preflight check

Fix preflight_check issue and add unit tests and integration tests

---

examples/psi/README.md
examples/psi/user_email_match/app/config/config_fed_client.json
examples/psi/user_email_match/app/custom/local_psi.py

- fix a type in simulator command
- make data path configurable

update psi readme [skip ci]

---

integration/monai/examples/spleen_ct_segmentation_real-world/README.md
integration/monai/examples/spleen_ct_segmentation_sim/README.md

Fix typo and change command style.
Addresses additional comments by @mingxin-zheng raised in https://github.com/NVIDIA/NVFlare/pull/1229.

Update monai examples again [skip ci]

---

nvflare/apis/controller_spec.py
tests/unit_test/apis/controller_spec_test.py

- Just a manual conflicts resolving of this PR https://github.com/NVIDIA/NVFlare/pull/1151 by @holgerroth

remove key check in task get_prop method

---

nvflare/app_common/widgets/streaming.py
nvflare/app_common/workflows/common_controller.py
tests/integration_test/data/apps/tb_streaming/custom/custom_controller.py
tests/integration_test/system_test.py

- Fix streaming that causes test failure
- Fix integration test logic

Fix tb streaming

---

examples/hello-pt-tb/app/custom/test_custom.py
examples/hello-pt/app/custom/test_custom.py
examples/xgboost/utils/baseline_centralized.py
requirements-dev.txt

- Update black/isort/flake8 versions
- Fix code style issue

Update black/isort/flake8 and fix code style [skip ci]

---

nvflare/fuel/utils/fobs/__init__.py
nvflare/fuel/utils/fobs/fobs.py
nvflare/private/fed/server/client_manager.py

. cherry-pick the Auto register enum decomposers
. Allow the same client to login with new token

Auto register enum decomposers

---

nvflare/apis/fl_constant.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/server/info_coll_cmd.py

. Fixed the show_errors missing job_id issue.
. Enhance client registration.

Fixed show_errors missing job_id issue.

---

nvflare/dashboard/application/blob.py

This PR fixes #1219.  Originally, the issue was fixed in #1215.  However, after #1251, the fix was also reverted back.  Thus, the PR will re-apply the fix.

Fix missing information in fed_admin.json

---

nvflare/fuel/f3/demo/client.py
nvflare/fuel/f3/demo/server.py
nvflare/fuel/f3/drivers/socket_driver.py
nvflare/fuel/f3/sfm/conn_manager.py
nvflare/fuel/f3/sfm/sfm_conn.py
nvflare/fuel/f3/sfm/sfm_endpoint.py

1. Added support for single connection per endpoint
2. Detect UDS/TCP connection closing.

Fixed issues with TCP/UDS connection closing

---

nvflare/private/defs.py
nvflare/private/fed/app/server/runner_process.py
nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/app/simulator/simulator_worker.py
nvflare/private/fed/client/client_app_runner.py
nvflare/private/fed/client/client_run_manager.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_command_agent.py
nvflare/private/fed/server/server_commands.py
nvflare/private/fed/simulator/simulator_server.py

Simulator integrate with FCI API

Simulator f3

---

nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/app/simulator/simulator_worker.py
nvflare/private/fed/server/fed_server.py

Added the cell stop for simulator.

Added the cell stop for simulator.

---

examples/cifar10/cifar10-real-world/README.md

Allow setting `N_GPU` for resource management in real-world example

CIFAR-10: make local number GPUs configurable

---

examples/cifar10/cifar10-real-world/README.md

Update wording of multi-task resource management.

Update cifar10 real world instructions

---

nvflare/app_opt/sklearn/__init__.py

Add missing __init__.py

---

nvflare/apis/fl_constant.py
nvflare/private/fed/client/client_executor.py
nvflare/private/fed/server/admin.py
nvflare/private/fed/server/info_coll_cmd.py
nvflare/private/fed/server/server_commands.py
nvflare/private/fed/server/server_engine.py
nvflare/private/fed/server/server_engine_internal_spec.py
nvflare/widgets/info_collector.py

Added reset_errors command support.

Added reset_errors command support.

---

nvflare/private/fed/app/client/client_train.py
nvflare/private/fed/app/client/sub_worker_process.py
nvflare/private/fed/app/deployer/simulator_deployer.py
nvflare/private/fed/app/server/runner_process.py
nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/client/client_engine.py
nvflare/private/fed/client/fed_client_base.py
nvflare/private/fed/server/admin.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/simulator/simulator_server.py

Integrate with new cell using MainProcessMonitor

Integrate with new cell

---

nvflare/app_common/aggregators/dxo_aggregator.py
nvflare/app_common/aggregators/intime_accumulate_model_aggregator.py

Needed to support metric aggregation for hyperparameter search, e.g. for [Auto-FedRL](https://arxiv.org/abs/2203.06338)

Allow metrics aggregation

---

nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/client/client_engine.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_engine.py
nvflare/private/fed/simulator/simulator_server.py

Fixed the simulator client heartbeat not stopped issue.

Fixed the simulator client heartbeat not stopped issue.

---

.github/pull_request_template.md

- Add a template for PR so it is more descriptive and make people's life easier

Create pull_request_template.md [skip ci]

---

nvflare/fuel/f3/mpm.py
nvflare/private/aux_runner.py
nvflare/private/fed/app/simulator/simulator.py
nvflare/private/fed/server/admin.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/simulator/simulator_server.py

Fixes # .
Fixed the leaking semaphore issue when the server shutdown.

Simulator shutdown

---

nvflare/fuel/f3/cellnet/cell.py
nvflare/fuel/f3/cellnet/net_agent.py
nvflare/fuel/f3/cellnet/net_manager.py
nvflare/fuel/f3/mpm.py
nvflare/fuel/f3/qat/cell_runner.py
nvflare/fuel/f3/qat/run_cell.py
nvflare/fuel/f3/qat/run_server.py
nvflare/fuel/utils/config_service.py

Fixed ad-hoc connection race condition;
Added get_float_var in config service;
Added var_values dict to keep latest var values in config_service;
Added admin commands to show config vars;

Nvflare f3

---

nvflare/apis/fl_constant.py
nvflare/private/fed/app/client/client_train.py
nvflare/private/fed/app/client/worker_process.py
nvflare/private/fed/app/deployer/simulator_deployer.py
nvflare/private/fed/app/fl_conf.py
nvflare/private/fed/app/server/runner_process.py
nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/client/client_app_runner.py
nvflare/private/fed/client/client_executor.py
nvflare/private/fed/client/client_json_config.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/client/fed_client_base.py
nvflare/private/fed/server/server_app_runner.py
nvflare/private/fed/server/server_json_config.py
nvflare/private/fed/simulator/simulator_client_engine.py

Integrate with the Config_service.

Simulator controller failed start

---

nvflare/apis/fl_constant.py
nvflare/private/fed/app/client/client_train.py
nvflare/private/fed/app/client/worker_process.py
nvflare/private/fed/app/deployer/simulator_deployer.py
nvflare/private/fed/app/fl_conf.py
nvflare/private/fed/app/server/runner_process.py
nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/client/client_app_runner.py
nvflare/private/fed/client/client_executor.py
nvflare/private/fed/client/client_json_config.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/client/fed_client_base.py
nvflare/private/fed/server/server_app_runner.py
nvflare/private/fed/server/server_json_config.py
nvflare/private/fed/simulator/simulator_client_engine.py

Enhance the SP switch when setting the cell. Wait for the client_runner to be created correctly.

Sp switch enhance

---

nvflare/fuel/f3/mpm.py
nvflare/private/fed/app/client/client_train.py
nvflare/private/fed/app/client/sub_worker_process.py
nvflare/private/fed/app/client/worker_process.py
nvflare/private/fed/app/deployer/simulator_deployer.py
nvflare/private/fed/app/server/runner_process.py
nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/app/simulator/simulator_worker.py
nvflare/private/fed/client/client_engine.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/client/fed_client_base.py
nvflare/private/fed/server/admin.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_command_agent.py
nvflare/private/fed/server/server_engine.py
nvflare/private/fed/server/server_runner.py

Integrate with the new MPM main thread monitor implementation.

Mpm run change

---

nvflare/fuel/f3/aio_context.py
nvflare/fuel/f3/drivers/aio_grpc_driver.py
nvflare/fuel/f3/mpm.py

Support the use of global AIO context.

support global aio context

---

nvflare/dashboard/application/blob.py

Fixes #1317 
Dashboard accidentally loads CSP-related codes, which is still under development and contains bugs.  This PR resolves that bug.

Fix issue #1317

---

nvflare/apis/fl_constant.py
nvflare/private/fed/app/server/runner_process.py
nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/client/fed_client_base.py
nvflare/private/fed/cmi.py
nvflare/private/fed/server/client_manager.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/job_runner.py

Added support for the secure train.
Fixed some issues with the status update.

Integrated with the FCI secure train.

---

nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/client/client_engine.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/simulator/simulator_server.py

Enhance the Simulator shutdown process. Removed the cellnet error message.

Enhance the simulator shutdown process.

---

nvflare/private/fed/app/deployer/simulator_deployer.py
nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/client/client_engine.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/simulator/simulator_server.py

Simulator manage the admin server stop, not using the MPM.

Simulator stop enhance

---

nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/simulator/simulator_client_engine.py

Simulator not call  _clean_up_runs.

Simulator heartbeat

---

examples/advanced/sklearn-kmeans/README.md
examples/advanced/sklearn-kmeans/job_configs/sklearn_kmeans_base/app/custom/kmeans_assembler.py
examples/advanced/sklearn-kmeans/virtualenv/requirements.txt
nvflare/app_common/aggregators/assembler.py
nvflare/app_common/aggregators/collect_and_assemble_aggregator.py
nvflare/app_opt/sklearn/joblib_model_param_persistor.py

- Ran grammar checker on readme.
- Some refactoring on collector and assembler classes.
- Renamed `collector` to `collection` as it is a dict, not a class.
- Removed some unused functions.
- Pass fl_ctx to assemble() function for higher flexibility in the future.

Update k-means example

---

nvflare/app_opt/pt/__init__.py

Follows PR #1348 
Miss one import in that PR, found by @holgerroth .

Fix app_opt pt import

---

nvflare/private/fed/app/client/worker_process.py
nvflare/private/fed/app/deployer/simulator_deployer.py
nvflare/private/fed/client/client_executor.py
nvflare/private/fed/client/fed_client_base.py
nvflare/private/fed/server/fed_server.py

Changed the scheme config to use the scheme name only. Make it consistent with other component config.

fci scheme config change to make it use the scheme name only.

---

tests/unit_test/private/fed/app/deployer/simulator_deployer_test.py
tests/unit_test/private/fed/app/simulator/simulator_runner_test.py
tests/unit_test/private/fed/server/fed_server_test.py

Fixed the broken unit tests because of FCI integration.

Fixed the unit tests for FCI integration.

---

nvflare/private/fed/app/fl_conf.py
nvflare/private/fed/client/client_json_config.py
nvflare/private/fed/server/server_json_config.py

Fixed the issue the component could not be located due to "app_opt" folder move.

Fixed the issue could not locate the components due to app_opt move.

---

nvflare/lighter/impl/master_template.yml

This PR fixes a typo in dashboard cloud launch script and improves the message shown to users at the end of launching.

Fix typo and improve message in dashboard scripts

---

nvflare/apis/fl_constant.py
nvflare/private/defs.py
nvflare/private/fed/app/__init__.py
nvflare/private/fed/app/fl_conf.py
nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/server/admin.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/message_send.py
nvflare/private/fed/server/server_engine.py
tests/unit_test/private/fed/server/fed_server_test.py

FL server deploy integrate with Cellnet.
- FL server is able to deploy and start using Cellnet.
- admin is able to connect to the server for check_status.

FL server deploy integrate with cellnet

---

examples/advanced/sklearn-kmeans/README.md
examples/advanced/sklearn-linear/README.md
examples/advanced/sklearn-linear/job_configs/sklearn_linear_base/app/custom/linear_learner.py
examples/advanced/sklearn-linear/virtualenv/requirements.txt
nvflare/app_opt/sklearn/sklearn_executor.py

Fixes # .
- Grammar check on readme.
- Fix broken link.
- Some minor refactoring.

sklearn linear update [skip ci]

---

3rdParty/websockets.LICENSE.txt
nvflare/__init__.py
nvflare/fuel/f3/drivers/aio_context.py
nvflare/fuel/f3/drivers/aio_grpc_driver.py
nvflare/fuel/f3/drivers/aio_http_driver.py
setup.cfg
tests/unit_test/fuel/f3/communicator_test.py
tests/unit_test/fuel/f3/drivers/driver_manager_test.py

Merged async HTTP driver to dev
1. Merged http driver to dev
2. Added test cases for it
3. Put __version__ back to nvflare/__init__.py

Async HTTP Driver for FCI [skip ci]

---

nvflare/app_common/aggregators/collect_and_assemble_aggregator.py
nvflare/app_common/aggregators/intime_accumulate_model_aggregator.py
nvflare/app_common/widgets/intime_model_selector.py
nvflare/app_common/workflows/scatter_and_gather.py
nvflare/app_opt/he/intime_accumulate_model_aggregator.py
nvflare/app_opt/he/model_decryptor.py
nvflare/app_opt/he/model_encryptor.py
nvflare/app_opt/he/model_shareable_generator.py
nvflare/app_opt/xgboost/tree_based/bagging_aggregator.py
tests/unit_test/app_common/aggregators/in_time_accumulate_weighted_aggregator_test.py

Fixes #1389 .
- Uses `get_cookie` instead of `get_header` to get `CONTRIBUTION_ROUND`

Fix in time model selector

---

nvflare/fuel/f3/drivers/aio_conn.py
nvflare/fuel/f3/drivers/aio_tcp_driver.py
tests/unit_test/fuel/f3/communicator_test.py
tests/unit_test/fuel/f3/drivers/driver_manager_test.py

Merged async TCP driver to dev (2nd PR)
1. Merged async TCP driver
2. Added unit test for the driver

Async TCP Driver [skip ci]

---

nvflare/fuel/flare_api/flare_api.py

Fixes issue with starting insecure session with flare_api by adding the username for the call to Session.

fix new_insecure_session

---

examples/advanced/sklearn-kmeans/job_configs/sklearn_kmeans_base/app/custom/kmeans_learner.py
examples/advanced/sklearn-linear/README.md
examples/advanced/sklearn-linear/job_configs/sklearn_linear_base/app/custom/linear_learner.py
examples/advanced/sklearn-svm/README.md
examples/advanced/sklearn-svm/job_configs/sklearn_svm_base/app/custom/svm_learner.py
examples/advanced/sklearn-svm/virtualenv/requirements.txt
nvflare/app_opt/sklearn/sklearn_executor.py

Update SKLearn readmes and refactor SKLearnExecutor [skip ci]

---

nvflare/fuel/f3/drivers/aio_context.py
nvflare/fuel/f3/drivers/aio_uds_driver.py
tests/unit_test/fuel/f3/communicator_test.py
tests/unit_test/fuel/f3/drivers/driver_manager_test.py

Merged async UDS driver
1. Merged async UDS driver to dev
2. Added test cases for the async UDS driver

Async UDS Driver [skip ci]

---

examples/advanced/sklearn-kmeans/job_configs/sklearn_kmeans_base/app/custom/kmeans_learner.py
examples/advanced/sklearn-linear/job_configs/sklearn_linear_base/app/custom/linear_learner.py

Add AUC & Homogeneity log to SK Learners [skip ci]

---

nvflare/private/fed/simulator/simulator_client_engine.py
nvflare/private/fed/simulator/simulator_server.py

Fixes # .
Enhance the simulator to avoid the un-necessary Cell error at the END_RUN.

Enahce Simulator to avoid the Cell Error at end run.

---

nvflare/private/fed/client/communicator.py

Fixes # .
Changed the client fetch_task fetch_again behavior to without delay. Client Runner handles the task_fetch_interval.

Changed the fetch_task fetch_again without delay.

---

nvflare/__init__.py

- Add back the SimulatorRunner

Add back the SimulatorRunner

---

nvflare/fuel/f3/drivers/socket_conn.py
nvflare/fuel/f3/mpm.py

Changed a few logs from info to debug level. End users don't care about those messages.

Log Cleanup [skip ci]

---

nvflare/ha/overseer/utils.py

Some codes in overseer were no longer in use.  This PR removes those codes.

Remove unused codes [skip ci]

---

nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/server/job_cmds.py
nvflare/private/fed/server/job_runner.py
nvflare/private/fed/server/server_command_agent.py

Fixes # .
-  Fixed a simulator paramenter parsing bug.
- Fixed the "start_app client" not able to start client job bug.
- Fixed "abort_job" not showing proper error message for SUBMITTED job bug. 
A few QA bugs issue fixes.

Fixed a few QA bugs.

---

nvflare/fuel/utils/fobs/fobs.py

Added more details in the exception when recursive data is encountered in FOBS.

More detailed error for recursive data

---

nvflare/dashboard/application/blob.py
nvflare/lighter/impl/master_template.yml

Fix jupyter notebook FLARE API path issue
Add codes to set username in jupyter notebook at provisioning time

Fix jupyter notebook FLARE API path issue

---

nvflare/apis/fl_context.py
nvflare/app_common/workflows/cyclic_ctl.py
nvflare/app_common/workflows/scatter_and_gather.py
nvflare/app_common/workflows/scatter_and_gather_scaffold.py

Some props stickiness are inconsistent.
We change them to be the same.

Fix fl context prop

---

setup.cfg

Update protobuf version

---

nvflare/fuel/flare_api/flare_api.py

Fixed flare api's list_job to be consistent with the command behavior. Specifically, removed the "all" arg. To get all jobs, just do not specify the "limit" arg (or set to None).

fix list_job in flare api

---

nvflare/private/fed/server/fed_server.py

Overseer CB could happen multiple times in quick succession, whereas server state change could take time to complete. To protect server state's integrity, we do not want to handle these state change requests concurrently since they may mess up each other. We also don't need to pile up the requests to process them sequentially. This is because the latest state change request counts. So if there are multiple such requests during the state change processing, we only need to deal with the last one after the current state change processing is done and ignore all others.
This PR uses a simple flag to indicate whether we are busy with state change. If so simply ignore any other state change requests. Since state change requests repeat themselves, we will be able to catch the wanted change in the …

protect server state against multiple state changes

---

nvflare/lighter/impl/master_template.yml

Fix loading configuration files in aws scripts
Add early stop on error cases in aws

Fix loading conf in aws scripts

---

examples/advanced/random_forest/README.md
examples/advanced/random_forest/data_split_gen.sh
examples/advanced/random_forest/requirements.txt

Fixes # .
Fixed two suggestions from QA

Random forest minor fixes

---

docs/user_guide.rst
docs/user_guide/cloud_deployment.rst

Add cloud deployment user document.

Add user guide on cloud deployment

---

docs/whats_new.rst

Fixes # .
git push --set-upstream origin whats_new_data_leakage

Update what's new to include data leakage tool research

---

nvflare/lighter/impl/master_template.yml

Add check on az login exit code
Add check on derived location and specified location

Add check on az login exit code

---

examples/README.md
examples/virtualenv/set_env.sh

Fixes # .
Remove unnecessary virtualenv folder & call `source ./set_env.sh` directly.

Remove unnecessary virtualenv folder [skip ci]

---

docs/conf.py
requirements-doc.txt

Updates the docs for the 2.2 branch to be current and fixes the problem of jquery not working so other versions can be selected.

Patch docs requirements to fix issue with jquery not working

---

nvflare/private/fed/app/client/sub_worker_process.py
nvflare/private/fed/runner.py

Fixes # .
ensure the START_RUN event happen first for sub_worker_process.

Ensure the start_run event for sub_worker_process.

---

docs/faq.rst

This PR adds information about DNS propagation/cache and provides one way to resolve it.

Add one FAQ item to describe DNS cache/propagation and how to resolve it

---

docs/faq.rst

Fix a style issue on FAQ about server DNS propagation/caching.

---

nvflare/lighter/impl/master_template.yml

Fix a typo (should ready "security group")

Fix a typo

---

nvflare/app_common/workflows/scatter_and_gather.py

Ignore client results from unknown task_id in SAG.

Ignore unknown task result in SAG

---

nvflare/fuel/f3/communicator.py

Fix typo in fuel communicator

---

nvflare/fuel/flare_api/flare_api.py
nvflare/private/fed/server/job_cmds.py

Returns detailed reason on why abort job failed.

Fix abort job command return message

---

research/fed-ce/README.md
research/one-shot-vfl/README.md
research/one-shot-vfl/index.html

Fixes # .
Add readme for one-shot VFL paper now available on arxiv

Add readme for one-shot VFL paper [skip ci]

---

nvflare/apis/job_def.py
nvflare/private/fed/server/job_runner.py

Fixes # .
Fixed an issue the aborted job has no workspace from download_job.

update the abort_job status after the job complete

---

nvflare/private/fed/client/client_app_runner.py

Add missing parent constructor to nvflare/private/fed/client/client_app_runner.py

Add missing parent constructor

---

nvflare/private/fed/app/simulator/simulator_worker.py
nvflare/private/fed/server/server_commands.py

Fixes # .
Reduced the non-meaningful logs.

Reduced the non-meaningful logs.

---

nvflare/private/fed/client/client_json_config.py

Add default_task_fetch_interval, follow up of https://github.com/NVIDIA/NVFlare/pull/1621

Add default_task_fetch_interval

---

nvflare/private/fed/server/job_runner.py
nvflare/private/fed/server/training_cmds.py

Fixes # .
update the aborted job status immediately.

update the aborted job status immediately

---

examples/advanced/xgboost/histogram-based/requirements.txt
examples/advanced/xgboost/tree-based/requirements.txt

Fixes # .
Add item and corrections to the xgboost requirement files

Correction to xgboost requirements files [skip ci]

---

nvflare/private/fed/server/server_command_agent.py

Fixes # .
Fixed the server_command_agent AUTHENTICATION_ERROR reply.

Fixed the server_command_agent AUTHENTICATION_ERROR reply.

---

nvflare/private/fed/server/fed_server.py

Fixes # .
Update the _turn_to_cold to set to ColdState first.

Update the _turn_to_cold to set to ColdState first.

---

examples/advanced/brats18/pt/learners/supervised_learner.py
examples/advanced/cifar10/pt/learners/cifar10_learner.py
examples/advanced/prostate/prostate_2D/custom/learners/supervised_learner.py
examples/advanced/prostate/prostate_2D/custom/learners/supervised_monai_prostate_ditto_learner.py
examples/advanced/prostate/prostate_3D/custom/learners/supervised_learner.py
examples/advanced/prostate/prostate_3D/custom/learners/supervised_monai_prostate_ditto_learner.py
research/auto-fed-rl/src/autofedrl/autofedrl_cifar10_learner.py
research/fed-sm/jobs/fedsm_prostate/app/custom/learners/supervised_learner.py
research/fed-sm/jobs/fedsm_prostate/app/custom/learners/supervised_monai_prostate_fedsm_learner.py
research/quantifying-data-leakage/src/nvflare_gradinv/learners/cxr_learner.py

Fixes # .
update the computation of model diff from using "-" to using np.subtract

Improvement on model diff computation

---

integration/monai/examples/spleen_ct_segmentation_real-world/requirements.txt
integration/monai/flare_monai_integration.ipynb

- Remove tree command as that is not available in all envs.
- Update requirements.txt
- Add section about "preparing notebook environments"
- Fix paths typos

Update monai integration notebook [skip ci]

---

docs/example_applications_algorithms.rst
docs/getting_started.rst
docs/index.rst

Add section on notebook setup to docs and clean up index page, add sentence to link to install in quickstart.

Add notebook info [skip ci]

---

examples/README.md
examples/advanced/README.md
examples/advanced/brats18/README.md
examples/advanced/cifar10/README.md
examples/advanced/experiment-tracking/README.md
examples/advanced/federated-statistics/README.md
examples/advanced/nlp-ner/README.md
examples/advanced/prostate/README.md
examples/advanced/psi/README.md
examples/advanced/random_forest/README.md
examples/advanced/sklearn-kmeans/README.md
examples/advanced/sklearn-linear/README.md
examples/advanced/sklearn-svm/README.md
examples/advanced/vertical_federated_learning/README.md
examples/advanced/xgboost/README.md
examples/hello-world/README.md
examples/tutorials/README.md

Improve example readme [skip ci]

---

.github/workflows/markdown-links-check.yml
CONTRIBUTING.md
examples/README.md
examples/advanced/brats18/README.md
examples/advanced/experiment-tracking/tensorboard-streaming/README.md
examples/advanced/prostate/README.md
examples/advanced/sklearn-svm/README.md
examples/hello-world/README.md
examples/hello-world/hello-pt/README.md
examples/hello-world/hello-tf2/README.md
integration/monai/README.md
integration/monai/examples/README.md
research/auto-fed-rl/README.md

Add markdown link check workflow [skip ci] (#1660)

---

examples/advanced/brats18/requirements.txt
examples/advanced/cifar10/cifar10-real-world/requirements.txt
examples/advanced/cifar10/cifar10-sim/requirements.txt
examples/advanced/experiment-tracking/tensorboard-streaming/requirements.txt
examples/advanced/federated-policies/requirements.txt
examples/advanced/federated-statistics/df_stats/requirements.txt
examples/advanced/federated-statistics/image_stats/requirements.txt
examples/advanced/prostate/requirements.txt
examples/advanced/psi/user_email_match/requirements.txt
examples/advanced/random_forest/requirements.txt
examples/advanced/sklearn-kmeans/requirements.txt
examples/advanced/sklearn-linear/requirements.txt
examples/advanced/sklearn-svm/requirements.txt
examples/advanced/vertical_federated_learning/cifar10-splitnn/requirements.txt
examples/advanced/xgboost/histogram-based/requirements.txt
examples/advanced/xgboost/tree-based/requirements.txt
examples/hello-world/hello-cyclic/requirements.txt
examples/hello-world/hello-numpy-cross-val/requirements.txt
examples/hello-world/hello-numpy-sag/requirements.txt
examples/hello-world/hello-pt/requirements.txt
examples/hello-world/hello-tf2/requirements.txt
examples/hello-world/hw_pre_start.sh
examples/nvflare_setup.ipynb
examples/tutorials/tu_pre_start.sh
integration/monai/setup.py
integration/sample/README.md

Update requirements RC to real release

Update RC to real release

---

docs/whats_new.rst

Since updates were made to the PR for some updates on the what's new page, this keeps it consistent with the other branches:
https://github.com/NVIDIA/NVFlare/pull/1673
https://github.com/NVIDIA/NVFlare/pull/1674

Add changes from the PRs for the other branches for What's New updates [skip ci]

---

examples/advanced/sklearn-kmeans/jobs/sklearn_kmeans_base/app/custom/kmeans_learner.py
examples/advanced/sklearn-linear/jobs/sklearn_linear_base/app/custom/linear_learner.py
examples/advanced/sklearn-svm/jobs/sklearn_svm_base/app/custom/svm_learner.py
examples/advanced/vertical_federated_learning/cifar10-splitnn/src/splitnn/cifar10_learner_splitnn.py

Fix learners in examples

---

nvflare/app_opt/sklearn/sklearn_executor.py

- Follows PR https://github.com/NVIDIA/NVFlare/pull/1688 
- Fixed learner init method
- I will write another PR to unify this SKLearnExecutor with LearnerExecutor

Fix SKLearn executor

---

nvflare/fuel/f3/stats_pool.py

Fixes # .
Added the OVERALL column to the show_pool command. This column shows overall stats value (count, average, pecent, min, max) across all categories of the pool.

add overall stats to pool showing command

---

nvflare/private/fed/app/simulator/simulator_runner.py

- Fix minor problems in nvflare/private/fed/app/simulator/simulator_runner.py

Fix minor problems in simulator

---

examples/advanced/sklearn-svm/README.md
examples/advanced/sklearn-svm/jobs/sklearn_svm_base/app/config/config_fed_client.json
examples/advanced/sklearn-svm/jobs/sklearn_svm_base/app/custom/svm_learner.py
examples/advanced/sklearn-svm/prepare_job_config.sh
examples/advanced/sklearn-svm/requirements.txt
examples/advanced/sklearn-svm/run_experiment_simulator.sh
examples/advanced/sklearn-svm/utils/prepare_job_config.py
nvflare/fuel/f3/stats_pool.py

Fixes # .
Add cuml backend to SVM example. This is done by adding an alternative backend option and library import.

Add cuml backend to SVM example

---

nvflare/lighter/impl/cert.py
nvflare/lighter/provision.py
tests/unit_test/lighter/provision_test.py

This PR is pre-requisite for work for POC upgrade task. 
In this PR, we made three code refactoring changes, these changes is intended
1) make better organization of codes so that we can re-use the code 
2) abstract some properties such as server name, or subject in certification into methods, such change make it possible to overwrite the method if we like to change server_name or overwrite the subject

provision refactoring

---

ci/run_integration.sh
tests/integration_test/data/apps/tb_streaming/custom/custom_controller.py
tests/integration_test/data/projects/ha_1_servers_4_clients.yml
tests/integration_test/data/test_configs/standalone_job/image_stats.yml
tests/integration_test/example_registry.yml
tests/integration_test/run_integration_tests.sh
tests/integration_test/src/__init__.py
tests/integration_test/src/nvf_test_driver.py
tests/integration_test/src/utils.py
tests/integration_test/system_test.py
tests/integration_test/test_configs.yml

Fix integration tests by:
- cherry-pick #1592 
- cherry-pick #1683

Fix 2.3 integration tests

---

tests/integration_test/src/nvf_test_driver.py
tests/integration_test/src/utils.py
tests/unit_test/apis/job_def_test.py
tests/unit_test/lighter/provision_test.py

Fix integration test failure due to "show_stats" command return structure changes in the PR #1722

Fix HA tests

---

tests/integration_test/src/nvf_test_driver.py

The proper fix on dev branch: #1678 change too many files, this is a one-time hot-fix just for 2.3 branch to pass the integration tests.

[2.3] Add sleep time before admin api create/auto-login

---

integration/monai/examples/spleen_ct_segmentation_local/README.md
integration/monai/examples/spleen_ct_segmentation_sim/README.md

Fix readme typo [skip ci]

---

.github/workflows/premerge.yml

Remove github workflow branch restriction

remove github workflow branch restriction [skip ci]

---

nvflare/apis/filter.py
nvflare/app_common/executors/statistics/statistics_executor_exception.py
nvflare/fuel/flare_api/api_spec.py
nvflare/security/logging.py

Follow suggestions from official doc and https://github.com/NVIDIA/NVFlare/pull/1743

Replace BaseException with Exception

---

integration/nemo/nemo_nvflare/learner_executor.py

Fixes # .
NeMo integration: Check to initialize learner.

NeMo integration: Check to initialize learner

---

integration/nemo/nemo_nvflare/learner_executor.py

Fixes # .
fix initialize logic to work with latest dev

NeMo integration: fix initialize logic

---

examples/README.md
examples/advanced/README.md
examples/advanced/fl_hub/README.md
examples/advanced/fl_hub/config/site_a/hub_client.json
examples/advanced/fl_hub/config/site_a/hub_server.json
examples/advanced/fl_hub/config/site_a/resources.json
examples/advanced/fl_hub/config/site_b/hub_client.json
examples/advanced/fl_hub/config/site_b/hub_server.json
examples/advanced/fl_hub/config/site_b/resources.json
examples/advanced/fl_hub/jobs/numpy-cross-val/README.md
examples/advanced/fl_hub/jobs/numpy-cross-val/meta.json
examples/advanced/fl_hub/jobs/numpy-cross-val/t1_app/config/config_fed_server.json
examples/advanced/fl_hub/jobs/numpy-cross-val/t2a_app/config/config_fed_client.json
examples/advanced/fl_hub/jobs/numpy-cross-val/t2a_app/config/config_fed_server.json
examples/advanced/fl_hub/jobs/numpy-cross-val/t2b_app/config/config_fed_client.json
examples/advanced/fl_hub/jobs/numpy-cross-val/t2b_app/config/config_fed_server.json
examples/advanced/fl_hub/shutdown_systems.sh
examples/advanced/fl_hub/start_t1.sh
examples/advanced/fl_hub/start_t2a.sh
examples/advanced/fl_hub/start_t2b.sh
examples/advanced/fl_hub/workspaces/t1_project.yml
examples/advanced/fl_hub/workspaces/t2a_project.yml
examples/advanced/fl_hub/workspaces/t2b_project.yml

Fixes # .
Reopen https://github.com/NVIDIA/NVFlare/pull/1143 to address final comments.
Example of hierarchical interaction between several levels of nvflare FL systems, e.g. Tier-1 (hub) and Tier-2 (sub-systems).
Adds example to show a two-level hub system.

Re-add FL hub example

---

tests/unit_test/apis/dxo_test.py

Fixes # .
Add a unit test for DXO functionalities.

Add DXO unit test

---

docs/publications_and_talks.md
docs/publications_and_talks.rst

Removes dead link: https://www.gpuhackathons.org/event/monai-miccai-bootcamp-2021

Remove dead link on main [skip ci]

---

docs/publications_and_talks.rst

Remove dead link https://www.gpuhackathons.org/event/monai-miccai-bootcamp-2021

Remove dead link [skip ci]

---

docs/publications_and_talks.rst

Remove dead link https://www.gpuhackathons.org/event/monai-miccai-bootcamp-2021

[2.3] Remove dead link [skip ci]

---

nvflare/app_common/aggregators/accumulate_model_aggregator.py
nvflare/app_common/widgets/streaming.py
nvflare/fuel/utils/deprecated.py
tests/unit_test/fuel/utils/deprecated_test.py
tests/unit_test/lighter/utils_test.py

To support 3.8/3.9/3.10 without introducing new dependencies, we write our own deprecated decorator
- Add deprecated
- Add unit test

Fix deprecated

---

nvflare/security/logging.py
tests/unit_test/fuel/utils/component_builder_test.py

[2.3] Include exception type

---

examples/advanced/random_forest/README.md
examples/advanced/random_forest/random_forest.ipynb
examples/advanced/sklearn-linear/README.md
examples/advanced/sklearn-linear/prepare_data.sh
examples/advanced/sklearn-linear/sklearn_linear_higgs.ipynb
examples/advanced/xgboost/README.md
examples/advanced/xgboost/data_job_setup.ipynb

HIGGS dataset link has been moved.

Fix HIGGS dataset link

---

runtest.sh
tests/unit_test/app_common/utils/fl_model_utils_test.py
tests/unit_test/private/fed/app/simulator/simulator_runner_test.py

- Check code styles also with examples and tests folder

Enhance runtest.sh

---

tests/integration_test/data/test_configs/authorization/abort_job.yml
tests/integration_test/data/test_configs/authorization/clone_job.yml
tests/integration_test/data/test_configs/authorization/shell_commands.yml
tests/integration_test/data/test_configs/authorization/submit_job.yml
tests/integration_test/data/test_configs/authorization/test_diff_job_config.yml
tests/integration_test/src/nvf_test_driver.py

- Cherry-pick https://github.com/NVIDIA/NVFlare/pull/1809

[main] Add exception type name in tests' error messages

---

tests/integration_test/data/test_configs/authorization/abort_job.yml
tests/integration_test/data/test_configs/authorization/clone_job.yml
tests/integration_test/data/test_configs/authorization/shell_commands.yml
tests/integration_test/data/test_configs/authorization/submit_job.yml
tests/integration_test/data/test_configs/authorization/test_diff_job_config.yml
tests/integration_test/src/nvf_test_driver.py

Follows PR https://github.com/NVIDIA/NVFlare/pull/1789
The error messages now include the Exception Type, so we need to update the integration test assert messages.
- Update integration test assert messages

[2.3] Add exception type name in tests' error messages

---

examples/advanced/federated-statistics/df_stats.ipynb
examples/advanced/federated-statistics/df_stats/README.md
examples/advanced/random_forest/README.md
examples/advanced/random_forest/random_forest.ipynb
examples/advanced/sklearn-linear/README.md
examples/advanced/sklearn-linear/prepare_data.sh
examples/advanced/sklearn-linear/sklearn_linear_higgs.ipynb
examples/advanced/xgboost/README.md
examples/advanced/xgboost/data_job_setup.ipynb

HIGGS dataset link changed.
- Cherry-pick #1801 #1805 to 2.3

[2.3] Fix HIGGS links

---

examples/advanced/federated-statistics/df_stats.ipynb
examples/advanced/federated-statistics/df_stats/README.md
examples/advanced/random_forest/README.md
examples/advanced/random_forest/random_forest.ipynb
examples/advanced/sklearn-linear/README.md
examples/advanced/sklearn-linear/prepare_data.sh
examples/advanced/sklearn-linear/sklearn_linear_higgs.ipynb
examples/advanced/xgboost/README.md
examples/advanced/xgboost/data_job_setup.ipynb

HIGGS link changed.
Also add notes saying something the UCI website is not available.
- Cherry-pick #1801 #1805

[main] Fix HIGGS link

---

examples/advanced/fl_hub/config/site_a/hub_client.json
examples/advanced/fl_hub/config/site_a/hub_server.json
examples/advanced/fl_hub/config/site_b/hub_client.json
examples/advanced/fl_hub/config/site_b/hub_server.json
nvflare/app_common/hub/hub_controller.py
nvflare/app_common/hub/hub_executor.py
nvflare/fuel/utils/constants.py
nvflare/fuel/utils/pipe/file_name_utils.py
nvflare/fuel/utils/pipe/file_pipe.py
nvflare/fuel/utils/pipe/fobs_file_accessor.py
nvflare/fuel/utils/pipe/pipe.py
nvflare/fuel/utils/pipe/pipe_handler.py
nvflare/fuel/utils/validation_utils.py

- Add a "Mode" to Pipe `__init__`
- Rename `PipeMonitor` to `PipeHandler`

Refactor pipe and rename pipe monitor

---

nvflare/lighter/utils.py
nvflare/private/fed/client/training_cmds.py
nvflare/private/fed/server/job_runner.py
tests/unit_test/lighter/utils_test.py

This PR is created from cherry-picking 77daca3a2a2e99efaba4cb354a0f56f942a1718b
Add missing cert chain verification on submitted job signatures
Add unit test on verify_folder_signature

Add missing cert chain verification on submitted job signatures

---

nvflare/fuel/f3/comm_config.py
nvflare/fuel/f3/communicator.py
nvflare/fuel/f3/drivers/driver_manager.py
nvflare/fuel/utils/config_service.py
tests/unit_test/data/custom_drivers/com/__init__.py
tests/unit_test/data/custom_drivers/com/example/__init__.py
tests/unit_test/data/custom_drivers/com/example/warp_driver.py
tests/unit_test/data/custom_drivers/config/comm_config.json
tests/unit_test/fuel/f3/drivers/custom_driver_test.py
tests/unit_test/fuel/f3/drivers/driver_manager_test.py

Fixes FLARE-1441
Ported custom driver change to branch 2.3

Merged custom driver to branch 2.3

---

nvflare/fuel/f3/comm_config.py
nvflare/fuel/f3/communicator.py
nvflare/fuel/f3/drivers/driver_manager.py
nvflare/fuel/utils/config_service.py
tests/unit_test/data/custom_drivers/com/__init__.py
tests/unit_test/data/custom_drivers/com/example/__init__.py
tests/unit_test/data/custom_drivers/com/example/warp_driver.py
tests/unit_test/data/custom_drivers/config/comm_config.json
tests/unit_test/fuel/f3/drivers/custom_driver_test.py
tests/unit_test/fuel/f3/drivers/driver_manager_test.py

Fixes FLARE-1440
Ported custom driver changes to main branch

Custom Driver for Main Branch [no ci]

---

nvflare/app_common/executors/file_pipe_launcher_executor.py
nvflare/app_common/executors/launcher_executor.py

- Adds LauncherExecutor
- Depends on #1763 
- Works together with #1763 and #1837

Add LauncherExecutor

---

docs/programming_guide/data_exchange_object.rst
docs/programming_guide/fl_component.rst
examples/advanced/random_forest/random_forest.ipynb

Fixes documentation issues found by @BPDanek
Cherry-pick #1833 #1834 #1835

Update doc 2.3 [skip ci]

---

nvflare/app_common/model_exchange/__init__.py
nvflare/app_common/model_exchange/file_pipe_model_exchanger.py
nvflare/app_common/model_exchange/model_exchanger.py
nvflare/fuel/utils/pipe/file_accessor.py
nvflare/fuel/utils/pipe/fobs_file_accessor.py

- Adds ModelExchanger, this will be used on the custom client code.
- Adds FilePipeModelExchanger, for simplify client config if they choose to use FilePipe
- Can work together with #1783 or use it in custom executors

Adds ModelExchanger

---

nvflare/private/fed/server/job_meta_validator.py
tests/integration_test/data/test_configs/authorization/test_diff_job_config.yml

Fixes auth integration test by fixing the error message.
https://github.com/NVIDIA/NVFlare/pull/1824 changes the error message, this PR fix testing's assertion text.

Fix auth integration test

---

nvflare/fuel/f3/cellnet/new_cell.py
nvflare/fuel/f3/streaming/blob_streamer.py
nvflare/fuel/f3/streaming/stream_const.py
nvflare/private/fed/app/client/sub_worker_process.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/client/fed_client.py
nvflare/private/fed/client/fed_client_base.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_command_agent.py

This PR provides NewCell class that supports send_request API of original Cell class by utilizing StreamCell's send_blob and callback mechanism.  Upper layer applications require nearly no changes when sending/receiving large models.

New Cell to provide layers to support original Cell API

---

nvflare/fuel/f3/cellnet/new_cell.py
nvflare/fuel/f3/streaming/stream_const.py
nvflare/private/fed/app/client/sub_worker_process.py
nvflare/private/fed/app/deployer/simulator_deployer.py
nvflare/private/fed/app/simulator/simulator_worker.py
nvflare/private/fed/client/admin.py
nvflare/private/fed/client/fed_client.py
nvflare/private/fed/client/fed_client_base.py
nvflare/private/fed/server/admin.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_command_agent.py

This PR prepares the NewCell class for upper layer application.  It does not replace existing cell yet as the applications still import Cell.  Once all features are ready, we can switch to NewCell by removing import Cell and the comment of import NewCell as Cell.

New cell fix

---

nvflare/fuel/f3/streaming/byte_receiver.py

Fixes FLARE-1480
This fixes a bug that causes streaming ending prematurely and causes FOBS error.

Fixes an End-of-Stream bug

---

nvflare/private/fed/client/communicator.py

Add client heartbeat log

---

examples/advanced/cifar10/cifar10-real-world/README.md
examples/advanced/cifar10/cifar10-real-world/plot-requirements.txt
examples/advanced/cifar10/cifar10-real-world/requirements.txt
examples/advanced/cifar10/cifar10-sim/README.md
examples/advanced/cifar10/cifar10-sim/plot-requirements.txt
examples/advanced/cifar10/cifar10-sim/requirements.txt
examples/advanced/xgboost/tree-based/README.md
examples/advanced/xgboost/tree-based/plot-requirements.txt
examples/advanced/xgboost/tree-based/requirements.txt

Fixes #1843 .
- Separate plot-requirements from execution requirements

Separate plot-requirements out

---

nvflare/fuel/f3/cellnet/cell.py

In simulator, the client job cell couldn't find route to server job cell. This fixes the problem.

Fixes the streaming problem in simulator

---

nvflare/private/fed/app/client/sub_worker_process.py
nvflare/private/fed/app/deployer/simulator_deployer.py
nvflare/private/fed/app/simulator/simulator_worker.py
nvflare/private/fed/client/admin.py
nvflare/private/fed/client/fed_client.py
nvflare/private/fed/client/fed_client_base.py
nvflare/private/fed/server/admin.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_command_agent.py

This PR enables NewCell to support stream API.

Enable NewCell

---

examples/advanced/federated-statistics/df_stats/requirements.txt
examples/advanced/federated-statistics/df_stats/utils/prepare_data.py

remove wget to fix broken example. This is the same as https://github.com/NVIDIA/NVFlare/pull/1878 for dev branch

[2.3 branch] remove wget in df_stats example

---

nvflare/apis/event_type.py
nvflare/apis/fl_component.py
nvflare/apis/fl_constant.py
nvflare/apis/fl_exception.py
nvflare/apis/workspace.py
nvflare/fuel/common/excepts.py
nvflare/fuel/common/exit_codes.py
nvflare/fuel/f3/drivers/aio_context.py
nvflare/fuel/f3/drivers/aio_grpc_driver.py
nvflare/fuel/f3/mpm.py
nvflare/fuel/utils/dict_utils.py
nvflare/fuel/utils/json_scanner.py
nvflare/fuel/utils/obj_utils.py
nvflare/private/defs.py
nvflare/private/event.py
nvflare/private/fed/app/client/client_train.py
nvflare/private/fed/app/client/worker_process.py
nvflare/private/fed/app/fl_conf.py
nvflare/private/fed/app/server/runner_process.py
nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/client/client_app_runner.py
nvflare/private/fed/client/client_executor.py
nvflare/private/fed/client/client_json_config.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_app_runner.py
nvflare/private/fed/server/server_json_config.py
nvflare/private/fed/server/server_runner.py
nvflare/private/fed/utils/fed_utils.py
nvflare/private/fed_json_config.py
nvflare/private/json_configer.py

Fixes # .
This PR implements the following:
- Enhanced UnsafeJob processing by proactively aborting the job on all clients when UnsafeJob error is returned.
- Implemented event-based unsafe component detection and processing (see https://docs.google.com/document/d/1g07KTFBwcQS1vJjzz1icYCcZwWeTLmN3na1DauwPLYA/edit)
- Define gRPC's keepalive_time_ms to 120000 as default value. This is to make gRPC's keepalive more frequent to avoid the problem that the network provider reset TCP after idling too long.
- Improved cancelled task handling in AIO
- Improved logger creation by naming with qualified class name. This will make it easier to configure loggers to different log level.

Support Roche requirements and fixes

---

examples/hello-world/ml-to-fl/jobs/client_api1/app/custom/cifar10.py
examples/hello-world/ml-to-fl/jobs/client_api2/app/custom/cifar10.py
examples/hello-world/ml-to-fl/jobs/decorator/app/custom/cifar10.py
nvflare/app_common/abstract/fl_model.py
nvflare/client/lightning/__init__.py

- Use meaningful meta in "ml-to-fl"
- Change default FLModel params_type to None
- Remove warnings

Fix examples and FLModel

---

tests/integration_test/src/nvf_test_driver.py

- Call `_get_run_state` before checking it

Fix integration test

---

runtest.sh
setup.cfg

add mac specific setup (removing HE and openmind.psi dependency)

add Mac specific setup

---

nvflare/apis/event_type.py
nvflare/apis/fl_component.py
nvflare/apis/fl_constant.py
nvflare/apis/fl_exception.py
nvflare/apis/workspace.py
nvflare/fuel/common/exit_codes.py
nvflare/fuel/f3/drivers/aio_context.py
nvflare/fuel/f3/drivers/aio_grpc_driver.py
nvflare/fuel/f3/mpm.py
nvflare/fuel/utils/dict_utils.py
nvflare/fuel/utils/json_scanner.py
nvflare/fuel/utils/obj_utils.py
nvflare/private/defs.py
nvflare/private/event.py
nvflare/private/fed/app/client/client_train.py
nvflare/private/fed/app/client/worker_process.py
nvflare/private/fed/app/fl_conf.py
nvflare/private/fed/app/server/runner_process.py
nvflare/private/fed/app/server/server_train.py
nvflare/private/fed/client/client_app_runner.py
nvflare/private/fed/client/client_executor.py
nvflare/private/fed/client/client_json_config.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_app_runner.py
nvflare/private/fed/server/server_json_config.py
nvflare/private/fed/server/server_runner.py
nvflare/private/fed/utils/fed_utils.py
nvflare/private/fed_json_config.py
nvflare/private/json_configer.py

This PR was cherry-picked from 2.3.2 #1868.

Cherry-picked from 2.3.2 #1868

---

examples/advanced/brats18/submit_job.py
examples/advanced/cifar10/cifar10-real-world/submit_job.py
integration/monai/examples/spleen_ct_segmentation_local/submit_job.py
nvflare/fuel/flare_api/flare_api.py
nvflare/fuel/hci/client/api.py
nvflare/fuel/hci/client/api_spec.py
nvflare/fuel/hci/client/cli.py
nvflare/fuel/hci/client/file_transfer.py
nvflare/fuel/hci/client/fl_admin_api.py
nvflare/fuel/hci/client/fl_admin_api_runner.py
tests/integration_test/src/utils.py
tests/integration_test/system_test.py

Cherry-pick #1894
* revert some changes from POC update commit that caused issues
* fix ci
* rename poc to insecure

Revert some changes from POC update commit that caused issues (#1894)

---

examples/hello-world/ml-to-fl/jobs/lightning_client_api/app/config/config_fed_server.json
examples/hello-world/ml-to-fl/jobs/lightning_client_api/app/custom/autoencoder.py

- Add model persist
- Add model select based on metrics

Enhance lightning example

---

nvflare/private/fed/client/communicator.py

Cherry-pick Add client heartbeat log (#1864)

Cherry-pick Add client heartbeat log (#1864)

---

CONTRIBUTING.md
README.md
docs/contributing.rst
docs/examples/hello_cross_val.rst
docs/examples/hello_pt.rst
docs/examples/hello_scatter_and_gather.rst
docs/examples/hello_tf2.rst
docs/examples/hello_world_examples.rst
docs/getting_started.rst

Update references to dev after change in branch, update broken links [skip ci]

---

integration/monai/examples/spleen_ct_segmentation_local/job/app/config/config_fed_client.json
integration/monai/examples/spleen_ct_segmentation_local/requirements.txt
integration/monai/examples/spleen_ct_segmentation_sim/requirements.txt

Fixes [#1885](https://github.com/NVIDIA/NVFlare/issues/1885).
`MonaiAlgo` argument names have changed in recent 1.2.0 release. Updating local client job config to reflect the change.

Fix MonaiAlgo args [skip ci]

---

nvflare/fuel/f3/cellnet/new_cell.py

This PR uses future's waiter to wait until timeout.  It removes the time.sleep and has better loop structures.

Use future waiter

---

examples/hello-world/ml-to-fl/README.md

Fix typos [skip ci]

---

research/condist-fl/README.md

Fixes # .
Add reasearch folder for "ConDistFL: Conditional Distillation for Federated Learning from Partially Annotated Data" ([arXiv:2308.04070](https://arxiv.org/abs/2308.04070))

Add reasearch folder for "ConDistFL: Conditional Distillation for Federated Learning from Partially Annotated Data" [skip ci]

---

research/condist-fl/README.md

Fixes # .
Add ConDistFL readme to dev branch.

Add ConDistFL to dev branch [skip ci]

---

.github/workflows/blossom-ci.yml

Add Sean to build command

---

nvflare/fuel/f3/cellnet/cell_cipher.py

Add CellCipher for secure message encryption/decryption
Add SessionKeyManager to handle key exchange and management

Secure message

---

nvflare/app_common/abstract/fl_model.py
nvflare/app_common/utils/fl_model_utils.py

Use explicit argument name instead of kwargs

Fix fl model utils

---

nvflare/fuel/f3/cellnet/cell.py

Fixes # .
Removed the not used import in cell.py. (temporary)

Removed the not used import in cell.py (temporary)

---

nvflare/fuel/f3/cellnet/cell_cipher.py

This PR adds SimpleCellCipher to simplify the session key and cipher.

Add SimpleCellCipher to replace session key manager and cell cipher

---

examples/tutorials/job_cli.ipynb

Polish notebook for Job CLI by making language more consistent.

Polish notebook for Job CLI [skip ci]

---

nvflare/apis/impl/job_def_manager.py
nvflare/apis/job_def_manager_spec.py
nvflare/apis/storage.py
nvflare/app_common/storages/filesystem_storage.py
nvflare/private/fed/server/job_cmds.py

Fixes # .
Create the symlinks from the job storage to the download_job folder. Prepare for the download_job streaming command.

prepare the download_job data files.

---

nvflare/fuel/f3/cellnet/cell.py
nvflare/private/defs.py

This PR adds broadcast_request and includes aux_communication channel to Cell.

Add broadcast and aux_communication channel

---

nvflare/apis/controller_spec.py
nvflare/apis/impl/task_controller.py
nvflare/apis/server_engine_spec.py
nvflare/app_common/ccwf/server_ctl.py
nvflare/app_common/ccwf/swarm_client_ctl.py
nvflare/private/aux_runner.py
nvflare/private/fed/client/client_engine_executor_spec.py
nvflare/private/fed/client/client_run_manager.py
nvflare/private/fed/client/client_runner.py
nvflare/private/fed/server/server_engine.py
nvflare/private/fed/server/server_runner.py
nvflare/private/fed/simulator/simulator_server.py
nvflare/widgets/fed_event.py

This PR handles the new argument 'secure' in cell's methods.  And adds the new argument 'secure' in Task so client task control can set it in Task.

Add secure argument to Task and set secure argument in cell's call.

---

nvflare/fuel/f3/cellnet/cell.py

This PR fixes a race condition in broadcast of Cell.  The message header should be deepcopied into individual target message so that the stream_req_id would not be overwritten.

Fix a multithread race condition in broadcast of Cell

---

examples/advanced/cifar10/cifar10-real-world/shutdown_fl_run.sh

Fixes #2002 .
New stop_fl.sh requires y/N input.

Fix shutdown_fl_run.sh

---

nvflare/fuel/utils/pipe/pipe_handler.py

deque popleft is O(1) operation VS list pop(0) is O(n)

Enhance PipeHandler

---

integration/monai/examples/README.md

- Update "fl_simulator" doc link in integration/monai/examples/README.md

Update doc link in readme [skip ci]

---

nvflare/private/fed/app/deployer/simulator_deployer.py

federated_client.register does not take in register_data

Fix simulator deployer

---

nvflare/apis/utils/fl_context_utils.py
nvflare/private/fed/client/command_agent.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/server/server_command_agent.py
nvflare/private/fed/server/server_commands.py

This PR adds a utility function which generates peer fl context in a more efficient way and update a few locations with this function

Improve how to generate peer fl context

---

nvflare/apis/fl_constant.py
nvflare/apis/impl/controller.py
nvflare/apis/responder.py
nvflare/private/fed/client/client_runner.py
nvflare/private/fed/client/communicator.py
nvflare/private/fed/client/fed_client_base.py
nvflare/private/fed/server/server_runner.py

Fixes # .
- Changed CP's heartbeat to use a short timeout (maint_msg_timeout) to fix the HB bug.
- Added retry logic for submitting task results
-

Fix AV FL Issues

---

nvflare/dashboard/application/blob.py
nvflare/dashboard/application/models.py
nvflare/lighter/dummy_project.yml
nvflare/lighter/ha_project.yml
nvflare/lighter/impl/master_template.yml
nvflare/lighter/impl/static_file.py

Add support for scheme in provision.

Add scheme to provision

---

nvflare/lighter/dummy_project.yml
nvflare/lighter/ha_project.yml
nvflare/lighter/impl/cert.py

Same PR as #2072 but targeting main.

Add support for listen_host

---

nvflare/fuel/f3/sfm/sfm_conn.py

This PR fixes false alarm in QA script result checking logic.

Workaround for QA script

---

nvflare/apis/fl_constant.py
nvflare/app_common/utils/fl_model_utils.py

- Support cross site eval in FLModelUtil

Support cross site eval in FLModelUtil

---

docs/glossary.rst
docs/programming_guide/controllers/cross_site_model_evaluation.rst
docs/real_world_fl/notes_on_large_models.rst
docs/user_guide/confidential_computing.rst
docs/user_guide/nvflare_cli/dashboard_command.rst
docs/user_guide/nvflare_cli/poc_command.rst

docs: fix typos [skip ci]

---

job_templates/sag_pt/config_fed_client.conf
job_templates/sag_pt/config_fed_server.conf
job_templates/sag_pt_ddp/app_1/config_fed_client.conf
job_templates/sag_pt_ddp/app_2/config_fed_client.conf
job_templates/sag_pt_ddp/app_server/config_fed_server.conf
job_templates/sag_pt_deploy_map/app_1/config_fed_client.conf
job_templates/sag_pt_deploy_map/app_2/config_fed_client.conf
job_templates/sag_pt_deploy_map/app_server/config_fed_server.conf

Fix typos in job templates

---

nvflare/fuel/f3/cellnet/core_cell.py
nvflare/fuel/f3/cellnet/utils.py
nvflare/fuel/f3/connection.py
nvflare/fuel/f3/drivers/connector_info.py
nvflare/fuel/f3/sfm/conn_manager.py
nvflare/fuel/f3/stream_cell.py
nvflare/fuel/f3/streaming/blob_streamer.py
nvflare/fuel/f3/streaming/byte_receiver.py
nvflare/fuel/f3/streaming/byte_streamer.py
nvflare/fuel/f3/streaming/file_streamer.py
nvflare/fuel/f3/streaming/stream_utils.py
nvflare/fuel/utils/buffer_list.py
nvflare/fuel/utils/fobs/buf_list_stream.py
nvflare/fuel/utils/fobs/lobs.py
tests/unit_test/fuel/f3/streaming/streaming_test.py
tests/unit_test/fuel/utils/fobs/fobs_test.py

1. Added buffer list support in F3 and LOBS to reduce memory usage.
2. Added stats for streaming.
3. Changed connection wait timer to an event so it can be interrupt right away.

Buffer List Support

---

nvflare/app_opt/lightning/callbacks.py

Some lightning trainer does NOT have scaler, need to support that scenario.

Fix RestoreState callback

---

examples/advanced/gnn/README.md
examples/advanced/gnn/requirements.txt

Fixes # .
For env preparation steps, torch geometric needs special treatment

Update gnn example

---

docs/real_world_fl/notes_on_large_models.rst

This PR update the document on large model.  It removed the bytes <-> objects conversion from user codes, as it is now handled automatically by underlying codes.

Update the document on large model experiments.

---

.readthedocs.yaml
docs/example_applications_algorithms.rst

Fixes readthedocs config and link in docs

Fixes readthedocs config and link in docs [skip ci]

---

.readthedocs.yaml

Remove old python.version key (replaced by build.os.python)

Fix docs build

---

nvflare/app_common/abstract/launcher.py
nvflare/app_common/launchers/subprocess_launcher.py
tests/unit_test/app_common/launchers/subprocess_launcher_test.py

- Support both printing logs and write to a logfile for the SubprocessLauncher launched processes

Print logs and write to logfile at the same time

---

examples/tutorials/job_cli.ipynb
nvflare/tool/job/config/configer.py
tests/unit_test/tool/job/config/configer_test.py

1. expand the function to allow key in path format ( dot notation) 
2. add new section on JOB CLI tutorial

Job CLI Upgrade to support path notation

---

integration/nemo/examples/peft/peft.ipynb
job_templates/cyclic_cc_pt/config_fed_client.conf
job_templates/cyclic_cc_pt/info.md
job_templates/cyclic_pt/config_fed_client.conf
job_templates/cyclic_pt/info.md
job_templates/sag_nemo/app_1/config_fed_client.conf
job_templates/sag_nemo/app_2/config_fed_client.conf
job_templates/sag_nemo/app_3/config_fed_client.conf
job_templates/sag_nemo/info.md
job_templates/sag_pt/config_fed_client.conf
job_templates/sag_pt/info.md
job_templates/sag_pt_deploy_map/app_1/config_fed_client.conf
job_templates/sag_pt_deploy_map/app_2/config_fed_client.conf
job_templates/sag_pt_deploy_map/info.md
job_templates/sag_pt_gnn_supervised/app_1/config_fed_client.conf
job_templates/sag_pt_gnn_supervised/app_2/config_fed_client.conf
job_templates/sag_pt_gnn_supervised/info.md
job_templates/sag_pt_gnn_unsupervised/app_1/config_fed_client.conf
job_templates/sag_pt_gnn_unsupervised/app_2/config_fed_client.conf
job_templates/sag_pt_gnn_unsupervised/info.md
job_templates/sag_tf/config_fed_client.conf
job_templates/sag_tf/info.md
job_templates/swarm_cse_pt/config_fed_client.conf
nvflare/fuel/utils/pipe/file_pipe.py

Update configurations of LauncherExecutor

Update configurations of LauncherExecutor

---

nvflare/client/__init__.py
nvflare/client/api.py
nvflare/client/lightning/__init__.py

- Remove ``receive_global_model``
- Users should use ``while flare.is_running()`` for loop

Remove receive_global_model

---

examples/advanced/gnn/README.md

Fix gnn job templates link [skip ci]

---

.github/DISCUSSION_TEMPLATE/q-a.yml

Add a template for Q&A so users will provide required information for us to answer their questions

Add discussion Q&A template [skip ci]

---

docs/user_guide.rst
docs/user_guide/client_api.rst
nvflare/app_common/abstract/fl_model.py

- Update client api doc and docstrings

Update client api doc and docstrings

---

nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/app/simulator/simulator_worker.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_json_config.py
tests/unit_test/private/fed/app/simulator/simulator_runner_test.py

Fix issues introduced by PR #2145 that prevents simulator from running.

Fix simulator

---

nvflare/app_common/executors/launcher_executor.py
nvflare/app_common/executors/task_exchanger.py
nvflare/app_common/hub/hub_app_deployer.py
nvflare/app_common/hub/hub_controller.py
nvflare/app_common/hub/hub_executor.py
nvflare/app_common/utils/fl_model_utils.py
nvflare/client/flare_agent.py
nvflare/fuel/utils/constants.py
nvflare/fuel/utils/pipe/cell_pipe.py
nvflare/fuel/utils/pipe/file_pipe.py
nvflare/fuel/utils/pipe/pipe.py
nvflare/fuel/utils/pipe/pipe_handler.py

Rebase Original Changes in https://github.com/yanchengnv/NVFlare/blob/improve_grpc_24 on top of main branch:
- Add TaskExchanger
- Add FlareAgent
- Re-factor Hub related code based on TaskExchanger
- Enhance PipeHandler for status_cb and resend mechanism
New changes:
- Change "FLModelUtils.from_shareable": DON'T need fl_ctx as input argument, shareable should be sufficient
- Add FlareAgentWithFLModel

Add TaskExchanger and FlareAgent

---

docs/conf.py
docs/example_applications_algorithms.rst
docs/examples/federated_statistics_overview.rst
docs/examples/fl_experiment_tracking_mlflow.rst
docs/examples/hello_cross_val.rst
docs/examples/hello_pt.rst
docs/examples/hello_scatter_and_gather.rst
docs/examples/hello_tf2.rst
docs/examples/hello_world_examples.rst
docs/examples/tensorboard_streaming.rst
docs/getting_started.rst
docs/key_features.rst
docs/programming_guide/controllers/cross_site_model_evaluation.rst
docs/programming_guide/controllers/cyclic_workflow.rst
docs/programming_guide/controllers/scatter_and_gather_workflow.rst
docs/programming_guide/experiment_tracking.rst
docs/programming_guide/filters.rst
docs/real_world_fl.rst
docs/real_world_fl/FLAdminAPI.rst
docs/release_notes/flare_220.rst
docs/release_notes/flare_230.rst
docs/release_notes/flare_240.rst
docs/user_guide/client_api.rst
docs/user_guide/nvflare_cli/job_cli.rst
docs/user_guide/security/identity_security.rst

Add variable doc build version for github links

---

examples/advanced/swarm_learning/README.md

The job create "-sd" option will copy the whole thing inside the job, we don't want to copy all cifar 10 example scripts/data/jobs into swarm learning job.

Fix Swarm learning README [skip ci]

---

nvflare/tool/job/config/config_indexer.py
nvflare/tool/job/config/configer.py
tests/unit_test/tool/job/config/configer_test.py

- Fix split_array_key
- Fix get_app_name_from_path
- Add unit tests
- Enhance type hints

Fix job cli issues

---

nvflare/fuel/utils/experimental.py
tests/unit_test/fuel/utils/experimental_test.py

Fixes # .
Update experimental decorator for functions and classes. Add new tests

Experimental decorator for functions and classes

---

nvflare/apis/fl_constant.py
nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/app/simulator/simulator_worker.py

Fixes # .
Fixed the missing simulator END_RUN event.
Added a step to handle the END_RUN event when running the simulator.

Fixed the missing simulator END_RUN event

---

examples/advanced/xgboost/histogram-based/requirements.txt

Update requirements for xgboost example (https://nvbugspro.nvidia.com/bug/4418021)

Update xgboost example requirements [skip ci]

---

job_templates/sag_pt_he/config_fed_client.conf
job_templates/sag_pt_he/config_fed_server.conf
job_templates/sag_pt_he/info.conf
job_templates/sag_pt_he/info.md
job_templates/sag_pt_he/meta.conf
nvflare/app_opt/pt/params_converter.py

Add tensor reshape to pt ParamsConverter to support HE for client API

Add he support to pt params converter

---

examples/hello-world/step-by-step/cifar10/sag_he/sag_he.ipynb
examples/tutorials/setup_poc.ipynb
nvflare/tool/poc/poc_commands.py

- Fix POC mode HE support by reordering HEBuilder
- Added HE step-by-step example using client API

Fix POC HE mode, add HE step-by-step example

---

nvflare/private/fed/client/client_runner.py

Fixes # .
Changed the TASK_UNKNOWN to log debug

Changed the TASK_UNKNOWN to log debug

---

nvflare/private/fed/app/simulator/simulator_runner.py

Fixes # 
Fixed the Simulator run_status issue.
Simulator run() is not return back the correct return_code for several cases. This PR ensure the correct RC run_status.

Fix simulator rc

---

examples/hello-world/hello-tf2/README.md

Fixes # .
TF2 does not allow multiple processes to be running on a single GPU at the same time. Updated the readme for the instructions.

updated the hello-TF2 readme [skip ci]

---

nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/app/simulator/simulator_worker.py

Fixes # .
Simulator run the client END_RUN event after all the clients and server finished the running sessions. The already in session clients can detect and run the END_RUN event while it's in running status. This will avoid the un-necessary ClientRunner initialization. Only call the END_RUN for the "swapped out" clients.

Enhanced the Simulator client end_run solution 

---

integration/nemo/examples/peft/peft.ipynb

Fixes # .
Add spawn start method to enable simulation with NeMo models.

[2.4] Fix nemo peft notebook

---

integration/nemo/examples/peft/README.md
integration/nemo/examples/prompt_learning/README.md
integration/nemo/examples/supervised_fine_tuning/README.md

Fixes # .
* Update instructions to include docker run commands recommended by [NeMo](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/nemo). 
* Add hardware requirement sections.

[2.4] Update nemo instructions

---

docs/user_guide/nvflare_cli/job_cli.rst
examples/README.md
job_templates/cyclic_cc_pt/info.conf
job_templates/cyclic_pt/info.conf
job_templates/psi_csv/info.conf
job_templates/sag_cross_np/info.conf
job_templates/sag_cse_pt/info.conf
job_templates/sag_gnn/info.conf
job_templates/sag_nemo/info.conf
job_templates/sag_np/info.conf
job_templates/sag_np_cell_pipe/info.conf
job_templates/sag_np_metrics/info.conf
job_templates/sag_pt/info.conf
job_templates/sag_pt_deploy_map/info.conf
job_templates/sag_pt_executor/info.conf
job_templates/sag_pt_he/info.conf
job_templates/sag_pt_mlflow/info.conf
job_templates/sag_pt_model_learner/info.conf
job_templates/sag_tf/info.conf
job_templates/sklearn_kmeans/info.conf
job_templates/sklearn_linear/info.conf
job_templates/sklearn_svm/info.conf
job_templates/stats_df/info.conf
job_templates/stats_image/info.conf
job_templates/swarm_cse_pt/info.conf
job_templates/swarm_cse_pt_model_learner/info.conf
job_templates/vertical_xgb/info.conf
job_templates/xgboost_tree/info.conf
nvflare/tool/job/job_cli.py
nvflare/tool/job/job_client_const.py

[2.4] Rename to execution api type, update job command output

---

docs/user_guide/nvflare_cli/job_cli.rst
examples/README.md
job_templates/cyclic_cc_pt/info.conf
job_templates/cyclic_pt/info.conf
job_templates/psi_csv/info.conf
job_templates/sag_cross_np/info.conf
job_templates/sag_cse_pt/info.conf
job_templates/sag_gnn/info.conf
job_templates/sag_nemo/info.conf
job_templates/sag_np/info.conf
job_templates/sag_np_cell_pipe/info.conf
job_templates/sag_np_metrics/info.conf
job_templates/sag_pt/info.conf
job_templates/sag_pt_deploy_map/info.conf
job_templates/sag_pt_executor/info.conf
job_templates/sag_pt_he/info.conf
job_templates/sag_pt_mlflow/info.conf
job_templates/sag_pt_model_learner/info.conf
job_templates/sag_tf/info.conf
job_templates/sklearn_kmeans/info.conf
job_templates/sklearn_linear/info.conf
job_templates/sklearn_svm/info.conf
job_templates/stats_df/info.conf
job_templates/stats_image/info.conf
job_templates/swarm_cse_pt/info.conf
job_templates/swarm_cse_pt_model_learner/info.conf
job_templates/vertical_xgb/info.conf
job_templates/xgboost_tree/info.conf
nvflare/tool/job/job_cli.py
nvflare/tool/job/job_client_const.py

Rename to execution api type, update job command output

---

nvflare/cli.py

Update CLI string from 3.6 to 3.7

Update cli string [skip ci]

---

integration/monai/setup.py

Bump up the versions and improve dependency syntax

---

examples/advanced/gnn/README.md

Fixes # .
Some minor improvements to make pip install commands consistent and explain script behaviors.

[2.4] update gnn readme

---

examples/advanced/cifar10/cifar10-sim/figs/plot_tensorboard_events.py
examples/advanced/cifar10/cifar10-sim/run_simulator.sh
nvflare/app_common/workflows/base_fedavg.py
nvflare/app_common/workflows/model_controller.py

Fixes # .
Fixes the output director for simulator runs and global model selection.

[2.4] Fix CIFAR-10 global model selection

---

nvflare/app_common/workflows/cyclic_ctl.py

Cyclic controller did not check the ReturnCode of client task.  When the client task contained ReturnCode!=OK, cyclic controller kept processing the returned results in client tasks, which could cause problems.
This PR adds the ReturnCode check.  When it's not OK, cyclic controller calls FLComponent's system_panic to indicate such issue.

[2.4] Enhance the handling of RC of task returned from clients

---

nvflare/app_common/workflows/cyclic_ctl.py

This is the cherry-pick of 8694ebcf6a8bef736b3a707bd9aea9aef100c22a.

Enhance the handling of RC of task returned from clients

---

examples/advanced/cifar10/cifar10-sim/figs/plot_tensorboard_events.py
examples/advanced/cifar10/cifar10-sim/run_simulator.sh
examples/advanced/gnn/README.md
nvflare/app_common/workflows/base_fedavg.py
nvflare/app_common/workflows/model_controller.py

Fixes # .
Apply recent PRs from 2.4 branch to main (#2334, #2333)

Update cifar10 and gnn examples

---

nvflare/app_common/launchers/subprocess_launcher.py

This PR removes the logfile for child process.  The child process stdout and stderr will be redirected to subprocess_launcher's logger.

Replace logfile with the logging facility

---

integration/nemo/examples/peft/README.md
integration/nemo/examples/prompt_learning/README.md
integration/nemo/examples/supervised_fine_tuning/README.md

[2.4] Clarify nemo example readme

---

nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/app/simulator/simulator_worker.py

Cherry pick missing PR https://github.com/NVIDIA/NVFlare/pull/2270

[2.4] Enhance simulator END_RUN event handling mechanism

---

nvflare/app_common/executors/client_api_launcher_executor.py
nvflare/app_common/executors/launcher_executor.py
nvflare/app_common/executors/task_exchanger.py
nvflare/fuel/utils/pipe/cell_pipe.py
nvflare/fuel/utils/pipe/file_pipe.py
nvflare/fuel/utils/pipe/pipe.py
nvflare/fuel/utils/pipe/pipe_handler.py

Fix Pipe and PipeHandler

---

tests/integration_test/data/test_configs/standalone_job/internal_tf.yml

add setup section for tf integration test

[2.4] Setup for tf load_data

---

tests/integration_test/data/test_configs/standalone_job/internal_tf.yml

main version of https://github.com/NVIDIA/NVFlare/pull/2359

Setup for tf load_data

---

examples/nvflare_setup.ipynb
tests/integration_test/data/test_configs/standalone_job/hello_tf_examples.yml
tests/integration_test/data/test_configs/standalone_job/internal_tf.yml

Add addition setup sections for load_data() to avoid corruption

[2.4] tf dataset setup and teardown

---

examples/nvflare_setup.ipynb
tests/integration_test/data/test_configs/standalone_job/hello_tf_examples.yml
tests/integration_test/data/test_configs/standalone_job/internal_tf.yml

Add addition setup sections for load_data() to avoid corruption

tf dataset setup and teardown

---

integration/nemo/examples/README.md

Fixes # .
Fixes wrong link to SFT example.

Fix nemo example link

---

.github/workflows/markdown-links-check.yml
.github/workflows/premerge.yml
examples/advanced/cifar10/README.md
examples/advanced/cifar10/cifar10-sim/README.md
examples/advanced/nlp-ner/README.md
examples/advanced/sklearn-kmeans/README.md
examples/advanced/sklearn-linear/README.md
examples/advanced/sklearn-svm/README.md
examples/advanced/vertical_federated_learning/cifar10-splitnn/README.md
examples/tutorials/flare_simulator.ipynb

[2.4] Update outdated links

---

.github/workflows/markdown-links-check.yml
.github/workflows/premerge.yml
examples/advanced/cifar10/README.md
examples/advanced/cifar10/cifar10-sim/README.md
examples/advanced/nlp-ner/README.md
examples/advanced/sklearn-kmeans/README.md
examples/advanced/sklearn-linear/README.md
examples/advanced/sklearn-svm/README.md
examples/advanced/vertical_federated_learning/cifar10-splitnn/README.md
examples/tutorials/flare_simulator.ipynb

Update outdated links

---

integration/nemo/examples/README.md

Fixes # .
Fixes wrong link to SFT example.

[2.4] Fix nemo example link

---

nvflare/app_opt/xgboost/tree_based/executor.py
nvflare/app_opt/xgboost/tree_based/shareable_generator.py
nvflare/app_opt/xgboost/tree_based/utils.py

Move common method outside to a utils file

Update xgboost tree code

---

nvflare/apis/shareable.py
nvflare/apis/utils/reliable_aux_msg.py
nvflare/apis/utils/reliable_message.py

Added support for reliable message to be used by XGBoost native implementation.

Reliable aux msg

---

nvflare/fuel/utils/pipe/file_pipe.py

Clean up file pipe, same as #2369

[2.4] Clean up file pipe

---

nvflare/apis/shareable.py
nvflare/apis/utils/reliable_message.py

[2.4] Added ReliableMessage

---

nvflare/fuel/f3/drivers/net_utils.py

An one-line change to add agrpcs/ngrpcs as secure scheme.

[2.4] Added AGRPCS, NGRPCS as secure scheme

---

nvflare/fuel/f3/cellnet/cell.py

CellPipe's channel or all user defined application channels should have streaming capabilities unless otherwise opt out.

[2.4] Enable StreamCell for all application channels

---

docs/programming_guide/controllers/client_controlled_workflows.rst
nvflare/app_common/ccwf/cyclic_client_ctl.py
nvflare/app_common/ccwf/cyclic_server_ctl.py

same as https://github.com/NVIDIA/NVFlare/pull/2411 for main

Update rr_order to cyclic_order

---

docs/programming_guide/controllers/client_controlled_workflows.rst
nvflare/app_common/ccwf/cyclic_client_ctl.py
nvflare/app_common/ccwf/cyclic_server_ctl.py

- Fixes bug [1878](https://jirasw.nvidia.com/browse/FLARE-1878)
- Update rr_order to cyclic_order for client-controlled cyclic

[2.4] Update rr_order to cyclic_order

---

nvflare/fuel/f3/drivers/net_utils.py
nvflare/fuel/utils/fobs/README.rst

Merge following changes made to 2.4 to main branch,
Updated FOBS README to add DatumManager
Added agrpcs, ngrpcs as secure scheme

Updated FOBS readme to add DatumManager, added agrpcs as secure scheme

---

examples/advanced/experiment-tracking/mlflow/experiment_tracking.ipynb
examples/advanced/experiment-tracking/mlflow/jobs/hello-pt-mlflow/app/config/config_fed_server.conf
examples/advanced/experiment-tracking/mlflow/jobs/hello-pt-tb-mlflow/app/config/config_fed_server.conf
examples/advanced/experiment-tracking/wandb/jobs/hello-pt-wandb/app/config/config_fed_server.json

[2.4] Fix mlflow tag links

---

nvflare/client/api.py

Send needs to check for the object type.

[2.4] Add client api send check

---

nvflare/app_common/executors/launcher_executor.py

A copy of #2370 on the 2.4 branch

[2.4] Fix LauncherExecutor handle_event

---

setup.cfg

Bump Werkzeug 3.0.1
grpcio 1.62.1
to avoid:
https://github.com/advisories/GHSA-6628-q6j9-w8vg
https://github.com/advisories/GHSA-px8h-6qxv-m22q

[2.4] Upgrade dependencies versions

---

nvflare/client/api.py

If the fl_model is not FLModel, raise TypeError

Add check to client api send method

---

nvflare/client/api.py

#2425 has a typo
Fix api send typo

Fix api send typo

---

setup.cfg

Upgrade protobuf version to 4.24.4

[2.4] Upgrade protobuf version

---

.github/workflows/blossom-ci.yml
.github/workflows/codeql.yml
.github/workflows/markdown-links-check.yml
.github/workflows/premerge.yml

Upgrade github actions to newer versions

[2.4] Update github actions

---

docs/real_world_fl/operation.rst

https://github.com/NVIDIA/NVFlare/pull/2453 for main

Clarify download_job workspace delay

---

nvflare/apis/fl_constant.py
nvflare/apis/utils/reliable_message.py
nvflare/private/fed/app/deployer/server_deployer.py
nvflare/private/fed/client/client_runner.py
nvflare/private/fed/server/server_runner.py

Fixes # .
This PR applies changes of https://github.com/NVIDIA/NVFlare/pull/2452 to 2.5.

Improve reliable msg

---

nvflare/app_common/workflows/cyclic_ctl.py
nvflare/app_common/workflows/model_controller.py
nvflare/app_common/workflows/scatter_and_gather.py
nvflare/app_common/workflows/scatter_and_gather_scaffold.py
research/auto-fed-rl/src/autofedrl/autofedrl_scatter_and_gather.py
research/fed-sm/jobs/fedsm_prostate/app/custom/workflows/scatter_and_gather_fedsm.py

Same as https://github.com/NVIDIA/NVFlare/pull/2463 for 2.4 branch

[2.4] Add garbage collect at ends of round-based workflows

---

nvflare/app_common/workflows/cyclic_ctl.py
nvflare/app_common/workflows/model_controller.py
nvflare/app_common/workflows/scatter_and_gather.py
nvflare/app_common/workflows/scatter_and_gather_scaffold.py
research/auto-fed-rl/src/autofedrl/autofedrl_scatter_and_gather.py
research/fed-sm/jobs/fedsm_prostate/app/custom/workflows/scatter_and_gather_fedsm.py

Add garbage collect at ends of round-based workflows

---

nvflare/apis/wf_controller_spec.py
nvflare/app_common/workflows/base_fedavg.py
nvflare/app_common/workflows/model_controller.py
nvflare/app_common/workflows/scaffold.py
nvflare/app_common/workflows/wf_controller.py

- Add WFController wrapper to implement WFControllerSpec with ModelController
- change min_responses to be based on number of targets
- fix Controller vs FLComponentWrapper initialize() conflict

Add WFController

---

nvflare/private/fed/client/admin.py
nvflare/private/fed/server/server_engine.py

Fixes # .
cherry-pick the fix_submit_job_auth_failure to 2.4 branch.

[2.4] cherry-pick the fix_submit_job_auth_failure to 2.4 branch

---

.github/workflows/premerge.yml

Fix premerge github action using --no-cache-dir

[2.4] Fix premerge

---

nvflare/lighter/impl/cert.py

This PR is a cherry-pick of #2469

Add warning when the same admin in project.yml has different role

---

nvflare/app_common/workflows/model_controller.py

Fixes # .
Fix a typo in ModelController

Fix a typo in ModelController

---

nvflare/fuel/f3/cellnet/cell.py
nvflare/fuel/utils/pipe/cell_pipe.py

Fixes # .
Improved Cell's error handling;
Removed wait_for_reply since it's not reliable.

Fix wait-for-reply

---

nvflare/private/fed/server/job_runner.py

Fixes # .
Added more logging for the job status changing.

[2.4] Added more logging for the job status changing

---

examples/advanced/finance/jobs/2_cyclic/app_server/config/config_fed_server.json
examples/advanced/finance/jobs/2_histogram/app_site-1/config/config_fed_client.json
examples/advanced/finance/jobs/2_histogram/app_site-2/config/config_fed_client.json
examples/advanced/finance/jobs/vertical_xgb/app/config/config_fed_client.json
examples/advanced/xgboost/histogram-based/jobs/base/app/config/config_fed_client.json
examples/advanced/xgboost/tree-based/jobs/cyclic_base/app/config/config_fed_server.json
job_templates/vertical_xgb/config_fed_client.conf

Fix xgboost integration tests

---

nvflare/app_common/workflows/cyclic_ctl.py

Follows PR https://github.com/NVIDIA/NVFlare/pull/2484,
we need to change the handle_dead_job method, 
the current implementation is flawed as it does not wait for the grace period.
Controllers should not handle client dropping, we will enhance this properly after 2.5
- Fix client drop handling
- Allow users to pass custom "order" for relay
- Print out more logs

[2.3] Fix CyclicController bug

---

examples/hello-world/hello-tf2/jobs/hello-tf2/app/custom/trainer.py
examples/hello-world/hello_world.ipynb

This PR fixes two issues on hello-tensorflow section of hello-world jupyter notebook.
The first one is the env variable set inside notebook take no effects in the POC clients because all POC sites and server are up and running before that cell runs.  To set that env var properly, this PR added two lines of codes at the very beginning of trainer.py of hello tf2 example.  This will ensure that env var been set in all clients before starting any TF2 related codes. 
The second issue is the path of server workspace in POC changed and needs to be updated.

Fix issues on hello-world TF2 notebook

---

nvflare/apis/fl_constant.py
nvflare/apis/impl/controller.py
nvflare/apis/responder.py
nvflare/app_common/workflows/cyclic_ctl.py
nvflare/private/fed/server/fed_server.py
nvflare/private/fed/server/server_commands.py
nvflare/private/fed/server/server_engine.py
nvflare/private/fed/server/server_runner.py
nvflare/private/fed/server/sys_cmd.py

Fixes # .
This PR added following improvement to v2.3:
- Improved dead client determination logic
- Added log messages for dead client event tracking
- Added a debug admin command for analyzing dead client events
- Improved Cyclic Controller

[2.3] Improve dead client handling

---

setup.cfg

Follows #2426 and #2436 to upgrade deps on main

Upgrade dependencies

---

examples/advanced/psi/user_email_match/README.md
examples/advanced/psi/user_email_match/jobs/user_email_match/app/config/config_fed_client.conf
examples/advanced/psi/user_email_match/jobs/user_email_match/app/config/config_fed_server.conf
job_templates/psi_csv/config_fed_client.conf
job_templates/psi_csv/config_fed_server.conf

Use full path for PSI components

---

nvflare/apis/utils/reliable_message.py
nvflare/fuel/f3/drivers/aio_grpc_driver.py
nvflare/fuel/f3/drivers/grpc_driver.py
nvflare/private/fed/app/client/sub_worker_process.py
nvflare/private/fed/app/simulator/simulator_worker.py

Cherry-pick following bug fixes PRs:
#2447
#2457
#2458
#2474

Multiple bug fixes from 2.4

---

nvflare/app_common/executors/client_api_launcher_executor.py
nvflare/app_common/executors/launcher_executor.py
nvflare/app_common/executors/task_exchanger.py
nvflare/app_common/widgets/metric_relay.py
nvflare/fuel/f3/cellnet/cell.py
nvflare/fuel/utils/pipe/cell_pipe.py
nvflare/fuel/utils/pipe/file_pipe.py
nvflare/fuel/utils/pipe/pipe.py
nvflare/fuel/utils/pipe/pipe_handler.py

Cherry-picking the following PRs:
#2415 
#2442
#2441 
#2433
#2413
#2478
#2495 
#2496 
#2502

Enhancements from 2.4

---

nvflare/apis/impl/wf_comm_server.py

Use controller name for stats

---

integration/monai/examples/spleen_ct_segmentation_local/README.md
integration/monai/examples/spleen_ct_segmentation_sim/README.md

Update monai integration readme

[2.4] Update monai readme [skip ci]

---

nvflare/dashboard/cli.py
nvflare/lighter/impl/master_template.yml

Backport this feature from main branch to 2.4.

[2.4] Backport AWS VPC/Subnet enhancement from main branch

---

setup.cfg

Fixes https://github.com/advisories/GHSA-w3h3-4rj7-4ph4

[2.4] Upgrade gunicorn

---

examples/hello-world/hello-tf2/README.md
examples/hello-world/ml-to-fl/tf/README.md
examples/hello-world/ml-to-fl/tf/code/cifar10_tf_fl.py
examples/hello-world/ml-to-fl/tf/code/cifar10_tf_multi_gpu_fl.py
examples/hello-world/ml-to-fl/tf/code/cifar10_tf_multi_gpu_original.py
examples/hello-world/ml-to-fl/tf/code/cifar10_tf_original.py
examples/hello-world/ml-to-fl/tf/code/tf_net.py
job_templates/sag_tf/config_fed_server.conf
nvflare/app_opt/tf/model_persistor.py

Fixes # .
Update the tensorflow example to use the latest version of TF and Keras.
```
tensorflow==2.16.1
keras==3.3.3
```
Note, this change is also compatible with the TF container including keras==2.15.0 [nvidia/tensorflow:24.04-tf2-py3](https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow)
Now, the model summary shows correctly
```
_________________________________________________________________
Layer (type)                Output Shape              Param #   
=================================================================
conv2d (Conv2D)             (None, 30, 30, 32)        896       
max_pooling2d (MaxPooling2  (None, 15, 15, 32)        0         
D)                                                              
conv2d_1 (Conv2D)           (None, 13, 13, 64)        18496 …
```

Update TF2 example

---

nvflare/job_config/fed_job.py
tests/unit_test/job_config/fed_job_test.py

Fixes # .
- Added target validation for job API, also added the unit test.
1. must provide a target name
2. target name can not use special character

Added target validation for job API

---

nvflare/private/fed/client/client_app_runner.py

Fixes # .
add the runner_config to the client, available through client_engine. Use the runner_config to dynamically add more FLComponent.

add the runner_config to the client

---

nvflare/app_common/workflows/base_fedavg.py

Fixes # .
Added empty results check for aggregate_fn in base_fedavg. in the aggregate() will catch the raised exception and handle the aggregation error.

Added empty results check for aggregate_fn

---

nvflare/apis/utils/reliable_message.py

Fixes # .
This PR fixes QA bug https://nvbugspro.nvidia.com/bug/4687940 in 2.4.

[2.4] Fix missing replying arg

---

nvflare/apis/utils/reliable_message.py

Fixes # .
This PR fixes the QA bug https://nvbugspro.nvidia.com/bug/4687940

[2.5] fix missing replying var

---

nvflare/apis/client_engine_spec.py
nvflare/apis/server_engine_spec.py
nvflare/private/fed/client/client_engine.py
nvflare/private/fed/client/client_run_manager.py
nvflare/private/fed/server/server_engine.py
tests/unit_test/app_common/job_schedulers/job_scheduler_test.py

Fixes # .
Added engine.add_component() function. This allows the component implementation to dynamically add more components and handler to the system.

Added engine.add_component() function

---

nvflare/apis/client_engine_spec.py
nvflare/apis/server_engine_spec.py
nvflare/private/fed/client/client_engine.py
nvflare/private/fed/client/client_run_manager.py
nvflare/private/fed/server/server_engine.py
tests/unit_test/app_common/job_schedulers/job_scheduler_test.py

Fixes # .
Enable the add_component() function to engine. Also add the handlers if needed.

Added engine.add_component() function -- 2.4 branch

---

nvflare/private/fed/app/simulator/simulator_runner.py
nvflare/private/fed/app/simulator/simulator_worker.py
nvflare/private/fed/app/utils.py
tests/unit_test/private/fed/app/simulator/simulator_runner_test.py

Fixes # .
Added Simulator HE support for 2.4 branch.

Added Simulator HE support --- [2.4]

---

MANIFEST.in

Update MANIFEST.in file to include nvflare/libs/*.so files into the wheel file

Build process update

---

setup.py

Update the setup.py on version number and improve the way to get the base version.  Mainly for non-release build.

Update setup.py for base version and nightly build

---

nvflare/app_opt/xgboost/histogram_based_v2/sec/partial_he/util.py

Fixes FLARE-2032.
Changed HE code to use current version of ipcl on pypi.

[2.4] Support IPCL version from pypi

---

MANIFEST.in

Add nvflare/libs/*.so into wheel build.
This PR is a cherry-pick from main branch.

Update MANIFEST.in file to include nvflare/libs/*.so files into the

---

nvflare/dashboard/cli.py

Add feedback when users launch dashboard to cloud with editable version

---

web/src/components/gettingStarted.astro
web/src/components/tutorials.astro

- sharepoint -> google drive video embeddings to fix access issues
- abbreviated tags

Use google drive video embeddings

---

setup.cfg

Fixes # .
Fixed the wrong numpy version for release.

Fixed the numpy release version

---

setup.cfg

Fixes # .
Fixed the wrong numpy version for the nvflare release.

[2.4] Fix numpy release version

---

nvflare/app_opt/xgboost/histogram_based_v2/runners/xgb_client_runner.py

Change default plugin from nvflare to cuda_paillier.

[2.4] Change default plugin to cuda_paillier

---

setup.cfg

This PR upgrade the installation dependency, Werkzeug, to 3.0.3.

Resolve CVE with updated dependency

---

examples/advanced/cifar10/cifar10-sim/jobs/cifar10_scaffold/cifar10_scaffold/config/config_fed_server.json
examples/advanced/lr-newton-raphson/job/newton_raphson/app/config/config_fed_server.json
research/fed-bpt/job_templates/fedbpt/config_fed_server.conf
tests/integration_test/data/jobs/pt_mc_cyclic/app/config/config_fed_server.conf

Fixes [2096](https://jirasw.nvidia.com/browse/FLARE-2096): Add additional updates for min_clients to num_clients for BaseFedAvg

Updates for num_clients

---

nvflare/job_config/fed_job.py

Fixes # .
Support server-side custom scripts in job API. This is needed to deploy code to both clients and server.

Support server side custom scripts in job API

---

examples/advanced/README.md
examples/advanced/federated-statistics/hierarchical_stats/README.md

Fixes # .
Stats examples READMEs
This changes adds federated hierarchical stats example link in `examples/advanced/README.md` and changes images size in `hierarchical_stats/README.md` as the images were appearing smaller in the web browser.

Update stats READMEs

---

examples/hello-world/ml-to-fl/pt/code/cifar10_ddp_fl.py
examples/hello-world/ml-to-fl/pt/code/cifar10_ddp_original.py

Fix torch ddp issue reported in https://github.com/pytorch/pytorch/issues/98763
Solution follows comment: https://github.com/pytorch/pytorch/issues/98763#issuecomment-1503854003

Fix torch ddp

---

examples/advanced/job-level-authorization/setup.sh

If users set poc dir to other places, this setup.sh will fail, need to set it back.

Enhance job auth setup script

---

nvflare/fuel/utils/pipe/pipe_handler.py

Fixes # .
This PR fixes the issue reported in https://jirasw.nvidia.com/browse/FLARE-1945.
Pipe handler has a thread for reading data from pipe and checking pipe status. At the same time, the pipe handler could be stopped at any time and the pipe object is set to None. This PR makes the reading thread safe by ensuring the pipe object is not None before accessing its methods.

[2.5] Fix pipe handler race condition handling

---

nvflare/app_common/metrics_exchange/metrics_sender.py

Add MetricsSender docstring

---

nvflare/lighter/impl/cert.py

Remove serialization of pfx (#2721)

---

examples/advanced/federated-statistics/README.md
examples/advanced/xgboost/histogram-based/README.md

Fix broken link in examples/advanced/federated-statistics/README.md

Fix missing link

---

nvflare/app_common/storages/filesystem_storage.py

Fixes # .
This PR fixes the bug reported in https://nvbugspro.nvidia.com/bug/4781526.

[2.5] Fix clone job to keep original job

---

integration/monai/setup.py

Also update its nvflare version to ~=2.5.0rc1

Bump up the version of monai-nvflare package to 0.2.9

---

examples/tutorials/setup_poc.ipynb

Minor fix for instructions in setup_poc.ipynb in the examples/tutorials folder.

Minor fix for instructions in setup_poc.ipynb for main

---

examples/getting_started/pt/src/train_eval_submit.py
examples/getting_started/pt/swarm_script_executor_cifar10.py

…r10 example.
Fixes # .
fixed the CrossSiteEvalClientController in swarm_script_executor_cifar10 example. Allow run the example with "cpu" only.

fix the CrossSiteEvalClientController in swarm_script_executor_cifar10

---

examples/hello-world/ml-to-fl/np/code/train_loop.py
nvflare/app_common/launchers/subprocess_launcher.py

Cherry-pick https://github.com/NVIDIA/NVFlare/pull/2350 and https://github.com/NVIDIA/NVFlare/pull/2351

Cherry pick launcher log fix

---

nvflare/fuel/hci/client/cli.py

Fix loading cli history in admin console

---

nvflare/fuel/utils/pipe/pipe_handler.py

Fixes # .
This PR applies changes of https://github.com/NVIDIA/NVFlare/pull/2728 to 2.4.

[2.4] Fix pipe handler race condition handling

---

examples/getting_started/pt/swarm_script_executor_cifar10.py

…ar10.
Fixes # .
Fixed the cross validation wrong config for swarm_script_executor_cifar10 example.

fixed the cross validation wrong config for swarm_script_executor_cifar10

---

examples/advanced/xgboost/histogram-based/jobs/base_v2/app/config/config_fed_server.json
examples/advanced/xgboost/utils/prepare_job_config.py
tests/integration_test/data/test_configs/standalone_job/xgb_histogram_examples.yml
tests/integration_test/data/test_configs/standalone_job/xgb_tree_examples.yml

Follows recent PR changes and update example and CI

Update xgboost example and ci

---

examples/advanced/vertical_xgboost/code/vertical_xgb/vertical_data_loader.py
examples/advanced/xgboost/histogram-based/jobs/base/app/custom/higgs_data_loader.py
examples/advanced/xgboost/histogram-based/jobs/base_v2/app/custom/higgs_data_loader.py
examples/advanced/xgboost/tree-based/jobs/bagging_base/app/custom/higgs_data_loader.py
examples/advanced/xgboost/tree-based/jobs/cyclic_base/app/custom/higgs_data_loader.py
nvflare/app_opt/xgboost/data_loader.py
nvflare/app_opt/xgboost/histogram_based/executor.py
nvflare/app_opt/xgboost/histogram_based_v2/runners/xgb_client_runner.py

There are more and more attributes that the XGBDataLoader needs, for example:
- rank
- client_id
- data_split_mode
Add these as base class property attributes and remove from method signature so child classes can easily get them.
And don't need to change method signature in the future when more information is needed.

Refactor XGBDataLoader

---

nvflare/app_opt/he/homomorphic_encrypt.py

Fix HE docstring typo

---

nvflare/fuel/utils/pipe/pipe_handler.py

Update newly renamed branch with commit.

fix race condition handling if pipe handler (#2729)

---

examples/advanced/xgboost_secure/README.md
examples/advanced/xgboost_secure/prepare_flare_job.sh
examples/advanced/xgboost_secure/run_training_flare.sh
examples/advanced/xgboost_secure/train_standalone/train_federated.py
job_templates/xgboost/config_fed_server.conf

Update xgboost example

---

setup.cfg

Fixes # .
Allow newer version of grpcio and protobuf.

Relax grpcio/protobuf versions

---

web/src/components/hero.astro
web/src/components/tutorials.astro
web/src/pages/index.astro

- banner link to nvidia flare day registration
- hide highlights section by default

Add NVIDIA FLARE DAY banner

---

integration/xgboost/encryption_plugins/README.md
integration/xgboost/encryption_plugins/cuda_plugin/src/cuda_plugin.h

- Added more information on how to run and how to build.
- Removed unused codes.

Remove unused code and update README

---

examples/hello-world/hello-fedavg-numpy/fedavg_script_runner_hello-numpy.py
examples/hello-world/hello-fedavg-numpy/hello-fedavg-numpy_getting_started.ipynb

Add NPModelPersistor to hello-fedavg-numpy

---

nvflare/job_config/script_runner.py

Remove basename in ScriptRunner

---

web/src/components/code.astro

Update site code blocks and links

---

research/quantifying-data-leakage/src/nvflare_gradinv/filters/gradinv.py

Fixes # .
Fixes dtype errors with newer versions of torch and numpy.

Gradient inversion fix dtype error

---

examples/advanced/random_forest/model_validation.sh
examples/advanced/random_forest/random_forest.ipynb

Fixes updated simulator model path for validation.

Update simulator folder path for random forest example

---

nvflare/app_opt/xgboost/histogram_based/controller.py

XGBoost change the signature of run_federated_server in 2.1.1
Update controller to use xgb new syntax

[2.4] Update controller to use xgb new syntax

---

nvflare/apis/utils/reliable_message.py

Fixes # .
This PR further improves the race condition handling in RM, especially in handling requests after reply was sent.

improve race condition handling

---

docs/release_notes/flare_250.rst
examples/advanced/bionemo/README.md

Fixes # .
- Fix the bionemo framework version used in the instructions to 1.0
- Fix docs formatting

BioNeMo examples: fix docs

---

tests/integration_test/data/test_configs/standalone_job/pt_job.yml

Fix ci test configs format issue

Fix ci test configs format issue

---

examples/advanced/random_forest/jobs/random_forest_base/app/config/config_fed_client.json
examples/advanced/vertical_xgboost/README.md
examples/advanced/vertical_xgboost/prepare_data.sh

Fixes findings regarding GPU utilization from QA.
Explicitly add use_gpus item to job so that it can be updated

Update random forest and vertical xgb examples

---

docs/programming_guide/controllers/model_controller.rst
docs/release_notes/flare_250.rst
examples/advanced/job_api/pt/src/cifar10_lightning_fl.py
examples/getting_started/pt/nvflare_lightning_getting_started.ipynb
examples/getting_started/pt/nvflare_pt_getting_started.ipynb
examples/getting_started/pt/src/cifar10_lightning_fl.py
examples/getting_started/tf/nvflare_tf_getting_started.ipynb
examples/hello-world/hello-fedavg/README.md
web/src/components/code.astro
web/src/components/gettingStarted.astro
web/src/components/hero.astro
web/src/components/tutorials.astro

Site, docs, and example updates

---

examples/tutorials/flare_simulator.ipynb

Hello-numpy-cross-val is changed to use new style.
- Update to use old style example hello-numpy-sag

Update flare simulator tutorial

---

tests/integration_test/data/jobs/hello-pt-cse/app/custom/train.py

Fix hello-pt-cse job

---

examples/advanced/vertical_xgboost/README.md
job_templates/vertical_xgb/config_fed_server.conf
nvflare/app_opt/flower/executor.py
nvflare/app_opt/xgboost/histogram_based_v2/runners/xgb_client_runner.py

Add vertical xgboost gpu instructions
- Update job template
- Fix readme

Add vertical xgboost gpu instructions

---

docs/user_guide/federated_xgboost/secure_xgboost_user_guide.rst
examples/advanced/xgboost_secure/README.md

Changed split_mode to data_split_mode in README file in XGBoost example folder.

Fixed XGBoost Example README

---

examples/advanced/cifar10/cifar10-sim/jobs/cifar10_fedavg/cifar10_fedavg/config/config_fed_server.json
examples/advanced/cifar10/cifar10-sim/jobs/cifar10_fedprox/cifar10_fedprox/config/config_fed_server.json

Fix cifar10 examples num_clients

---

tests/integration_test/data/jobs/hello-pt-cse/app/custom/train.py
tests/integration_test/data/test_configs/standalone_job/pt_job.yml

Fix data save path of test job

Fix data save path

---

nvflare/app_opt/xgboost/histogram_based/executor.py

XGB 2.1.1 change api we need to change our code as well.
change to new xgb api.

[2.4] Fix xgb api call

---

tests/integration_test/data/jobs/hello-pt-cse/app/custom/train.py
tests/integration_test/data/test_configs/standalone_job/pt_job.yml

This time I verified using Jenkins testing build, so we will be good for this test after this PR.
- Change to absolute path
- Remove CrossValResultValidator as that is not compatible with new cross model eval model controller

Fix ci path

---

docs/release_notes/flare_250.rst

[2.5] doc fix typo

---

examples/advanced/random_forest/README.md
examples/advanced/random_forest/random_forest.ipynb
examples/advanced/sklearn-linear/README.md
examples/advanced/sklearn-linear/sklearn_linear_higgs.ipynb
examples/advanced/vertical_xgboost/README.md
examples/advanced/xgboost/README.md
examples/advanced/xgboost/data_job_setup.ipynb
examples/hello-world/step-by-step/higgs/README.md

Fixes higgs link that no longer works.
Replace it with a new link

Update higgs data link

---

web/src/components/code.astro
web/src/components/gettingStarted.astro
web/src/components/series.astro
web/src/components/tutorials.astro
web/src/layouts/Layout.astro
web/src/pages/index.astro

Add flare series section, enhancements

---

examples/tutorials/setup_poc.ipynb

[2.4] Add job template dir in setup_poc.ipynb

---

nvflare/client/api.py
nvflare/client/api_spec.py
nvflare/client/ex_process/api.py
nvflare/client/in_process/api.py
nvflare/client/model_registry.py
nvflare/client/task_registry.py

[2.5] Add check before api send 25

---

.github/DISCUSSION_TEMPLATE/q-a.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/premerge.yml
nvflare/cli.py
nvflare/private/fed/app/utils.py
setup.cfg
tests/unit_test/fuel/utils/component_builder_test.py

Add support to newer python version

Add support to newer python version

---

.github/workflows/deploy.yml
web/astro.config.mjs
web/src/components/code.astro
web/src/components/footer.astro
web/src/components/gettingStarted.astro
web/src/components/hero.astro
web/src/components/overview.astro
web/src/components/series.astro
web/src/components/tutorials.astro
web/src/pages/404.astro
web/src/pages/agnostic.astro
web/src/pages/research.astro
web/src/pages/security.astro

- change to deploy site from gh-pages branch
- allow switching of versions at `https://nvidia.github.io/NVFlare/version/{branch}` (keep main branch at `https://nvidia.github.io/NVFlare`, add version dropdown selector
- update github and internal links
- will cherry-pick to 2.5 after merged

Add web branch versioning

---

examples/advanced/psi/user_email_match/requirements.txt

update openmind-psi to 2.0.5 for python 3.12 support

---

nvflare/app_opt/tf/job_config/model.py
nvflare/app_opt/tf/model_persistor.py

Fix tf model persistor and tf model
- add missing argument
- allow passing persistor object

Fix tf model persistor and tf model

---

nvflare/app_opt/pt/job_config/base_fed_job.py
nvflare/app_opt/pt/job_config/model.py
nvflare/app_opt/tf/job_config/base_fed_job.py
nvflare/app_opt/tf/job_config/model.py
nvflare/app_opt/tf/model_persistor.py
nvflare/job_config/script_runner.py

Cherry-pick:
#2983 #2984 #2985

[2.5] Allow JobAPI wrapper customization

---

docs/examples/federated_statistics_overview.rst
docs/examples/hello_world_examples.rst
docs/examples/medical_image_analysis.rst
docs/examples/tutorial_notebooks.rst
docs/release_notes/flare_250.rst
docs/user_guide/federated_xgboost/secure_xgboost_user_guide.rst
docs/user_guide/flower_integration/flower_job_structure.rst
docs/user_guide/security/data_privacy_protection.rst
docs/user_guide/security/serialization.rst
examples/getting_started/tf/run_jobs.sh
examples/hello-world/hello-tf/requirements.txt
integration/xgboost/encryption_plugins/README.md

- Fix typos
- For github links change to use github_nvflare_link

Fix doc typo and VDR reported issues

---

docs/examples/federated_statistics_overview.rst
docs/examples/hello_world_examples.rst
docs/examples/medical_image_analysis.rst
docs/examples/tutorial_notebooks.rst
docs/release_notes/flare_250.rst
docs/user_guide/federated_xgboost/secure_xgboost_user_guide.rst
docs/user_guide/flower_integration/flower_job_structure.rst
docs/user_guide/security/data_privacy_protection.rst
docs/user_guide/security/serialization.rst
examples/getting_started/tf/run_jobs.sh
examples/hello-world/hello-tf/requirements.txt
integration/xgboost/encryption_plugins/README.md

Fix doc typo and VDR reported issues, equivalent to #2994

[2.5] Fix doc typo and VDR reported issues

---

nvflare/client/lightning/__init__.py

[2.5] Expose init in client lightning api

---

examples/hello-world/hello-flower/README.md
examples/hello-world/hello-flower/flwr-pt-tb/flwr_pt_tb/client.py
examples/hello-world/hello-flower/flwr-pt-tb/flwr_pt_tb/server.py
examples/hello-world/hello-flower/job.py
nvflare/app_opt/flower/flower_pt_job.py

[2.5] Update flwr job object, client, server

---

nvflare/client/lightning/__init__.py

Expose init in client lightning api

Expose init in client lightning api

---

web/src/components/gettingStarted.astro
web/src/components/hero.astro
web/src/components/series.astro
web/src/components/tutorials.astro
web/src/pages/flareDay.astro

Enhance web responsive design for mobile

---

nvflare/fuel/utils/fobs/fobs.py

[2.5] Fix fobs issue

---

integration/monai/setup.py
setup.cfg

Update the required python versions for nvflare and monai_nvflare

[2.5] Update version and python requires

---

nvflare/app_opt/pt/job_config/model.py

[2.5] Fix PTModel optional arguments

---

nvflare/app_opt/pt/job_config/model.py

Fixes [2274](https://jirasw.nvidia.com/browse/FLARE-2274)

Fix PTModel optional arguments

---

research/fed-bpt/README.md
research/fed-bpt/requirements.txt

Fixes # .
Fix fedbpt cma version and upgrade to Python 3.12

FedBPT: Fix fedbpt cma version

---

setup.cfg

To be compatible with other packages, set numpy less than 2.0.0

[2.5] Set numpy less than 2.0.0

---

docs/real_world_fl/overview.rst

Cherry-pick Fixed broken doc ref to 'helm_chart' (#3022)

[2.5] Cherry-pick Fixed broken doc ref to 'helm_chart' (#3022) [skip ci]

---

examples/hello-world/hello-pt/requirements.txt

[2.5] Fix hello-pt req [skip ci]

---

web/src/components/code.astro

[2.5] Remove extra "." [skip ci]

---

docker/Dockerfile

This PR is to update the dockerfile which builds the docker image for dashboard.

[2.5] Bump up python version of Dockerfile

---

nvflare/lighter/impl/aws_template.yml
nvflare/lighter/impl/azure_template.yml

This is a cherry pick of #3063.

Update dashboard cloud base image version to meet Python 3.9

---

tests/unit_test/apis/impl/controller_test.py

Adjust the timing to produce stable result and add comments to the tests
Adjust the timing to produce stable result and add comments to the tests

Fix controller sequential relay test

---

nvflare/lighter/impl/master_template.yml
tests/integration_test/data/test_configs/authorization/shell_commands.yml

Follows the recent logging changes #3057 , the output of "ls" command changed.
Changed output accordingly

Fix auth ls command response

---

nvflare/private/fed/app/simulator/simulator_runner.py

Fixes # .
Fixed the simulator without custom folder job run error. Added check for the custom folder existence.

[2.5] --- Fix the simulator without custom folder job run error

---

nvflare/app_opt/xgboost/histogram_based_v2/adaptors/xgb_adaptor.py
nvflare/app_opt/xgboost/histogram_based_v2/aggr.py
nvflare/app_opt/xgboost/histogram_based_v2/controller.py
nvflare/app_opt/xgboost/histogram_based_v2/sec/client_handler.py
nvflare/app_opt/xgboost/histogram_based_v2/sec/partial_he/adder.py
nvflare/app_opt/xgboost/histogram_based_v2/sec/partial_he/encryptor.py
nvflare/app_opt/xgboost/histogram_based_v2/sec/partial_he/util.py

1. Not repeating pubkey in encrypter
2. Using shared memory for encrypted GH in adder
3. Added more debug log statements

[2.5] XGB Optimization using Shared Memory

---

nvflare/private/fed/client/client_engine.py
nvflare/private/fed/client/client_executor.py

Fixes # .
Removed the extra client app custom folder when running a job.

Remove the extra client app custom folder

---

nvflare/lighter/provision.py

Fixes #3093.
This PR is a cherry-pick of #3106.

[2.5] Cherry pick 3106

---

nvflare/private/fed/client/client_engine.py

Fixes # .
Removed the extra client app customer folder.

[2.5] --- Remove the extra client app custom folder 

---

nvflare/private/fed/app/deployer/server_deployer.py
nvflare/private/fed/client/client_engine.py
nvflare/widgets/fed_event.py

Fixes # .
Added support to send fed event for SP and CP.

Add SP/CP fed event runner

---

.github/workflows/blossom-ci.yml

Cherrypick malware scan change to branch 2.5 [skip ci]

---

docs/resources/log_config.json
docs/user_guide/configurations/logging_configuration.rst
nvflare/fuel/utils/log_utils.py
nvflare/lighter/impl/master_template.yml
nvflare/lighter/templates/master_template.yml
nvflare/private/fed/app/simulator/log_config.json
nvflare/private/fed/app/simulator/simulator_runner.py

- factor out fl_ctx from message into log record attribute
- improve formatter inheritance
- add exclude_logger_names option to LoggerNameFilter
- fix simulator log_config path for running directory

Logging enhancements

---

docs/resources/log_config.json
docs/user_guide/configurations/logging_configuration.rst
examples/tutorials/custom_log_config.json
examples/tutorials/logging.ipynb
nvflare/lighter/impl/master_template.yml
nvflare/lighter/templates/master_template.yml
nvflare/private/fed/app/simulator/log_config.json

Add logging tutorial notebook

---

MANIFEST.in
docs/user_guide/configurations/logging_configuration.rst
examples/tutorials/custom_log_config.json
examples/tutorials/logging.ipynb
nvflare/lighter/impl/master_template.yml
nvflare/private/fed/app/simulator/log_config.json

[2.5] Cherry-pick logging notebook and fix

---

nvflare/app_opt/pt/client_api_launcher_executor.py
nvflare/app_opt/pt/in_process_client_api_executor.py

Change ParamsConverter logs to debug level

---

nvflare/fuel/utils/log_utils.py

[2.5] Fix log fl_ctx parsing

---

examples/advanced/kaplan-meier-he/km_job.py

Fixes # .
Otherwise the default pytorch launcher will be used, which is not necessary

Specify framwork for km exmaple

---

nvflare/app_common/logging/__init__.py

Add init file for log sender and receiver

---

examples/getting_started/pt/nvflare_lightning_getting_started.ipynb
examples/getting_started/pt/nvflare_pt_getting_started.ipynb
examples/getting_started/tf/nvflare_tf_getting_started.ipynb
examples/hello-world/hello-fedavg/hello-fedavg.ipynb

Skip npx degit confirmation in notebooks

---

nvflare/fuel/utils/log_utils.py

Allow logs with levels greater than info through filter

---

nvflare/app_common/filters/svt_privacy.py

Fixes # .
Update the internal variable names to be captured by job API

SVTPrivacy: update member variable names

---

examples/hello-world/hello-flower/flwr-pt-tb/pyproject.toml
examples/hello-world/hello-flower/flwr-pt/pyproject.toml

Fixes # .
update flower dependencies for `enter` / `exit` support and remove simulation dependencies not used by NVFlare.

update flower dependencies

---

examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.0_introduction/introduction.ipynb
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.1_identity_security/identity_security.ipynb
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.2_site_security_privacy_policy/site_policy.ipynb
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.3_customized_site_security/custom_client_side_auth_system_integration/keycloak_integration.ipynb
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.3_customized_site_security/custom_client_side_job_level_authorization/client_side_security_check.ipynb
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.3_customized_site_security/custom_server_side_authentication/server_side_security_plugin.ipynb
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.3_customized_site_security/customized_site_security.ipynb
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.4_communication_security/communication_security.ipynb
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.5_message_serialization/fobs.ipynb
examples/tutorials/self-paced-training/part-4_advanced_federated_learning/chapter-10_federated_XGBoost/10.2_secure_fed_xgboost/secure_fed_xgboost.ipynb
examples/tutorials/self-paced-training/part-5_federated_learning_applications_in_industries/chapter-12_federated_learning_in_financial_services/12.0_introduction/introduction.ipynb

Fixes # .
Chapter 12: add fraud detection words at the top level notebook
Chapter 10: secure xgb, explain the risk, and what we are protection against in both Horizontal and Vertical cases
Chapter 6: typo/language fixes

Update tutorail notebooks

---

examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.2_site_security_privacy_policy/site_policy.ipynb
examples/tutorials/self-paced-training/welcome.ipynb

Tutorials: Fix missing instructions

---

docs/user_guide/configurations/logging_configuration.rst
nvflare/fuel/utils/log_utils.py

Cherry-pick from https://github.com/NVIDIA/NVFlare/pull/3291

[2.6] Logging fix and clarifications

---

examples/tutorials/self-paced-training/part-1_federated_learning_introduction/part_1_introduction.ipynb
examples/tutorials/self-paced-training/part-4_advanced_federated_learning/chapter-9_flare_low_level_apis/09.0_introduction/introduction.ipynb
examples/tutorials/self-paced-training/part-4_advanced_federated_learning/part-4_introduction.ipynb
examples/tutorials/self-paced-training/part-5_federated_learning_applications_in_industries/part-5_introduction.ipynb
examples/tutorials/self-paced-training/welcome.ipynb

[Tutorials] Fix broken links

---

research/fed-bpt/src/cma_decomposer.py

Fixes # .
Adds CMAOptionsDecomposer to support decomposing of CMA related components.

[2.6] Fix cma_decomposer

---

nvflare/apis/utils/reliable_message.py

Fixes # .
This PR cleans up unnecessary error logs of ReliableMessage. It also changes the log level from INFO to DEBUG for non-essential log messages.

[2.6] Clean up msg log of ReliableMessage

---

.github/workflows/deploy.yml
.github/workflows/premerge.yml

[2.6] Update github workflow

---

docs/quickstart.rst
docs/user_guide/configurations/logging_configuration.rst
docs/user_guide/nvflare_cli/fl_simulator.rst
examples/tutorials/flare_simulator.ipynb
nvflare/fuel/utils/log_utils.py

cherry-pick from https://github.com/NVIDIA/NVFlare/pull/3307

[2.6] Fix log exception dict, example and doc updates [skip ci]

---

nvflare/lighter/impl/azure.py

Fixes # .
Added missing pattern replacement to azure builder.

[2.6] Fix azure start scripts generation in azure builder

---

nvflare/fuel/f3/streaming/tools/receiver.py
nvflare/fuel/f3/streaming/tools/sender.py

The sender.py may fail if the connection is not established faster enough. Added an event to 
wait for receiver to go online.

[2.6] Fixed a race condition in testing tool

---

examples/advanced/brats18/README.md

Fixes # .
Add clarification to Brats for data split question

Add clarification to brats

---

MANIFEST.in

[2.6] Remove old log config from MANIFEST.in

---

nvflare/cli.py

[2.6] Add exit code when nvflare provision encounter exception

---

nvflare/dashboard/cli.py
nvflare/lighter/templates/aws_template.yml
nvflare/lighter/templates/azure_template.yml

Some user messages in dashboard were outdated after the format of credential env var changed.
This PR made the messages consistent.

[2.6] Fix dashboard user message

---

docs/release_notes/flare_260.rst
docs/user_guide/dashboard_api.rst

Add to docs about the added prefix for dashboard API, changes for removing HA, and polish docs.
Add to docs about the added prefix for dashboard API, changes for removing HA, and polish docs. Made more concise and professional.

Add docs about dashboard prefix

---

README.md

[2.6] Update README

---

nvflare/app_opt/pt/file_model_persistor.py

Fixes # .
Apply https://github.com/NVIDIA/NVFlare/pull/3317 to main branch

Update PyTorch Persistor

---

README.md
docs/real_world_fl/cloud_deployment.rst
web/src/components/hero.astro
web/src/components/series.astro
web/src/components/tutorials.astro

Sync 2.6 changes back to main : Web, README 

---

examples/hello-world/ml-to-fl/pt/README.md
examples/hello-world/ml-to-fl/pt/pt_client_api_job.py
examples/hello-world/ml-to-fl/pt/src/cifar10_lightning_ddp_fl.py
examples/hello-world/ml-to-fl/pt/src/cifar10_lightning_ddp_original.py
examples/hello-world/ml-to-fl/pt/src/lit_net.py
nvflare/client/task_registry.py

Fixes #3360.
- Added is_rank0 check in nvflare/client/task_registry.py when "get_task"

[2.6] Fix ClientAPI + multi GPU

---

examples/advanced/xgboost/fedxgb_secure/README.md
examples/advanced/xgboost/fedxgb_secure/xgb_fl_job.py

Fixes # .
Same updates as https://github.com/NVIDIA/NVFlare/pull/3391 to 2.6 branch

[2.6] Apply same xgb updates to 2.6 as main 

---

web/src/pages/index.astro

Add FLARE DAY 2025 call for submission banner

---

examples/hello-world/ml-to-fl/pt/README.md
examples/hello-world/ml-to-fl/pt/lightning_job.py
examples/hello-world/ml-to-fl/pt/src/cifar10_lightning_ddp_fl.py

Cherry-pick [2.6] Enhance lightning DDP example (#3421)

---

integration/monai/examples/mednist/requirements.txt
integration/monai/examples/spleen_ct_segmentation_local/requirements.txt
integration/monai/examples/spleen_ct_segmentation_sim/requirements.txt

Fixes # .
Apply https://github.com/NVIDIA/NVFlare/pull/3434 to main branch

MONAI examples: update nvflare version

---

.github/workflows/.lycheeignore
.github/workflows/markdown-links-check.yml
docs/release_notes/flare_220.rst
docs/release_notes/flare_230.rst
docs/release_notes/flare_250.rst
docs/user_guide/federated_xgboost/secure_xgboost_user_guide.rst
examples/advanced/finance/README.md
examples/advanced/job_api/tf/README.md
examples/advanced/kaplan-meier-he/README.md
examples/advanced/lr-newton-raphson/README.md
examples/advanced/monitoring/README.md
examples/advanced/monitoring/jobs/README.md
examples/advanced/sklearn-kmeans/README.md
examples/advanced/xgboost/README.md
examples/advanced/xgboost/fedxgb_secure/README.md
examples/getting_started/tf/README.md
examples/hello-world/README.md
examples/hello-world/step-by-step/README.md
job_templates/readme.md

The original gaurav-nelson/github-action-markdown-link-check@1.0.15 is no longer maintained.
And it has some false cases.
Switch to an actively maintained github action https://github.com/lycheeverse/lychee-action
- Switch to an actively maintained github action https://github.com/lycheeverse/lychee-action
- Fix failed links

[2.6] Use lychee to do link check

---

examples/advanced/experiment-tracking/mlflow/jobs/hello-pt-mlflow-client/code/src/training_script.py
examples/advanced/experiment-tracking/mlflow/jobs/hello-pt-mlflow/code/src/train_script.py
examples/advanced/experiment-tracking/tensorboard/jobs/tensorboard-streaming/code/src/train_script.py
examples/advanced/job_api/pt/src/train_eval_submit.py
examples/getting_started/pt/src/train_eval_submit.py
examples/hello-world/hello-fedavg/src/cifar10_fl.py
examples/hello-world/step-by-step/cifar10/code/fl/train.py
examples/hello-world/step-by-step/cifar10/code/fl/train_with_mlflow.py
examples/hello-world/step-by-step/cifar10/cse/cse.ipynb
examples/tutorials/self-paced-training/part-1_federated_learning_introduction/chapter-1_running_federated_learning_applications/01.2_convert_deep_learning_to_federated_learning/code/src/client.py
examples/tutorials/self-paced-training/part-1_federated_learning_introduction/chapter-1_running_federated_learning_applications/01.3_server_side_customization/code/src/client.py
examples/tutorials/self-paced-training/part-1_federated_learning_introduction/chapter-1_running_federated_learning_applications/01.4_client_side_customization/code/src/client.py
examples/tutorials/self-paced-training/part-1_federated_learning_introduction/chapter-1_running_federated_learning_applications/01.5_experiment_tracking/01.5.1_experiment_tracking_with_tensorboard/code/src/client.py
examples/tutorials/self-paced-training/part-1_federated_learning_introduction/chapter-1_running_federated_learning_applications/01.5_experiment_tracking/01.5.2_experiment_tracking_with_mlflow/code/src/client.py
examples/tutorials/self-paced-training/part-1_federated_learning_introduction/chapter-1_running_federated_learning_applications/01.5_experiment_tracking/01.5.2_experiment_tracking_with_mlflow/code/src/client_mlflow.py
examples/tutorials/self-paced-training/part-2_federated_learning_system/chapter-3_federated_computing_platform/03.2_deployment_simulation/code/src/client.py
examples/tutorials/self-paced-training/part-2_federated_learning_system/chapter-3_federated_computing_platform/03.4_system_monitoring/jobs/setup-1/code/src/client.py
examples/tutorials/self-paced-training/part-2_federated_learning_system/chapter-3_federated_computing_platform/03.4_system_monitoring/jobs/setup-2/code/src/client.py
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.2_site_security_privacy_policy/code/federated-policies/jobs/src/client.py
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.3_customized_site_security/custom_client_side_auth_system_integration/code/src/client.py
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.3_customized_site_security/custom_client_side_job_level_authorization/code/src/client.py
nvflare/app_opt/pt/job_config/base_fed_job.py

[2.6] Fix typos

---

examples/advanced/llm_hf/README.md
examples/advanced/llm_hf/llm_hf_fl_job.py
examples/advanced/llm_hf/requirements.txt
examples/advanced/llm_hf/utils/hf_sft_peft_iter.py

Fixes # .
Same updates as https://github.com/NVIDIA/NVFlare/pull/3456

Apply same VDR updates as 2.6 to main

---

examples/advanced/experiment-tracking/mlflow/jobs/hello-pt-mlflow-client/code/src/training_script.py
examples/advanced/experiment-tracking/mlflow/jobs/hello-pt-mlflow/code/src/train_script.py
examples/advanced/experiment-tracking/tensorboard/jobs/tensorboard-streaming/code/src/train_script.py
examples/advanced/job_api/pt/src/train_eval_submit.py
examples/getting_started/pt/src/train_eval_submit.py
examples/hello-world/hello-fedavg/src/cifar10_fl.py
examples/hello-world/step-by-step/cifar10/code/fl/train.py
examples/hello-world/step-by-step/cifar10/code/fl/train_with_mlflow.py
examples/hello-world/step-by-step/cifar10/cse/cse.ipynb
examples/tutorials/self-paced-training/part-1_federated_learning_introduction/chapter-1_running_federated_learning_applications/01.2_convert_deep_learning_to_federated_learning/code/src/client.py
examples/tutorials/self-paced-training/part-1_federated_learning_introduction/chapter-1_running_federated_learning_applications/01.3_server_side_customization/code/src/client.py
examples/tutorials/self-paced-training/part-1_federated_learning_introduction/chapter-1_running_federated_learning_applications/01.4_client_side_customization/code/src/client.py
examples/tutorials/self-paced-training/part-1_federated_learning_introduction/chapter-1_running_federated_learning_applications/01.5_experiment_tracking/01.5.1_experiment_tracking_with_tensorboard/code/src/client.py
examples/tutorials/self-paced-training/part-1_federated_learning_introduction/chapter-1_running_federated_learning_applications/01.5_experiment_tracking/01.5.2_experiment_tracking_with_mlflow/code/src/client.py
examples/tutorials/self-paced-training/part-1_federated_learning_introduction/chapter-1_running_federated_learning_applications/01.5_experiment_tracking/01.5.2_experiment_tracking_with_mlflow/code/src/client_mlflow.py
examples/tutorials/self-paced-training/part-2_federated_learning_system/chapter-3_federated_computing_platform/03.2_deployment_simulation/code/src/client.py
examples/tutorials/self-paced-training/part-2_federated_learning_system/chapter-3_federated_computing_platform/03.4_system_monitoring/jobs/setup-1/code/src/client.py
examples/tutorials/self-paced-training/part-2_federated_learning_system/chapter-3_federated_computing_platform/03.4_system_monitoring/jobs/setup-2/code/src/client.py
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.2_site_security_privacy_policy/code/federated-policies/jobs/src/client.py
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.3_customized_site_security/custom_client_side_auth_system_integration/code/src/client.py
examples/tutorials/self-paced-training/part-3_security_and_privacy/chapter-6_Security_in_federated_compute_system/06.3_customized_site_security/custom_client_side_job_level_authorization/code/src/client.py
nvflare/app_opt/pt/job_config/base_fed_job.py

Cherry-pick [2.6] Fix typos (#3450)

---

.github/workflows/.lycheeignore
.github/workflows/markdown-links-check.yml
docs/release_notes/flare_220.rst
docs/release_notes/flare_230.rst
docs/release_notes/flare_250.rst
docs/user_guide/federated_xgboost/secure_xgboost_user_guide.rst
examples/advanced/finance/README.md
examples/advanced/job_api/tf/README.md
examples/advanced/kaplan-meier-he/README.md
examples/advanced/lr-newton-raphson/README.md
examples/advanced/monitoring/README.md
examples/advanced/monitoring/jobs/README.md
examples/advanced/sklearn-kmeans/README.md
examples/advanced/xgboost/README.md
examples/advanced/xgboost/fedxgb_secure/README.md
examples/getting_started/tf/README.md
examples/hello-world/README.md
examples/hello-world/step-by-step/README.md
job_templates/readme.md

The original gaurav-nelson/github-action-markdown-link-check@1.0.15 is no longer maintained.
And it has some false cases.
Switch to an actively maintained github action
https://github.com/lycheeverse/lychee-action
- Switch to an actively maintained github action https://github.com/lycheeverse/lychee-action
- Fix failed links
Fixes # .

Cherry-pick [2.6] Use lychee to do link check (#3454)

---

examples/advanced/finance/requirements.txt
examples/advanced/psi/user_email_match/requirements.txt
examples/advanced/vertical_federated_learning/cifar10-splitnn/requirements.txt
examples/advanced/xgboost/requirements.txt

Should be openmined-psi >= 2.0.5
Some requirements.txt files are wrong

[2.6] Update openmined-psi version

---

tests/unit_test/fuel/f3/streaming/streaming_test.py

About 10% of the time this unit test will timeout, increase the timeout from 300 to 400.
for example: https://github.com/NVIDIA/NVFlare/actions/runs/14784508640/job/41510397924 
increase the timeout from 300 to 400 for this unit test.

[2.6] Increase stream act timeout for unit test

---

examples/advanced/experiment-tracking/wandb/src/net.py
nvflare/app_opt/tracking/wandb/wandb_receiver.py

Fix WandBReceiver bug.
- Use job api for WandB example.
- Fix WandBReceiver bug.
---------
Fixes # .

Cherry-pick [2.6] Update WandB code and example (#3429)

---

docs/installation.rst

Fix installation doc formatting issue
Fix installation doc formatting issue

[2.6] Fix installation doc

---

examples/advanced/finance/requirements.txt
examples/advanced/psi/user_email_match/requirements.txt
examples/advanced/vertical_federated_learning/cifar10-splitnn/requirements.txt
examples/advanced/xgboost/requirements.txt

Should be openmined-psi >= 2.0.5
Some requirements.txt files are wrong

Cherry-pick [2.6] Update openmined-psi version (#3467)

---

web/package-lock.json
web/package.json
web/src/layouts/Layout.astro

Fix prismjs loading

---

nvflare/app_opt/pt/file_model_persistor.py
tests/integration_test/data/test_configs/authorization/shell_commands.yml
tests/integration_test/src/utils.py

[2.5] Fix 2.5 Jenkins CI

---

examples/advanced/bionemo/README.md
nvflare/client/api.py

Fixes # .
Adding https://github.com/NVIDIA/NVFlare/pull/3523

[2.6] Add rank type check for client API

---

web/src/pages/index.astro

Remove flare day banner

---

examples/hello-world/hello-lr/README.md
examples/hello-world/hello-lr/job.py
nvflare/app_common/workflows/lr/fedavg.py

Fixes # .
Few changes did not work, restore back to the old logics

LR: Restore it back few logics

---

examples/advanced/distributed_optimization/README.md

Fixes a typo in the distributed_optimization examples README

fix typo in distributed optimization README

---

README.md
docs/getting_started.rst

update readme and getting started

---

nvflare/private/stream_runner.py

And fix the message
And fix the message

Change Stream Runner shutdown print to debug

---

examples/tutorials/flare_api.ipynb
nvflare/fuel/flare_api/flare_api.py

Fixes # .
https://jirasw.nvidia.com/browse/FLARE-2645
https://jirasw.nvidia.com/browse/FLARE-2644

Bug Fixes : FLARE-2645, 2644

---

nvflare/edge/device/android/app/src/main/java/com/nvidia/nvflare/app/controllers/FlareRunnerController.kt
nvflare/edge/device/android/app/src/main/java/com/nvidia/nvflare/ui/MainActivity.kt
nvflare/edge/device/android/sdk/ETTrainerExecutor.kt
nvflare/edge/device/android/sdk/config/ConfigProcessor.kt
nvflare/edge/device/android/sdk/core/AndroidFlareRunner.kt
nvflare/edge/device/android/sdk/training/ETTrainer.kt
nvflare/edge/device/android/sdk/training/TrainingConfig.kt
nvflare/edge/device/android/sdk/utils/Constants.kt

Fix android job selection logic to resolve the issue brought up by QA when changing jobs.

Fix android job selection logic

---

nvflare/edge/assessors/async_num.py

Fixes QA 5532344.
We have an update on model version control and auto aggregator keeping, which changes the content of selection list, the async_num will need to be updated accordingly for it to run

Update async_num assessor's selection list content

---

examples/hello-world/hello-cyclic/README.md
examples/hello-world/hello-cyclic/job.py
nvflare/app_opt/pt/recipes/cyclic.py
nvflare/app_opt/tf/recipes/cyclic.py
nvflare/recipe/cyclic.py

Add PT/TF specific CyclicRecipe for better UX
Add PT/TF specific CyclicRecipe for better UX

Add PT/TF specific CyclicRecipe for better UX

---

examples/hello-world/step-by-step/cifar10/stats/image_stats_job.py

Fixes # .
job_name is changed to "name"

fix job name due to argument name change
